# -*- coding: utf-8 -*-
import json

path = '/Users/yepz/JSweb/data/modules.json'

with open(path, 'r', encoding='utf-8') as f:
    data = json.load(f)

# Module 1.22 — Microgravedad (ISS) ~1,000 words
text_1_22 = """Imagina que entras en un ascensor en el piso 100 de un rascacielos. De repente, el cable se rompe y el ascensor empieza a caer libremente hacia el suelo. Durante esos aterradores segundos de caída, tú y todo lo que hay dentro del ascensor —tu mochila, tu teléfono, las llaves— estaríais flotando. No es que la gravedad haya desaparecido; la Tierra sigue tirando de ti con la misma fuerza. Lo que ocurre es que tú y el ascensor estáis cayendo exactamente a la misma velocidad, por lo que no hay ninguna superficie (el suelo) que empuje tus pies hacia arriba. Esa es, en esencia, la vida en la **Estación Espacial Internacional (ISS — International Space Station; un laboratorio de investigación que orbita la Tierra a unos 408 km de altitud; es el objeto artificial más grande en el espacio y un esfuerzo de colaboración entre 15 naciones)**: un estado de caída libre perpetua que llamamos **microgravedad (Microgravity — condición en la que las personas u objetos parecen no tener peso; aunque hay gravedad, la aceleración de caída libre anula la sensación de peso; se llama 'micro' porque existen pequeñas perturbaciones gravitacionales o aceleraciones residuales de millonésimas de G)**.

¿Cómo es posible caer permanentemente sin chocar nunca contra el suelo? La respuesta está en la **velocidad orbital (Orbital Velocity — la velocidad horizontal necesaria para que la curvatura de la caída de un objeto coincida exactamente con la curvatura de la Tierra; para la ISS, esta velocidad es de aproximadamente 7.66 km/s o 27,600 km/h; a esta velocidad, la estación cae hacia la Tierra pero 'falla' el suelo constantemente porque el planeta se curva debajo de ella)**. Newton lo explicó con su famoso experimento mental del cañón: si disparas una bala de cañón lo suficientemente fuerte, la bala caerá hacia la Tierra, pero la superficie terrestre se curvará hacia abajo al mismo ritmo que la trayectoria de la bala. En lugar de estrellarse, la bala dará la vuelta al mundo. Eso es una órbita. Por eso los astronautas no "flotan" porque no hay gravedad —a 400 km de altura, la gravedad terrestre es todavía el 90% de la que sentimos aquí abajo—; flotan porque están "cayendo alrededor" de la Tierra a una velocidad estrepitosa.

Vivir en este "ascensor infinito" cambia todas las reglas de la física que conocemos. En la Tierra, el aire caliente sube y el frío baja; esto lo llamamos **convección (Convection — el movimiento de fluidos —líquidos o gases— causado por diferencias de densidad bajo la influencia de la gravedad; el calor hace que el aire se dilate, se vuelva menos denso y suba; en microgravedad, este proceso desaparece porque no hay un 'arriba' o 'abajo' definido por el peso)**. Sin convección, las cosas se comportan de forma extraña. Si enciendes una vela en la ISS, la llama no es alargada y amarilla, sino una esfera azul perfecta que se apaga rápidamente porque el CO₂ que expulsa se queda rodeando la mecha en lugar de subir, asfixiando el fuego. Esto permite a los científicos estudiar la **combustión (Combustion — reacción química de oxidación rápida con desprendimiento de energía luminosa y calorífica; en microgravedad se produce de forma más limpia y uniforme, revelando mecanismos químicos ocultos que en la Tierra son enmascarados por la turbulencia de la convección)** de una forma imposible de observar en nuestro planeta.

Para la ciencia de materiales y la medicina, la microgravedad es una mina de oro. En nuestro planeta, si intentas cultivar cristales de proteínas —fundamentales para diseñar nuevos medicamentos contra el cáncer o virus—, la gravedad y la convección distorsionan el crecimiento, creando cristales imperfectos. En la ISS, los cristales crecen con una simetría atómica casi perfecta porque las moléculas se van depositando una a una sin ser perturbadas por corrientes de aire o sedimentación. Hemos cultivado cristales de insulina y de proteínas del virus de la gripe que son tan puros que han permitido a los químicos mapear su estructura con una resolución nunca vista, acelerando el desarrollo de fármacos.

Pero no todo es ciencia en tubos de ensayo; la vida diaria es un desafío de ingeniería. Imagina intentar beber agua. En microgravedad, los líquidos no se quedan en el fondo del vaso; forman esferas flotantes debido a la **tensión superficial (Surface Tension — la fuerza microscópica que mantiene unidas las moléculas en la superficie de un líquido; en ausencia de peso, esta fuerza domina y empuja al líquido a adoptar la forma con menor área de superficie posible: una esfera)**. Los astronautas tienen que beber de bolsas selladas con popotes. Las herramientas tienen velcro para no salir volando, y los sacos de dormir están sujetos a las paredes. Incluso ir al baño requiere un sistema de succión por aire para simular el papel que la gravedad juega en la Tierra.

La ISS es, por encima de todo, nuestra escuela para llegar a otros planetas. Es donde aprendemos que la tecnología no es solo circuitos y metal, sino una extensión de nuestra capacidad para hackear las leyes de la naturaleza y sobrevivir donde nuestra biología no debería. Cada experimento en órbita, desde el crecimiento de una lechuga espacial hasta el estudio de la física de fluidos, es un paso hacia misiones más profundas en el sistema solar. La microgravedad nos enseña que el peso es solo una condición local, pero la curiosidad es una fuerza universal."""

# Module 1.23 — Fisiología Humana en G ~1,000 words
text_1_23 = """El cuerpo humano es una obra maestra de la ingeniería evolutiva diseñada para una sola condición específica: vivir en una plataforma rocosa con una aceleración constante de **1G (One G — la aceleración estándar de la gravedad en la superficie de la Tierra, aproximadamente 9.81 m/s²; es la fuerza bajo la cual evolucionaron todos los sistemas biológicos terrestres desde las bacterias hasta los mamíferos)**. Tus huesos están diseñados para soportar tu peso contra el suelo; tu corazón está diseñado para bombear sangre con fuerza suficiente para que llegue a tu cerebro venciendo la gravedad; incluso tus oídos tienen pequeños cristales que te dicen dónde está el "abajo". Cuando sacamos a un humano de este entorno y lo ponemos a vivir en microgravedad, el cuerpo entra en modo de confusión total.

El primer sistema que nota el cambio es el **sistema esquelético**. En la Tierra, tus huesos no son piedras estáticas; son tejidos vivos que se reconstruyen constantemente según el estrés que reciben. Hay una batalla eterna entre dos tipos de células: los **osteoblastos (Osteoblasts — células encargadas de construir nuevo tejido óseo y mineralizar el hueso; requieren el impacto físico del caminar o cargar peso para activarse)** y los **osteoclastos (Osteoclasts — células que reabsorben y destruyen el tejido óseo viejo o no utilizado; en microgravedad su actividad continúa mientras la de los constructores se detiene)**. Sin el estímulo de la gravedad, el cuerpo decide que no necesita un esqueleto tan pesado y empieza a "comerse" sus propios huesos. Un astronauta pierde entre un 1% y un 1.5% de su masa ósea por mes. Para que te des una idea, un mes en el espacio equivale a lo que una persona con osteoporosis avanzada pierde en todo un año en la Tierra. El calcio extraído de los huesos termina en la sangre, lo que aumenta el riesgo de dolorosos cálculos renales.

El corazón también se "relaja" peligrosamente. En la Tierra, la gravedad tira de los fluidos hacia tus pies. Tu sistema cardiovascular tiene que trabajar duro para mantener la sangre circulando hacia arriba. Pero en el espacio, se produce una **redistribución de fluidos (Fluid Shift — el desplazamiento del volumen sanguíneo y linfático desde las extremidades inferiores hacia el torso y la cabeza al desaparecer la fuerza que empuja los fluidos hacia abajo; causa el fenómeno de 'cara hinchada y piernas de pájaro' —Puffy Face, Bird Legs— en los astronautas)**. El cerebro detecta un exceso de sangre en la cabeza y le ordena al cuerpo eliminar líquidos: los astronautas pierden volumen sanguíneo total en pocos días. Al no tener que luchar contra el peso, el corazón se vuelve más pequeño y débil, como un músculo que dejas de entrenar en el gimnasio.

Sin embargo, el descubrimiento más preocupante de los últimos años es el impacto en la visión, conocido como **síndrome VIIP (Visual Impairment and Intracranial Pressure — una condición donde el aumento de la presión del líquido cefalorraquídeo en el cráneo aplana la parte posterior del globo ocular y causa inflamación del nervio óptico)**. En la Tierra el líquido del cerebro drena naturalmente hacia la columna por gravedad; en el espacio se acumula en el cráneo, presionando los ojos desde adentro hacia afuera. Muchos astronautas regresan con cambios permanentes en su vista, necesitando lentes que no usaban antes. Este es hoy uno de los mayores frenos biológicos para enviar misiones de 3 años a Marte: no queremos que los exploradores lleguen ciegos al Planeta Rojo.

Para contrarrestar todo esto, los astronautas no "descansan" en el espacio. Su rutina diaria incluye 2 horas obligatorias de ejercicio extremo. Usan bandas elásticas para amarrarse a caminadoras y máquinas de resistencia que simulan el peso de cientos de kilos. Es una batalla diaria contra la atrofia. También se experimenta con **centrífugas de gravedad artificial (Artificial Gravity / Centrifuge — máquinas que giran a gran velocidad para crear una fuerza centrífuga que el cuerpo interpreta como gravedad; se investiga su uso en naves espaciales del futuro para evitar que el cuerpo se degrade en viajes largos)**, pero la tecnología para implementarlas a gran escala todavía es experimental.

La medicina espacial nos enseña que somos criaturas de la Tierra en el nivel más profundo de nuestras células. Nuestra biología es una respuesta al campo gravitatorio de nuestro planeta. Adaptarnos a vivir en otros mundos no es solo una cuestión de naves espaciales más rápidas, sino de entender cómo hackear nuestra propia fisiología para que la falta de peso no nos destruya. Estudiar a los astronautas en la ISS es, en el fondo, estudiar los límites de la resiliencia humana frente a lo desconocido. Somos polvo de estrellas que aprendió a caminar en 1G, y ahora estamos aprendiendo a volar sin peso."""

# Module 1.24 — Velocidad de Escape ~1,000 words
text_1_24 = """Si quieres lanzar una piedra al aire, regresará a tu mano. Si la lanzas más fuerte, subirá más alto, pero la gravedad de la Tierra eventualmente la detendrá y la traerá de vuelta. Pareciera que estamos atrapados en una prisión invisible de la que nada puede escapar. Pero la física nos dice que hay un límite: si lanzas esa piedra con la fuerza suficiente, alcanzará una velocidad tan alta que la gravedad de la Tierra —aunque nunca se apague del todo— nunca será capaz de detenerla. Esa piedra saldrá disparada hacia el cosmos para siempre. Esa "velocidad mágica" es lo que llamamos **velocidad de escape (Escape Velocity — la velocidad mínima que un objeto sin motores encendidos necesita para alejarse infinitamente de un planeta; depende únicamente de la masa y el radio del cuerpo celeste, no de la masa del objeto que escapa; para la Tierra, este valor es de aproximadamente 11.2 km/s o 40,320 km/h)**.

¿Por qué 11.2 km/s? Imagina la gravedad como un pozo profundo en el que estamos metidos. Para salir del pozo, necesitas energía cinética. Cuanto más masivo es el planeta, más profundo es el pozo. En la Luna, que es mucho más pequeña, la velocidad de escape es de solo 2.4 km/s; por eso los astronautas del Apollo pudieron despegar de regreso con un motor pequeño. En Júpiter, el gigante del sistema solar, el pozo es tan profundo que necesitarías ir a 60 km/s para escapar. En un **agujero negro (Black Hole — una región del espacio-tiempo con una gravedad tan intensa que su velocidad de escape es mayor que la velocidad de la luz —300,000 km/s—; como nada puede ir más rápido que la luz, nada puede escapar de su interior, ni siquiera la luz misma)**, el pozo es infinito: la velocidad de escape es mayor que el límite de velocidad del Universo.

Alcanzar esos 11.2 km/s es el mayor dolor de cabeza de la ingeniería aeroespacial, y todo se resume en lo que los científicos llaman **la tiranía de la ecuación del cohete (Rocket Equation / Tsiolkovsky Equation — formulada por el pionero ruso Konstantin Tsiolkovsky en 1903; establece que para ganar velocidad tienes que quemar combustible, pero ese combustible tiene peso, por lo que necesitas más combustible para mover el combustible, creando un círculo vicioso exponencial)**. Si quieres llevar un satélite de 1 tonelada al espacio profundo, necesitas un cohete que pese cientos de toneladas, porque el 90% del peso del cohete es simplemente el combustible necesario para levantar el propio combustible. Es por eso que los cohetes son en esencia tanques de gasolina gigantes con una pequeña punta de carga útil.

Para vencer esta "tiranía", la humanidad inventó el **despegue por etapas (Staging — la técnica de dividir un cohete en varias secciones que se van descartando conforme se agota su combustible; esto permite al cohete 'adelgazar' en pleno vuelo, eliminando el peso muerto de los tanques vacíos para que las etapas superiores puedan acelerar más fácilmente)**. Sin esta técnica, nunca habríamos llegado ni siquiera a la órbita terrestre. Cuando ves un lanzamiento de SpaceX o de la NASA, los grandes bloques que caen al mar son el sacrificio necesario para que la punta del cohete alcance finalmente la libertad de la velocidad de escape.

Pero, ¿qué pasa si queremos ir a Plutón o fuera del sistema solar? Incluso con los cohetes más grandes, no tenemos suficiente combustible para acelerar todo el camino. Por eso usamos un truco de "ju-jitsu cósmico" llamado **asistencia gravitatoria (Gravity Assist / Slingshot Maneuver — el uso del movimiento orbital de un planeta para lanzar una nave espacial a una velocidad mayor; la nave 'roba' una fracción infinitesimal de la energía orbital del planeta para acelerarse a sí misma)**. Las sondas Voyager 1 y 2 utilizaron a Júpiter y Saturno como catapultas gravitacionales, ganando la velocidad suficiente para convertirse en los primeros objetos humanos en entrar al **espacio interestelar (Interstellar Space — el espacio físico que existe entre las estrellas; la zona donde el viento solar del Sol deja de dominar y el medio interestelar toma el control; la Voyager 1 cruzó esta frontera en 2012, viajando hoy a unos 17 km/s fuera del sistema solar)**.

El futuro de la exploración espacial depende de encontrar formas de escapar de la Tierra sin depender de combustibles químicos pesados. Hoy experimentamos con **motores iónicos (Ion Thrusters — motores que aceleran iones —átomos cargados— mediante campos eléctricos a velocidades altísimas; aunque tienen muy poca fuerza inicial, pueden estar encendidos durante años, alcanzando velocidades finales asombrosas con muy poco combustible)** y soñamos con velas solares que usen la luz del Sol para empujarnos como si fuéramos barcos en un océano cósmico. La velocidad de escape es la frontera definitiva; es el precio que la Tierra nos cobra por dejarnos salir a explorar el resto de nuestra galaxia. Es la medida de nuestra ambición y la prueba máxima de nuestra ingeniería."""

fullTexts = {
    "1.22": text_1_22,
    "1.23": text_1_23,
    "1.24": text_1_24
}

keyPoints = {
    "1.22": ["Microgravedad", "Velocidad Orbital", "ISS", "Convección", "Ciencia de Materiales"],
    "1.23": ["Atrofia Ósea", "Redistribución de Fluidos", "Síndrome VIIP", "Ejercicio Espacial", "1G vs 0G"],
    "1.24": ["Velocidad de Escape", "Pozo Gravitatorio", "Ecuación del Cohete", "Asistencia Gravitatoria", "Motores Iónicos"]
}

updated = 0
for ch in data['chapters']:
    for m in ch['modules']:
        if m['id'] in fullTexts:
            m['fullText'] = fullTexts[m['id']]
            m['keyPoints'] = keyPoints[m['id']]
            updated += 1

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"✅ {updated} módulos (1.22-1.24) expandidos a ~1,000 palabras y actualizados.")
