import json
import os

path = '/Users/yepz/JSweb/data/modules.json'

with open(path, 'r', encoding='utf-8') as f:
    data = json.load(f)

fullTexts = {
    "1.18": """Una de las preguntas más profundas y desconcertantes que un ser humano puede hacerse no es filosófica sino cosmológica: ¿Tiene el Universo un borde? ¿Qué hay más allá? La respuesta de la ciencia moderna es al mismo tiempo satisfactoria y desconcertante: existe un **Universo Observable (Observable Universe — la región del cosmos de la que podemos recibir información; está delimitada no por una pared física sino por el horizonte cósmico, que es el límite más allá del cual la luz no ha tenido tiempo de alcanzarnos desde el Big Bang; está centrado en cada observador, por lo que cada punto del cosmos tiene su propio y único Universo Observable)** con un horizonte definido, más allá del cual no podemos ver ni saber nada, no porque haya una pared física, sino porque la luz de esas regiones no ha tenido tiempo suficiente para alcanzarnos.

El Universo Observable es una esfera centrada exactamente en donde estás tú ahora mismo, con un radio de aproximadamente 46,500 millones de años luz. Espera —si el Universo tiene 13,800 millones de años, ¿cómo puede su radio observable ser 46,500 millones de años luz si la luz solo ha tenido 13,800 millones de años para viajar? La respuesta está en la **expansión del espacio (Expansion of Space — el aumento del tamaño del Universo a lo largo del tiempo; no es que las galaxias se muevan a través del espacio, sino que el espacio mismo se estira entre ellas; esto significa que dos galaxias pueden alejarse entre sí a velocidades superiores a c sin violar la relatividad, porque no se mueven a través del espacio sino que el espacio entre ellas crece)**. Las regiones que emitieron luz hace 13,800 millones de años se han movido alejándose mientras esa luz viajaba hacia nosotros. Hoy están a 46,500 millones de años luz aunque la luz tardó solo 13,800 millones de años en llegar.

El **horizonte cósmico (Cosmic Horizon / Hubble Horizon — el límite del Universo Observable; más allá de él, las galaxias se alejan de nosotros a velocidades superiores a la de la luz debido a la expansión del espacio, por lo que su luz nunca nos alcanzará; no es una pared física sino un límite de información causal)** actúa como una burbuja de información: nada de lo que ocurra más allá puede afectarnos ahora ni en el futuro cercano. La **energía oscura (Dark Energy — la fuerza o propiedad del espacio vacío que está acelerando la expansión del Universo; representa el 68% del contenido total del cosmos; está acercando el horizonte cósmico hacia nosotros con el tiempo, lo que significa que las galaxias lejanas que hoy observamos eventualmente quedarán fuera de nuestro alcance para siempre)** está haciendo que ese horizonte se aleje cada vez más rápido, lo que significa que con el tiempo galaxias que hoy son observables quedarán permanentemente fuera de alcance. En un futuro lejano, el Universo Observable desde la Tierra se irá vaciando progresivamente de galaxias lejanas que cruzarán el horizonte sin retorno.

Dentro de ese Universo Observable, las estimaciones actuales apuntan a aproximadamente **2 billones de galaxias (2 × 10¹² galaxias — estimación publicada en 2016 por el equipo de Christopher Conselice usando imágenes del Telescopio Hubble; superó en un factor de 10 la estimación anterior de 200,000 millones de galaxias; sin embargo, el JWST está encontrando que el Universo temprano era incluso más abundante en galaxias de lo esperado, sugiriendo que esta cifra podría revisarse al alza)**. Si cada galaxia contiene un promedio de 100,000 millones de estrellas, y si cada estrella tiene en promedio un sistema planetario, el número de planetas en el Universo Observable supera los 10²³ —más que el número de átomos en todos los granos de arena de todas las playas de la Tierra juntos. La probabilidad de que en esa vastedad solo exista vida en nuestro pequeño planeta preocupó al físico Enrico Fermi, quien en los años 1950 lo resumió en lo que hoy conocemos como la **Paradoja de Fermi (Fermi Paradox — la aparente contradicción entre las altas probabilidades estadísticas de que exista vida inteligente extraterrestre en el Universo y la total ausencia de evidencia de su existencia hasta ahora; formulada por Enrico Fermi en 1950 durante una conversación casual con colegas en Los Álamos; sigue sin resolverse definitivamente)**: "¿Dónde están todos?"

El **Telescopio Espacial James Webb (JWST — James Webb Space Telescope; el telescopio espacial más grande y potente jamás construido; lanzado el 25 de diciembre de 2021; opera en el punto Lagrange L2 a 1.5 millones de km de la Tierra; observa principalmente en infrarrojo para ver a través del polvo interestelar y detectar galaxias del Universo temprano cuya luz ha sido desplazada hacia el rojo por la expansión cósmica)** identificó en 2022 galaxias formadas apenas 300–400 millones de años después del Big Bang, más brillantes y masivas de lo que los modelos predecían. Esta discrepancia está obligando a cosmólogos y astrofísicos a revisar los modelos de formación galáctica temprana: el Universo parece haber construido galaxias grandes mucho más rápido de lo que pensábamos posible.

La existencia del horizonte observable nos da también una perspectiva filosófica poderosa sobre nuestra posición cósmica. Copérnico en 1543 nos sacó del centro del Sistema Solar. La cosmología moderna nos dice algo más radical: no existe tal centro. Cada punto en el cosmos tiene su propio y único Universo Observable. El tuyo —centrado exactamente donde estás tú ahora leyendo esto— es genuinamente único. Eres el centro de tu propio Universo observable, y al mismo tiempo eres un punto arbitrario en un cosmos de dos billones de galaxias. Ambas cosas son igualmente verdaderas y el Universo no hace distinción entre ellas.""",
    "1.19": """El 14 de febrero de 1990, la sonda espacial **Voyager 1 (Voyager 1 — sonda espacial de la NASA lanzada en septiembre de 1977; la nave hecha por el ser humano que ha viajado más lejos de la Tierra; en 2012 cruzó la heliopausa convirtiéndose en el primer objeto humano en entrar al espacio interestelar; sigue operativa a más de 22,000 millones de km del Sol, comunicándose con la Tierra con una señal que tarda 20 horas en llegar)** estaba a 6,000 millones de kilómetros de la Tierra, más allá de la órbita de Neptuno, cuando el astrónomo Carl Sagan convenció a la NASA de que girara la cámara y fotografiara el sistema solar interior por última vez antes de apagar los instrumentos ópticos para siempre. El resultado fue una de las imágenes más profundas jamás capturadas: un punto diminuto, apenas un píxel de luz azul pálido suspendido en un rayo de luz solar dispersada, flotando en la inmensidad del espacio. Era la Tierra.

Sagan llamó a esa imagen **"El Pálido Punto Azul" (Pale Blue Dot — el título de la fotografía de la Tierra tomada por Voyager 1 el 14 de febrero de 1990 desde una distancia de 6,000 millones de km; la Tierra ocupa menos de 0.12 píxeles en la imagen; se convirtió en el símbolo visual de la perspectiva cósmica y la fragilidad de nuestro planeta; Sagan escribió un libro homónimo en 1994 basado en esta reflexión)** y escribió sobre ella una reflexión que se convirtió en uno de los textos de divulgación científica más citados de la historia. Su mensaje central: toda la historia humana —sus guerras, sus imperios, sus descubrimientos y sus tragedias— ha ocurrido en un grano de polvo suspendido en un rayo de luz solar.

¿Qué hace tan especial a ese Pálido Punto Azul? En términos astronómicos, casi nada: es un planeta rocoso de tamaño mediano en la **Zona de Habitabilidad (Habitable Zone / Goldilocks Zone — la región alrededor de una estrella donde las temperaturas permiten la existencia de agua líquida en la superficie de un planeta rocoso; para el Sol se extiende entre 0.95 y 1.67 Unidades Astronómicas; la Tierra orbita a 1 UA, cómodamente dentro de ella)** de una estrella amarilla enana de tipo G en el brazo de Orión de una galaxia espiral barrada de tamaño mediocre entre los 2 billones de galaxias del Universo Observable. Pero en términos de complejidad organizada de la materia, es posiblemente el objeto más asombroso del que tengamos conocimiento: alberga vida, consciencia, arte, música, ciencia y tecnología. De entre toda la materia del Universo, en este planeta polvo han surgido organismos capaces de preguntarse sobre el origen de las estrellas y los quarks.

El **azul** del punto no es arbitrario. La Tierra se ve azul desde el espacio por dos razones físicas precisas: el 71% de su superficie está cubierta de océanos que absorben las longitudes de onda del rojo e infrarrojo y reflejan preferentemente el azul; y la atmósfera produce el **efecto Rayleigh (Rayleigh Scattering — la dispersión de la luz por partículas mucho más pequeñas que la longitud de onda de la luz, como las moléculas de nitrógeno y oxígeno de la atmósfera; las longitudes de onda cortas —azul y violeta— se dispersan mucho más que las largas; es la razón por la que el cielo diurno es azul y los atardeceres son rojos o naranjas cuando la luz atraviesa más atmósfera)**, que dispersa preferentemente la luz azul. Sin esos océanos líquidos y sin esa atmósfera particular —producto de 3,800 millones de años de evolución biológica que acumuló el oxígeno liberado por la fotosíntesis— el punto sería gris o marrón, como Marte.

El legado de esta imagen fue conceptual y práctico: inspiró a una generación de astrónomos, biólogos y científicos planetarios a dedicar sus carreras a entender qué hace habitable a un planeta, y a buscar otros puntos azules pálidos orbitando otras estrellas. El programa **TESS (Transiting Exoplanet Survey Satellite — satélite de la NASA lanzado en 2018; busca exoplanetas detectando el pequeño oscurecimiento que produce un planeta al transitar frente a su estrella; ha identificado más de 7,000 candidatos a exoplanetas; se enfoca especialmente en estrellas cercanas y brillantes para facilitar el estudio posterior de las atmósferas de sus planetas)** y el JWST buscan activamente exoplanetas con señales de vapor de agua, oxígeno y metano en sus atmósferas: las **biosignaturas (Biosignatures — señales químicas o físicas en la atmósfera o superficie de un planeta que podrían indicar la presencia de vida; incluyen el oxígeno molecular, el metano, el ozono y el vapor de agua en combinaciones que no se explicarían sin procesos biológicos; el JWST es el primer telescopio con capacidad de detectarlas en planetas de otros sistemas estelares)** de la vida tal como la conocemos. La fotografía de Sagan no solo fue una reflexión filosófica: fue el punto de partida de la búsqueda de otros puntos azules en el cosmos.""",
    "1.20": """Si redujéramos el Sol al tamaño de una pelota de baloncesto y lo colocáramos en el centro de Los Ángeles, la estrella más cercana —**Alfa Centauri (Alpha Centauri — el sistema estelar más cercano al Sol; a 4.37 años luz de distancia; es en realidad un sistema triple formado por Alfa Centauri A, Alfa Centauri B y Próxima Centauri; su nombre proviene del griego y significa "el pie del Centauro", la constelación austral en la que aparece; es visible a simple vista desde el hemisferio sur pero no desde la mayor parte de México y otros países del norte)** — estaría en la Ciudad de México. Esta analogía captura la realidad más chocante de la astronomía: incluso nuestros vecinos estelares están a distancias que hacen que cualquier viaje interplanetario humano actual parezca absolutamente trivial en comparación.

Alfa Centauri no es una estrella sino un **sistema estelar triple (Triple Star System — un sistema gravitacionalmente ligado de tres estrellas que orbitan alrededor de su centro de masa común; son más comunes de lo que se pensaba; en el caso de Alfa Centauri, las dos estrellas principales forman un binario cerrado y Próxima Centauri orbita a enorme distancia del par central, posiblemente con un período de varios millones de años)**. Sus tres componentes son **Alfa Centauri A (Alpha Centauri A — estrella de tipo G2V, casi idéntica al Sol en masa y temperatura pero ligeramente más grande y brillante; con Alfa Centauri B forman un sistema binario cuyo período orbital es de 79.9 años; es el tercer objeto más brillante del cielo nocturno)**, **Alfa Centauri B (Alpha Centauri B — estrella de tipo K1V, naranja y más pequeña y fría que el Sol; orbita junto a Alfa Centauri A a una distancia que varía entre 11 y 36 UA en su órbita elíptica)** y **Próxima Centauri (Proxima Centauri — una enana roja de tipo M5.5Ve, la más pequeña y débil de las tres; está ligeramente más cerca de la Tierra que el par central —a 4.24 años luz— convirtiéndola en la estrella más cercana al Sol; es propensa a poderosas llamaradas estelares que podrían esterilizar planetas cercanos)**, una enana roja que actualmente es el objeto estelar más cercano a nuestro Sol.

En 2016, astrónomos del **ESO (European Southern Observatory — la Organización Europea para la Investigación Astronómica en el Hemisferio Austral; opera el observatorio más productivo del mundo en La Silla y Paranal, Chile; construye el ELT —Extremely Large Telescope— de 39 metros de diámetro previsto para 2028)** anunciaron el descubrimiento de un exoplaneta orbitando Próxima Centauri en la zona de habitabilidad: **Próxima b (Proxima b — exoplaneta con masa mínima de 1.17 veces la de la Tierra en órbita a 0.0485 UA de Próxima Centauri con un período de 11.2 días; está en la zona de habitabilidad pero la estrella emite llamaradas de rayos X que podrían erosionar su atmósfera; su habitabilidad es incierta y debatida activamente)**.

Un año luz equivale a 9.461 × 10¹² km, o aproximadamente 9.5 billones de kilómetros. La sonda Voyager 1, que viaja a unos 17 km/s —la sonda hecha por el ser humano más rápida de la historia— tardará más de 75,000 años en recorrer solo un año luz. Llegar a Alfa Centauri con la tecnología actual tomaría unos 300,000 años. No es una barrera de presupuesto ni de voluntad política: es una barrera física de escala cósmica.

¿Es posible algún día llegar en una sola vida humana? El proyecto **Breakthrough Starshot (Breakthrough Starshot — iniciativa científica fundada en 2016 por el físico Stephen Hawking y el empresario Yuri Milner con una inversión inicial de $100 millones; propone enviar una flota de nanosondas del tamaño de un chip, aceleradas por un láser terrestre de alta potencia hasta el 20% de la velocidad de la luz, para llegar a Alfa Centauri en aproximadamente 20 años y fotografiar sus planetas)** propone nanosondas aceleradas por **vela de luz (Light Sail — una vela ultradelgada y ultra ligera hecha de material reflectante que usa la presión de la radiación electromagnética para propulsarse; la misma fuerza que empuja las colas de los cometas lejos del Sol; con suficiente potencia de láser terrestre, una vela microscópica podría ser acelerada hasta fracciones significativas de la velocidad de la luz)** hasta el 20% de **c**, llegando en 20 años. La tecnología que requiere —un láser de tierra de 100 gigavatios, nanosondas de gramos— está en el límite de lo concebible con nuestra física actual.

Estudiar el vecindario estelar más cercano nos pone cara a cara con la pregunta más fundamental para el futuro de la humanidad: ¿somos capaces de convertirnos en una **civilización multiplanetaria e interestelar (Interstellar Civilization — una hipotética civilización capaz de viajar o comunicarse entre sistemas estelares distintos; en la escala de Kardashev —clasificación de civilizaciones por consumo energético— correspondería a una Tipo II o III; ninguna especie conocida ha alcanzado este nivel; si el Homo sapiens lo lograra, sería el mayor salto en su historia evolutiva desde el dominio del fuego)**? La respuesta depende de avances en física de propulsión, materiales, biología del envejecimiento y ética de misiones de siglos. Pero el viaje, en la imaginación y en la ingeniería, ya ha comenzado.""",
    "1.21": """Todo en el Universo está en movimiento. Las galaxias no están estáticas en el espacio sino flotando en corrientes gravitacionales, acercándose y alejándose unas de otras dependiendo de la geometría local del espacio-tiempo. Y nuestra Galaxia, la Vía Láctea, tiene una cita inevitable en el calendario cósmico: dentro de aproximadamente 4,500 millones de años, chocará con nuestra galaxia vecina, **Andrómeda (Andromeda / M31 — la galaxia espiral gigante más cercana a la Vía Láctea; a 2.537 millones de años luz; contiene aproximadamente 1 billón de estrellas —más del doble que la Vía Láctea—; se acerca a nosotros a unos 110 km/s; es visible a simple vista desde zonas de baja contaminación lumínica como una mancha difusa en la constelación de Andrómeda)**, en el evento que los astrónomos han bautizado **Lactómeda (Milkomeda — nombre portmanteau de Milky Way + Andromeda acuñado por los astrónomos John Dubinski y Larry Hernquist; designa la galaxia elíptica gigante que resultará de la fusión gravitacional de la Vía Láctea y Andrómeda en unos 7,000 millones de años desde ahora)**.

Andrómeda es la galaxia espiral más grande del **Grupo Local (Local Group — el pequeño cúmulo gravitacionalmente ligado de galaxias al que pertenece la Vía Láctea; contiene unas 50 galaxias, de las cuales la Vía Láctea y Andrómeda son las dos más masivas; el diámetro del Grupo Local es de aproximadamente 10 millones de años luz)** y se acerca a nosotros a unos 110 kilómetros por segundo. Los astrónomos del Telescopio Espacial Hubble midieron en 2012 su movimiento **lateral (Transverse Velocity — la componente del movimiento de un objeto perpendicular a la línea de visión del observador; es difícil de medir directamente para objetos muy lejanos porque requiere detectar desplazamientos angulares muy pequeños durante períodos de observación largos; la medición de 2012 confirmó que la colisión Vía Láctea-Andrómeda es prácticamente inevitable)** con la precisión suficiente para confirmar que la colisión es prácticamente inevitable.

Pero "colisión" es una palabra engañosa cuando hablamos de galaxias. Las estrellas están separadas entre sí por distancias tan enormes que la probabilidad de que dos estrellas choquen directamente durante la fusión es extremadamente baja. Lo que sí ocurrirá es una **danza gravitacional (Gravitational Dance — la interacción gravitacional compleja entre dos sistemas masivos que se fusionan; las galaxias se atraerán mutuamente, pasarán una "a través" de la otra perturbando las órbitas estelares, se alejarán, serán atraídas de nuevo, y tras múltiples pases y miles de millones de años de interacción, se fusionarán en una sola galaxia)** de millones de años. Las galaxias se atraerán mutuamente, pasarán una a través de la otra perturbando las órbitas estelares, se alejarán, y finalmente, tras múltiples pases, se fusionarán en una sola galaxia elíptica gigante en unos 7,000 millones de años.

Las consecuencias para el Sistema Solar son inciertas pero probablemente no catastróficas para las estrellas individuales. Las simulaciones computacionales muestran que hay una probabilidad no despreciable de que el Sistema Solar sea lanzado a regiones más alejadas del centro de la nueva galaxia fusionada o incluso catapultado fuera de ella. También habrá períodos de intensa **formación estelar (Starburst — período de formación estelar extraordinariamente rápida en una galaxia, generalmente desencadenado por la colisión o interacción gravitacional con otra galaxia; las nubes de gas se comprimen, fragmentan y colapsan formando miles de estrellas nuevas en un tiempo geológicamente breve; produce galaxias con color azulado característico por la abundancia de estrellas masivas jóvenes y calientes)** mientras las nubes de gas de ambas galaxias colisionan y se comprimen, creando oleadas de nuevas estrellas jóvenes visibles incluso en galaxias en fusión que observamos hoy con el Hubble a millones de años luz.

Para cuando Lactómeda ocurra, el Sol habrá comenzado su transición hacia una **gigante roja (Red Giant — la fase evolutiva de una estrella de masa baja o media cuando agota el hidrógeno en su núcleo; el núcleo se contrae y calienta mientras las capas exteriores se expanden enormemente; el Sol aumentará su tamaño hasta unas 200 veces su diámetro actual, posiblemente engullendo a Mercurio y Venus)**, potencialmente absorbiendo las órbitas de Mercurio y Venus. Si todavía existe humanidad en ese momento —o cualquier descendiente reconocible— habrá tenido miles de millones de años de anticipación para migrar a otros sistemas estelares. Lactómeda no es el fin: es la próxima gran transformación del vecindario cósmico que habitamos, tan inevitable como el amanecer del día siguiente y tan remota como el propio fin del Sol.""",
    "1.25": """En la historia de la física, hay un momento legendario que resume el poder de observar el mundo cotidiano con ojos curiosos. Según la historia —que probablemente tiene mucho de mítica pero contiene verdad conceptual—, **Isaac Newton (Isaac Newton — físico, matemático y astrónomo inglés (1643–1727); considerado uno de los científicos más influyentes de la historia; formuló las tres leyes del movimiento, la ley de la gravitación universal, desarrolló el cálculo diferencial e integral de forma independiente a Leibniz, y explicó la naturaleza de la luz con un prisma; su obra Principia Mathematica de 1687 es uno de los libros más importantes de la historia de la ciencia)** estaba sentado bajo un manzano en Woolsthorpe, Lincolnshire, cuando una manzana cayó al suelo frente a él. En lugar de ignorarlo, Newton se preguntó: ¿acaso la misma fuerza que tira de la manzana alcanza hasta la Luna? La respuesta fue la **Ley de la Gravitación Universal (Universal Law of Gravitation — la ley formulada por Newton en 1687 que establece que todo objeto con masa atrae a todo otro objeto con masa con una fuerza directamente proporcional al producto de sus masas e inversamente proporcional al cuadrado de la distancia entre sus centros de masa; es universal porque aplica a todos los objetos con masa en el Universo sin excepción)**, quizás la generalización matemática más poderosa de la historia de la ciencia.

Publicada en su obra *Principia Mathematica* en 1687, la ley dice en su esencia:

**F = G × (M₁ × M₂) / r²**

Donde **F** es la fuerza de atracción gravitacional, **M₁** y **M₂** son las masas de los dos objetos, **r** es la distancia entre sus centros de masa y **G** es la **Constante Gravitacional Universal (Gravitational Constant G — la constante de proporcionalidad de la ley de gravitación de Newton; su valor es 6.674 × 10⁻¹¹ N·m²/kg²; fue medida directamente por primera vez por Henry Cavendish en 1798 usando una balanza de torsión; es la constante fundamental de la física que conocemos con menor precisión relativa incluso hoy, con errores de medición de partes por millón)**: 6.674 × 10⁻¹¹ N·m²/kg². Con esta fórmula, Newton fue capaz de explicar por qué los planetas orbitan el Sol en **elipses (Ellipses — las órbitas de los planetas son elipses con el Sol en uno de los focos, como describió Kepler en su primera ley; Newton demostró matemáticamente que esto es la consecuencia inevitable de una fuerza gravitacional que decae con el cuadrado de la distancia)**, por qué las mareas suben y bajan en sincronía con la Luna, y por qué los cometas regresan en períodos predecibles.

Una implicación crucial de la fórmula es la dependencia con el cuadrado de la distancia: la **ley del inverso del cuadrado (Inverse Square Law — principio que establece que la intensidad de una fuerza o radiación disminuye con el cuadrado de la distancia desde la fuente; si duplicas la distancia, la intensidad se reduce a una cuarta parte; si triplicas la distancia, a una novena parte; aplica a la gravedad, la luz, el sonido en campo libre y los campos eléctrico y magnético)**. Si te alejas de la Tierra al doble de distancia, la gravedad que sientes es cuatro veces menor. Al triple, nueve veces menor. Esta relación garantiza que la gravedad disminuye con la distancia pero nunca llega a exactamente cero —en teoría, la gravitación de la Tierra alcanza hasta el último confín del Universo Observable, aunque de manera inmeasurablemente débil.

La Fuerza G en la cotidianidad no es solo la razón por la que caemos. Es la que mantiene nuestra atmósfera acumulada alrededor del planeta —sin gravedad, las moléculas de aire se escaparían al espacio—. Es la que genera las mareas. Es la que hace que los océanos permanezcan en la superficie. Es la que define cómo se mueven los fluidos dentro de tu cuerpo. La **gravedad de 1G (1G — la aceleración gravitacional en la superficie terrestre, equivalente a 9.81 m/s²; es el valor de referencia estándar de la gravedad; todas las formas de vida en la Tierra han evolucionado durante miles de millones de años bajo esta aceleración específica, moldeando desde la forma de los esqueletos hasta el funcionamiento del sistema cardiovascular)** moldeó evolutivamente cada aspecto de tu biología durante millones de años.

Newton transformó la humanidad porque demostró que el Universo funciona según **leyes matemáticas precisas y universales** que aplican desde una manzana cayendo hasta las órbitas galácticas. La misma ecuación que describe la caída de un objeto desde un puente describe la dinámica de la Vía Láctea alrededor del **Gran Atractor (Great Attractor — una anomalía gravitacional de masa gigantesca ubicada a unos 250 millones de años luz en la dirección de la constelación de Centauro; ejerce atracción gravitacional sobre la Vía Láctea, Andrómeda y docenas de otros cúmulos de galaxias del Supergrupo Local; su naturaleza exacta sigue siendo investigada porque está parcialmente oculta por el plano de la Vía Láctea)**. Esta universalidad de las leyes físicas a todas las escalas es la premisa fundamental de la ciencia moderna: el mismo lenguaje matemático describe el átomo, la manzana, la Luna y el cosmos. Newton fue quien primero lo demostró con rigor, y esa visión sigue siendo la piedra fundacional de toda la física hasta hoy.""",
}

updated = 0
for ch in data['chapters']:
    for m in ch['modules']:
        if m['id'] in fullTexts:
            m['fullText'] = fullTexts[m['id']]
            updated += 1

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"✅ {updated} módulos actualizados correctamente.")
