import json
import math

path = '/Users/yepz/JSweb/data/modules.json'

with open(path, 'r', encoding='utf-8') as f:
    data = json.load(f)

fullTexts = {
    "1.22": """En la **Estación Espacial Internacional (ISS — International Space Station; la estructura habitada más grande jamás construida en el espacio; orbita la Tierra a 408 km de altitud completando 15.5 vueltas por día; pesa 420 toneladas y tiene el volumen interior de una casa de seis habitaciones; fue ensamblada en órbita entre 1998 y 2011 por 15 naciones; ha albergado continuamente a astronautas desde noviembre del año 2000)**, a 408 km sobre la superficie terrestre, los astronautas flotan. Duermen en sacos de dormir sujetos a la pared. Comen alimentos rehidratables con cucharas magnéticas para que los trozos no migren hacia los instrumentos. El agua no cae sino que forma esferas perfectas que ruedan por el aire. Esta experiencia, que llamamos **microgravedad (Microgravity — el estado en que la gravedad percibida es extremadamente pequeña pero no exactamente cero; en la ISS sigue existiendo la gravedad terrestre al 90% de su valor en superficie, pero todos los objetos están en caída libre simultánea, anulando la sensación de peso; el término "micro" refleja perturbaciones residuales de gravedad de entre 10⁻⁶ y 10⁻³ g causadas por el arrastre atmosférico residual, la presión de radiación solar y efectos de marea gravitacional)**, es uno de los entornos más fascinantes y desafiantes que el ser humano ha habitado.

Lo primero que hay que aclarar es el mito más popular de la exploración espacial: los astronautas de la ISS no flotan porque "no hay gravedad en el espacio". La gravedad terrestre a 408 km de altitud sigue siendo aproximadamente el **90%** de la que sentimos en la superficie. Los astronautas flotan porque están en **caída libre constante (Free Fall — el estado en que un objeto cae bajo la única influencia de la gravedad, sin ninguna otra fuerza actuando sobre él; en caída libre, todos los objetos dentro de un mismo sistema caen a la misma tasa independientemente de su masa —principio de equivalencia de Einstein—; esto crea la sensación de ausencia de peso porque no hay superficie que empuje hacia arriba)**.

La ISS orbita la Tierra a 7.66 km/s —cerca de 28,000 km/h—. A esa velocidad, la curvatura de la Tierra se aleja tan rápido como la estación cae hacia ella por la gravedad. El resultado neto es que la estación está cayendo infinitamente sin llegar a impactar, y todos los ocupantes y objetos dentro caen junto con ella a la misma tasa. Esto crea la sensación de flotación: no hay superficie que "empuje" en ninguna dirección. Técnicamente, los astronautas no están "sin gravedad": están en **órbita (Orbit — la trayectoria curva que sigue un objeto alrededor de otro bajo la influencia de la gravedad; es una caída libre continua que "falla" en impactar porque la velocidad horizontal es suficientemente alta para que la superficie del cuerpo central se curve hacia abajo a la misma tasa que el objeto cae; Newton describió la órbita como "disparar una bala de cañón tan rápido que la Tierra se curva bajo ella")**, que es caída libre perpetua.

¿Por qué es tan valiosa la microgravedad como entorno de investigación? Porque elimina la **convección (Convection — el movimiento de un fluido causado por diferencias de densidad creadas por diferencias de temperatura; en la Tierra, los fluidos más calientes y menos densos suben mientras los más fríos y densos bajan; este movimiento mezcla los fluidos constantemente; en microgravedad la convección desaparece porque no hay dirección preferente "arriba/abajo")**, lo que permite crecer **cristales de proteínas (Protein Crystals — ordenamientos tridimensionales periódicos de moléculas de proteína; se usan para determinar la estructura tridimensional exacta de una proteína mediante difracción de rayos X; los cristales crecidos en microgravedad son más grandes, más puros y más ordenados que los terrestres porque la ausencia de convección permite un crecimiento más lento y uniforme; esto ha permitido comprender mejor la estructura de proteínas implicadas en el cáncer y el VIH)** de perfección imposible en la Tierra. También permite estudiar **procesos de combustión (Combustion in Microgravity — las llamas en microgravedad forman esferas perfectas sin la deformación que causa la convección terrestre; esto revela mecanismos de quema más completos y eficientes con menor producción de hollín; los motores diseñados a partir de este conocimiento podrían ser significativamente más eficientes y menos contaminantes)** con llamas esféricas que revelan mecanismos de quema más eficientes.

En total, la ISS ha albergado a más de **270 astronautas** de 20 países y ha realizado más de 3,000 experimentos científicos. Es, sin duda, la obra de ingeniería y cooperación internacional más compleja en la historia de la humanidad, y su contribución a la medicina, la física de materiales y la biología espacial sigue siendo insustituible.

---
**🔖 Bluebook v1 · Capítulo I, Sección 1.5** (Págs. 26–28)
**📐 NGSS: HS-PS2-1 · HS-PS2-4** — Analizar datos sobre la interacción gravitacional en sistemas de referencia en caída libre.
**📋 RENAC / SEP-CONOCER: EC009 · Física Aplicada · Exploración Espacial**
**💡 Standards World:** ISS · Microgravedad · Caída Libre · Órbita · Convección · Biología Espacial · Cristales de Proteína · 7.66 km/s""",

    "1.23": """El cuerpo humano fue diseñado por la evolución para funcionar bajo una fuerza de gravedad específica: **1G (1G — la aceleración gravitacional estándar en la superficie terrestre, equivalente a 9.81 m/s²; es el valor de referencia bajo el que toda la biología de los organismos terrestres evolucionó durante cientos de millones de años; cada sistema del cuerpo humano —esquelético, muscular, cardiovascular, vestibular— fue optimizado para este valor preciso de gravedad)**, la gravedad de la superficie terrestre. Cada sistema de tu cuerpo fue optimizado durante millones de años de evolución para operar en este rango gravitacional preciso. Sacar a un ser humano de este entorno por períodos prolongados tiene consecuencias fisiológicas profundas que la medicina espacial lleva décadas estudiando.

La **pérdida de densidad ósea (Bone Density Loss — la reducción de la masa mineral ósea que ocurre en microgravedad; sin la carga mecánica del peso corporal, los osteoblastos —células constructoras de hueso— reducen su actividad mientras los osteoclastos —células que reabsorben hueso— continúan trabajando; el resultado es una pérdida de entre 1–2% de masa ósea por mes, principalmente en cadera, fémur y columna lumbar; se puede mitigar con ejercicio intensivo pero no eliminar completamente)** es uno de los efectos más severos de la microgravedad. En la Tierra, el esqueleto soporta constantemente el peso del cuerpo, estimulando a los **osteoblastos (Osteoblasts — las células responsables de la formación y mineralización del tejido óseo; sintetizan y secretan la matriz orgánica del hueso —principalmente colágeno— y regulan su mineralización; son activadas mecánicamente por las cargas que soporta el hueso; en microgravedad, sin carga, su actividad disminuye drásticamente)** a depositar nuevo mineral óseo. En microgravedad, sin esa carga, los **osteoclastos (Osteoclasts — las células responsables de la resorción ósea; disuelven la matriz mineral del hueso para liberar calcio al torrente sanguíneo; en microgravedad continúan trabajando aunque los osteoblastos se frenan, lo que produce un balance negativo neto de masa ósea)** continúan trabajando mientras los osteoblastos se desaceleran. Un astronauta que pasa 6 meses en la ISS puede perder tanta masa ósea como una persona con osteoporosis de 10 años.

La atrofia **muscular (Muscle Atrophy — la reducción de la masa y fuerza muscular por falta de uso; los músculos antigravitatorios —glúteos, cuádriceps, pantorrillas, músculos espinales— sufren la mayor pérdida porque en microgravedad no necesitan sostener el peso corporal; después de misiones largas, los astronautas necesitan asistencia para caminar durante las primeras horas tras el retorno)** afecta especialmente a los músculos antigravitatorios que en la Tierra trabajan constantemente para mantenernos erguidos.

En el sistema **cardiovascular (Cardiovascular Adaptation — en microgravedad, el fluido corporal —normalmente jalado hacia abajo por la gravedad— se redistribuye uniformemente hacia el torso y la cabeza; el corazón detecta el exceso aparente de fluido y reduce la producción de plasma sanguíneo; después de pocas semanas hay un 10–15% menos de volumen sanguíneo total; al regresar a la gravedad, este volumen reducido puede causar mareos e hipotensión ortostática —bajada de presión al ponerse de pie—)**, la redistribución de fluidos corporal provoca una sensación constante de "cabeza llena" similar a estar boca abajo durante horas.

Quizás el efecto más alarmante descubierto en la última década es el **VIIP (Visual Impairment Intracranial Pressure Syndrome — síndrome de deterioro visual por presión intracraneal aumentada; el fluido cefalorraquídeo sin gravedad que lo distribuya hacia la médula espinal acumula mayor presión en el cráneo; esta presión aplana el globo ocular y comprime el nervio óptico, produciendo cambios en la visión que en algunos casos son permanentes; cerca del 40% de los astronautas de misiones largas lo experimentan; es actualmente uno de los mayores obstáculos médicos para misiones a Marte)**. Cerca del 40% de los astronautas de misiones largas reportan deterioro visual.

El impacto de la **radiación cósmica (Cosmic Radiation — las partículas de alta energía —principalmente protones y núcleos atómicos— que viajan por el espacio a velocidades relativistas; en la ISS —dentro de la magnetósfera terrestre— la dosis es 10 veces mayor que en la superficie; en viajes a Marte —fuera de la magnetósfera— puede ser 100–1,000 veces mayor sin protección; aumenta el riesgo de cáncer, cataratas y posibles daños al sistema nervioso central)** es otro factor crítico que aumenta el riesgo de cáncer en misiones de larga duración. La fisiología humana en el espacio nos recuerda cuán profundamente somos criaturas de la Tierra, y adaptar nuestra biología para habitar otros mundos es uno de los mayores desafíos de la **bioingeniería (Bioengineering — la aplicación de principios de ingeniería a sistemas biológicos; en el contexto de exploración espacial, incluye el diseño de contramedidas para la pérdida ósea y muscular, escudos de radiación, farmacología de la presión intracraneal y eventualmente la modificación genética para resistir mejor los ambientes extraterrestres)** del siglo XXI.

---
**🔖 Bluebook v1 · Capítulo I, Sección 1.5** (Págs. 27–28)
**📐 NGSS: HS-LS1-3 · HS-LS1-7** — Planificar y llevar a cabo investigaciones sobre cómo los sistemas corporales responden a los cambios ambientales.
**📋 RENAC / SEP-CONOCER: EC009 · Biología Espacial · Medicina de Exploración**
**💡 Standards World:** 1G · Pérdida Ósea · Atrofia Muscular · VIIP · Osteoblastos · Osteoclastos · Radiación Cósmica · Bioingeniería · Microgravedad""",

    "1.24": """Cada vez que un cohete despega de la plataforma de lanzamiento, está librando una batalla contra una de las fuerzas más antiguas e inflexibles del Universo: la gravedad. Para que cualquier objeto llegue al espacio y permanezca fuera, debe superar la cantidad de energía que la gravedad de la Tierra ejerce para retenerlo. Esta cantidad crítica tiene un nombre específico: **velocidad de escape (Escape Velocity — la velocidad mínima que necesita un objeto para escapar permanentemente del campo gravitacional de un cuerpo celeste sin necesitar propulsión adicional; en ese punto, la energía cinética del objeto es exactamente igual a su energía potencial gravitacional negativa; el objeto puede entonces viajar hacia el infinito desacelerándose pero nunca deteniéndose completamente)**.

Para la Tierra, este valor es de **11.2 km/s** (40,320 km/h). La fórmula derivada directamente de las ecuaciones de Newton es:

**v_e = √(2GM/r)**

Donde **G** es la Constante Gravitacional Universal, **M** la masa del cuerpo del que se escapa y **r** la distancia desde su centro. Esta ecuación revela algo fascinante: la velocidad de escape depende de la **densidad** del objeto, no solo de su masa. Una esfera del tamaño del Sol pero comprimida hasta la densidad de un **agujero negro (Black Hole — un objeto cuya velocidad de escape supera c —la velocidad de la luz—; esto ocurre cuando toda la masa de un objeto se concentra dentro de su radio de Schwarzschild; para el Sol, ese radio sería de apenas 3 km; para la Tierra, sería de 9 mm)** tendría una velocidad de escape mayor que la velocidad de la luz: esa es precisamente la definición física de un agujero negro.

En la práctica, los cohetes nunca alcanzan los 11.2 km/s de golpe porque requeriría una cantidad de combustible astronómica. En cambio, usan una combinación de técnicas. La **Ecuación de Tsiolkovsky (Tsiolkovsky Rocket Equation — la ecuación fundamental de la propulsión de cohetes, derivada por el matemático ruso Konstantin Tsiolkovsky en 1903; relaciona el cambio de velocidad de un cohete (Δv) con la velocidad de expulsión del gas propelente y la razón de masa inicial a final; su consecuencia más brutal es que para duplicar el Δv hay que cuadrar la cantidad de combustible —la "tiranía de la ecuación del cohete"—)** describe la relación entre el cambio de velocidad, la velocidad de expulsión de los gases y la razón de masa. Para duplicar el **delta-V (Delta-V / Δv — el cambio de velocidad total disponible para una nave espacial a partir de su propelente; es la moneda de cambio de la mecánica orbital; cada maniobra —salida de órbita, corrección de trayectoria, aterrizaje— consume una porción del Δv disponible; las misiones se diseñan optimizando el uso de este recurso limitado)**, necesitas cuadrar la cantidad de combustible.

Los **cohetes multietapa (Multistage Rockets — cohetes que consisten en varias secciones con sus propios motores y depósitos de combustible que se separan cuando se agotan, reduciendo el peso que las etapas superiores deben acelerar; el Saturn V que llevó a los astronautas a la Luna tenía tres etapas; el principio fue propuesto por Tsiolkovsky en 1903 y es la solución más práctica conocida a la tiranía de la ecuación del cohete)** resuelven parcialmente este problema descartando el peso de los depósitos vacíos durante el ascenso. La **asistencia gravitacional (Gravitational Assist / Slingshot — maniobra orbital en que una nave espacial aprovecha el movimiento de un planeta para aumentar su velocidad sin usar combustible; la nave "roba" una fracción mínima del momento angular del planeta; la Voyager 2 usó cuatro asistencias gravitacionales —Júpiter, Saturno, Urano y Neptuno— para alcanzar velocidades de salida del sistema solar que habrían sido imposibles con solo su propelente)** permite ganar velocidad de forma "gratuita" pasando cerca de planetas.

El **punto de lanzamiento** también importa: lanzar desde el Ecuador —como hacen las plataformas marinas de SpaceX— aprovecha los 465 m/s de velocidad rotacional terrestre en esa latitud como un impulso inicial gratuito. El futuro de la propulsión espacial busca romper las cadenas de la ecuación de Tsiolkovsky con propulsión iónica, **velas de luz (Light Sails — superficies altamente reflectantes que usan la presión de la radiación electromagnética para propulsarse; los fotones no tienen masa en reposo pero sí momento; cuando rebotan en una superficie, transfieren ese momento; la fuerza es minúscula pero en el vacío del espacio, sin resistencia, puede acumular velocidades enormes con el tiempo)**, motores de fusión nuclear y, en el límite teórico, propulsión por antimateria que liberaría 1,000 veces más energía por kilogramo que el mejor combustible químico.

---
**🔖 Bluebook v1 · Capítulo I, Sección 1.5** (Págs. 28–30)
**📐 NGSS: HS-PS2-1 · HS-PS3-1** — Aplicar conceptos de energía cinética y potencial para analizar el movimiento de objetos en campos gravitacionales.
**📋 RENAC / SEP-CONOCER: EC009 · Mecánica Newtoniana · Exploración Espacial**
**💡 Standards World:** Velocidad de Escape · 11.2 km/s · Cohetes · Ecuación de Tsiolkovsky · Multietapas · Asistencia Gravitacional · Delta-V · Velas de Luz""",

    "2.80": """En la búsqueda de temperaturas extremadamente bajas —las más frías alcanzadas en el Universo observable— los científicos han desarrollado una técnica extraordinaria que parece completamente contraintuitiva: usar luz para enfriar materia. Este proceso, llamado **enfriamiento por láser (Laser Cooling — técnica que usa fotones de un rayo láser ajustado a una frecuencia ligeramente menor que la resonancia de los átomos objetivo; los átomos que se mueven hacia el láser absorben los fotones y reciben un "golpe" que reduce su velocidad; aplicando seis rayos desde todas las direcciones simultáneamente, los átomos quedan atrapados en una "melaza óptica" —optical molasses— que los desacelera en todas dimensiones; fue desarrollada entre 1985 y 1990 por Steven Chu, Claude Cohen-Tannoudji y William Phillips, quienes compartieron el Nobel de Física 1997)**, es la base de algunos de los avances más importantes de la física del siglo XXI.

¿Cómo puede la luz, que normalmente calienta las cosas, servir para enfriar? La clave está en el **Efecto Doppler a escala atómica (Atomic Doppler Effect — la misma compresión y estiramiento de frecuencias que ocurre con el sonido de un auto en movimiento, pero aplicado a átomos que se mueven hacia o lejos de un rayo láser; si el láser está ajustado a una frecuencia ligeramente menor que la resonancia del átomo, solo los átomos que se mueven hacia el rayo verán la frecuencia correcta gracias al corrimiento Doppler, y solo ellos absorberán los fotones, recibiendo una deceleración selectiva)**. Al aplicar seis rayos láser desde todas las direcciones, los átomos quedan atrapados en una melaza óptica que los desacelera en todas las dimensiones hasta temperaturas de millonésimas de Kelvin.

Para ir más lejos aún, se combina con el **enfriamiento adiabático magnético (Magnetic Evaporative Cooling — proceso en que una nube de átomos previamente enfriada por láser se atrapa en un campo magnético; al reducir gradualmente la intensidad del campo, los átomos con mayor energía cinética escapan primero, llevándose su energía consigo —como el vapor caliente que escapa de una taza de café—; los restantes tienen menor energía promedio, es decir, menor temperatura; repitiendo el proceso se pueden alcanzar temperaturas de billonésimas de Kelvin, rozando el cero absoluto)**. Los átomos más energéticos escapan llevándose su energía consigo.

Combinando estas técnicas, los físicos logran crear el **Condensado de Bose-Einstein (Bose-Einstein Condensate / BEC — el quinto estado de la materia, predicho matemáticamente por Satyendra Nath Bose y Albert Einstein en 1924–1925; ocurre cuando un gas diluido de átomos bosónicos se enfría tan cerca del cero absoluto que todos los átomos colapsan en el mismo estado cuántico mínimo de energía y se comportan como una sola "superpartícula" cuántica coherente; fue creado experimentalmente por primera vez en 1995 por Eric Cornell, Carl Wieman y Wolfgang Ketterle usando rubidio-87; ganaron el Nobel de Física 2001)**: un estado de la materia donde millones de átomos se comportan como una sola entidad cuántica.

El Magnetic Cooling y el BEC tienen aplicaciones revolucionarias. Son la base de los **relojes atómicos (Atomic Clocks based on BEC — los relojes atómicos más precisos del mundo usan átomos enfriados por láser y campos magnéticos para medir la frecuencia de transición del cesio-133 con una incertidumbre de menos de 10⁻¹⁸ —menos de un segundo de error en 30,000 millones de años—; son los estándares de tiempo que calibran el GPS, las redes de telecomunicaciones y los experimentos de física fundamental)** más precisos del mundo. Son también fundamentales para la investigación en **Computación Cuántica (Quantum Computing — paradigma de computación que usa qubits en superposición cuántica para realizar ciertos tipos de cálculo exponencialmente más rápido que una computadora clásica; los qubits necesitan operar a temperaturas cercanas al cero absoluto para mantener la coherencia cuántica —la superposición— el tiempo suficiente para realizar operaciones; los sistemas de IBM, Google y otros usan enfriamiento a 15 milikelvin, mil veces más frío que el espacio exterior)**, donde los **qubits (Qubits / Quantum Bits — la unidad básica de información cuántica; a diferencia del bit clásico que es 0 o 1, un qubit puede estar en superposición —siendo 0 y 1 simultáneamente— hasta que es medido; el entrelazamiento cuántico permite que operaciones sobre un qubit afecten instantáneamente a otros; son la base del poder de la computación cuántica)** necesitan operar a temperaturas cercanas al cero absoluto para mantener la coherencia cuántica.

Esta tecnología demuestra que los límites de lo posible en física no son los de la intuición cotidiana. Enfriar con luz, atrapar átomos con imanes, hacer que millones de partículas se comporten como una sola: el Universo cuántico es más extraño y más útil de lo que cualquier generación anterior pudo imaginar.

---
**🔖 Bluebook v1 · Capítulo I, Sección 1.7** (Págs. 37–38)
**📐 NGSS: HS-PS2-5 · HS-PS3-4** — Planificar investigaciones para recolectar evidencias sobre campos magnéticos y transferencias de energía en sistemas cuánticos.
**📋 RENAC / SEP-CONOCER: EC009 · Física de Bajas Temperaturas y Tecnología Cuántica**
**💡 Standards World:** Magnetic Cooling · Enfriamiento Láser · Condensado de Bose-Einstein · Cero Absoluto · Efecto Doppler Atómico · Computación Cuántica · Nobel 2001 · Qubits"""
}

updated = 0
total_words = 0

for ch in data['chapters']:
    for m in ch['modules']:
        if m['id'] in fullTexts:
            text = fullTexts[m['id']].strip()
            m['fullText'] = text
            
            # Recalculate duration and update title if needed
            word_count = len(text.split())
            new_duration = math.ceil(word_count / 100) + 5
            m['duration'] = f"{new_duration} min"
            
            # Ensure title starts with ID
            if not m['title'].startswith(m['id']):
                m['title'] = f"{m['id']} {m['title']}"
            
            updated += 1
            print(f"Updated {m['id']}: {word_count} words -> {new_duration} min")

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"✅ {updated} módulos actualizados correctamente.")
