import json
import math

path = '/Users/yepz/JSweb/data/modules.json'

with open(path, 'r', encoding='utf-8') as f:
    data = json.load(f)

fullTexts = {
    "1.33": """Toda la energía que mueve el mundo, desde el calor de tu piel hasta la electricidad de tu ciudad, viene en última instancia de reacciones que ocurren en el corazón de los átomos. Hay dos formas de liberar esta energía nuclear: rompiendo átomos grandes o pegando átomos pequeños. Son los procesos de **Fisión (Nuclear Fission — la ruptura de un núcleo atómico pesado —como el Uranio-235 o el Plutonio-239— en dos núcleos más ligeros al ser golpeado por un neutrón lento; libera energía, calor y 2–3 neutrones adicionales que pueden desencadenar nuevas fisiones; si se controla, genera electricidad en una central nuclear; si no se controla, produce una explosión nuclear)** y **Fusión (Nuclear Fusion — la unión de dos núcleos atómicos ligeros —generalmente isótopos de hidrógeno— para formar un núcleo más pesado; libera enormes cantidades de energía porque el núcleo resultante pesa ligeramente menos que la suma de los originales y esa diferencia de masa se convierte en energía según E=mc²; es el proceso que alimenta a las estrellas y al Sol)**, y entender la diferencia es clave para el futuro energético de la humanidad.

La **Fisión Nuclear** ocurre cuando el núcleo de **Uranio-235 (U-235 — el isótopo fisionable del uranio; representa solo el 0.7% del uranio natural; su núcleo con 92 protones y 143 neutrones es inestable cuando absorbe un neutrón y se divide en fragmentos más ligeros como bario y criptón; el proceso libera una cantidad de energía equivalente a quemar 3 millones de veces el mismo peso en carbón; para usarlo en reactores nucleares, se enriquece hasta el 3–5% de concentración)** es golpeado por un neutrón y se divide en dos núcleos más pequeños. Los neutrones liberados pueden chocar con otros átomos de U-235, creando una **reacción en cadena (Chain Reaction — el proceso en que los neutrones liberados por una fisión disparan nuevas fisiones, que liberan más neutrones, que disparan más fisiones, en una cascada exponencial; en un reactor nuclear, las barras de control absorben el exceso de neutrones para mantener la reacción estable; en una bomba nuclear, no hay control y la cadena se vuelve explosiva en microsegundos)**. Si se controla con **barras de control (Control Rods — varillas de materiales que absorben neutrones eficientemente —cadmio, boro o hafnio— que se insertan o retiran del núcleo del reactor para regular la velocidad de la reacción en cadena; insertar las barras más profundamente atrapa más neutrones y desacelera la reacción; retirarlas la acelera; son el principal mecanismo de seguridad de todos los reactores de fisión)**, la energía se extrae como calor para generar electricidad. El gran desafío son los **residuos radiactivos (Nuclear Waste — los productos de fisión radiactivos que permanecen peligrosos durante miles de años; el plutonio-239, por ejemplo, tiene una vida media de 24,100 años; su almacenamiento seguro a largo plazo es uno de los mayores desafíos éticos e ingenieriles de la civilización nuclear)** de larga vida.

La **Fusión Nuclear** es el proceso opuesto y el que alimenta al Sol. Dos núcleos ligeros de hidrógeno se unen para formar **Helio (Helium — el segundo elemento de la tabla periódica con 2 protones; se produce por fusión nuclear en el núcleo del Sol y en la fusión nuclear controlada en reactores; el isótopo Helio-4 es el producto de la reacción D-T —deuterio más tritio— que se persigue en ITER)**. La fusión libera más energía que la fisión y no produce residuos radiactivos de larga vida. El combustible —isótopos de hidrógeno como el **deuterio (Deuterium — isótopo del hidrógeno con un protón y un neutrón en su núcleo; es el doble de pesado que el hidrógeno ordinario; representa 1 de cada 6,400 moléculas de agua oceánica; es uno de los combustibles para la fusión nuclear; prácticamente inagotable porque se puede extraer del agua de mar)**— se puede extraer del agua de los océanos.

El principal obstáculo es que la fusión requiere temperaturas de **100 millones de grados Celsius (100 Million Degrees — la temperatura mínima necesaria para que los núcleos de deuterio y tritio se acerquen lo suficiente para que la fuerza nuclear fuerte supere la repulsión electromagnética entre sus cargas positivas y se fusionen; es 6 veces más caliente que el centro del Sol; a esa temperatura la materia existe como plasma y debe confinarse mediante campos magnéticos porque ningún material sólido puede contenería)**, mucho más que el centro del Sol. A esa temperatura, la materia existe como **plasma (Plasma — el cuarto estado de la materia, formado cuando un gas se calienta tanto que los electrones se separan de los átomos, creando una mezcla de iones positivos y electrones libres; es el estado más común de la materia visible en el Universo —el Sol, las estrellas y los rayos son plasma—; es conductor de la electricidad y responde a los campos magnéticos, lo que permite confinarlo en reactores de fusión)** que debe confinarse magnéticamente en máquinas llamadas **Tokamaks (Tokamak — cámara toroidal —en forma de rosquilla— que usa campos magnéticos superconductores extremadamente poderosos para confinar el plasma de fusión a lo largo de trayectorias circulares sin que toque las paredes; el diseño fue concebido por físicos soviéticos Tamm e Sajarov en la década de 1950; es la arquitectura dominante en todos los grandes proyectos de fusión actuales incluyendo ITER)**. El proyecto **ITER (International Thermonuclear Experimental Reactor — el mayor experimento científico de la historia; se construye en Cadarache, Francia; involucra a 35 países incluyendo la UE, EEUU, China, India, Japón, Corea y Rusia; su objetivo es demostrar que la fusión puede producir 10 veces más energía de la que consume para calentar el plasma —Q≥10—; no generará electricidad pero sentará las bases para DEMO, el primer reactor de fusión comercial)** es el mayor experimento científico de la historia, diseñado para demostrar que podemos obtener más energía de la fusión de la que consumimos en calentar el plasma.

Tanto la fisión como la fusión demuestran la famosa ecuación de Einstein, **E=mc² (E=mc² — la equivalencia masa-energía descubierta por Einstein in 1905; establece que la energía E contenida en una masa m es igual a esa masa multiplicada por el cuadrado de la velocidad de la luz c; como c² es un número enorme —9 × 10¹⁶—, incluso una masa minúscula contiene una cantidad colosal de energía; explica por qué las reacciones nucleares liberan millones de veces más energía que las reacciones químicas)**: una minúscula diferencia de masa se convierte en energía colosal. Somos seres hechos de átomos que han aprendido a liberar la energía que los mantiene unidos.

---
**🔖 Bluebook v1 · Capítulo II, Sección 2.1 — Física Nuclear** (Págs. 42–45)
**📐 NGSS: HS-PS1-8** — Desarrollar modelos para ilustrar los cambios en la composición del núcleo del átomo y la energía liberada.
**📋 RENAC / SEP-CONOCER: ET005 · Energía Nuclear y Tecnologías de Generación**
**💡 Standards World:** Fisión · Fusión · Uranio-235 · Hidrógeno · ITER · Tokamak · Reacción en Cadena · E=mc²""",

    "1.34": """En el interior de las estrellas más masivas que nuestro Sol, ocurre una danza química invisible responsable de la mayor parte del nitrógeno y el oxígeno que hoy respiras. Se llama el **Ciclo C-N-O (CNO Cycle — Carbon-Nitrogen-Oxygen Cycle; uno de los dos mecanismos principales de fusión nuclear en las estrellas; predomina en estrellas con más de 1.3 veces la masa solar donde la temperatura del núcleo supera los 15–17 millones de Kelvin; produce el mismo resultado neto que la cadena protón-protón —4 protones → 1 helio-4 + energía— pero mucho más eficientemente usando el carbono como catalizador)**, y es uno de los métodos más eficientes que tiene la naturaleza para convertir hidrógeno en helio y liberar energía estelar.

Mientras que las estrellas pequeñas como el Sol usan mayormente la **cadena protón-protón (Proton-Proton Chain — el principal mecanismo de fusión del Sol y las estrellas de masa similar; fusiona directamente cuatro protones en un núcleo de helio-4 mediante una serie de pasos que incluyen la conversión de protones en neutrones por la fuerza nuclear débil; es extremadamente lento —en el Sol, cada protón tarda en promedio 9,000 millones de años en participar en la reacción— porque la probabilidad de la conversión protón-neutrón es muy baja)**, las estrellas con más de 1.3 veces la masa solar recurren al ciclo C-N-O. En este proceso, el **Carbono-12 (Carbon-12 / C-12 — el isótopo estable más abundante del carbono con 6 protones y 6 neutrones; en el ciclo CNO actúa como catalizador absorbiendo y devolviendo protones en ciclos repetidos; al finalizar cada ciclo completo, el C-12 original es recuperado intacto mientras que 4 protones se han convertido en un núcleo de helio-4)** actúa como un **catalizador (Catalyst — una sustancia que acelera una reacción química participando en ella pero sin ser consumida ni transformada permanentemente; al final de la reacción, el catalizador emerge idéntico a como entró y puede iniciar otro ciclo inmediatamente; en el ciclo CNO, el carbono cataliza la fusión del hidrógeno sin ser destruido)**: entra al ciclo, ayuda a fusionar hidrógeno, y sale intacto al final para reiniciar el proceso.

El ciclo funciona así: el C-12 captura un protón para convertirse en Nitrógeno-13, que decae a Carbono-13, que captura otro protón para volver a ser Nitrógeno-14, que captura otro para ser Oxígeno-15, y finalmente, tras una última colisión, libera un núcleo de Helio y vuelve a ser el C-12 original. El resultado neto es que **4 núcleos de Hidrógeno se fusionan en 1 de Helio**, liberando fotones y **neutrinos (Neutrinos from CNO — las partículas subatómicas casi sin masa que se generan durante los procesos de desintegración beta del ciclo CNO; escapan inmediatamente del núcleo estelar a velocidades cercanas a c y pueden ser detectados en la Tierra; el detector Borexino en Italia detectó en 2020 por primera vez los neutrinos específicos del ciclo CNO del Sol, confirmando directamente que el ciclo opera en nuestro astro)**.

Este ciclo es extremadamente sensible a la **temperatura (Temperature Sensitivity of CNO — la tasa de reacción del ciclo CNO es proporcional a T²⁰ —temperatura elevada a la vigésima potencia—; esto significa que un pequeño aumento de temperatura produce un aumento gigantesco en la producción de energía; es por eso que las estrellas masivas, con núcleos más calientes, son exponencialmente más luminosas que el Sol y queman su combustible en millones en lugar de miles de millones de años)**. En estrellas supermásivas, donde las temperaturas centrales son aún más altas, el ciclo C-N-O ocurre a una velocidad frenética, haciendo que estas estrellas brillen con una intensidad cegadora y consuman su combustible en apenas unos millones de años.

La importancia del ciclo C-N-O para la vida es directa. Durante estas reacciones, pequeñas cantidades de nitrógeno y oxígeno se acumulan en la estrella. Cuando estas estrellas masivas explotan como **Supernovas (Supernovas — explosiones estelares catastróficas al final de la vida de una estrella masiva; dispersan al espacio interestelar los elementos fabricados en el interior de la estrella durante su vida —incluyendo el nitrógeno y el oxígeno del ciclo CNO— enriqueciendo el medio interestelar con los ingredientes necesarios para que nazcan nuevas estrellas con sistemas planetarios capaces de albergar vida)**, ese nitrógeno y oxígeno se dispersan al espacio interestelar. Esa es la fuente del aire que respiras y del nitrógeno en tu ADN. Tu capacidad de pensar y respirar depende de reacciones nucleares que ocurrieron en el corazón de estrellas masivas hace eones. La **nucleosíntesis estelar (Stellar Nucleosynthesis — la fabricación de elementos químicos más pesados que el hidrógeno y el helio en el interior de las estrellas mediante fusión nuclear; incluyendo el ciclo CNO, la fusión triple alfa, la captura de neutrones y los procesos r y s; prácticamente todos los átomos de tu cuerpo —excepto el hidrógeno y parte del helio— fueron fabricados en el interior de alguna estrella que explotó antes de que naciera el Sol)** es literalmente la historia de tus átomos.

---
**🔖 Bluebook v1 · Capítulo I, Sección 1.1** (Págs. 13–15)
**📐 NGSS: HS-PS1-8 · HS-ESS1-3** — Comunicar información científica sobre cómo las estrellas producen elementos mediante la fusión.
**📋 RENAC / SEP-CONOCER: EC009 · Astrofísica Estelar**
**💡 Standards World:** Ciclo C-N-O · Catalizador · Fusión Nuclear · Carbono-12 · Helio · Supernova · Neutrinos · Nucleosíntesis · Cadena Protón-Protón""",

    "1.35": """A todas las estrellas les llega el momento de morir, y el Sol no es la excepción. Dentro de unos 5,000 millones de años, el Sol agotará el hidrógeno en su núcleo y comenzará una transformación dramática que lo convertirá en una **Gigante Roja (Red Giant — la fase evolutiva de una estrella de masa baja o media —entre 0.3 y 8 masas solares— cuando agota el hidrógeno en su núcleo; el núcleo de helio resultante se contrae bajo la gravedad mientras la fusión de hidrógeno continúa en una capa exterior; el calor extra generado hace que las capas exteriores de la estrella se expandan enormemente, hasta cientos de veces el diámetro original, mientras la temperatura superficial desciende dando un color rojizo)**. Es el destino de la mayoría de las estrellas de masa media del Universo.

¿Por qué una estrella se vuelve gigante al morir? Cuando el hidrógeno en el núcleo se agota, el núcleo —hecho ahora principalmente de helio— pierde la presión de radiación hacia afuera que proporcionaba la fusión. La gravedad, que nunca descansa, comienza a comprimir el núcleo. Esta compresión genera un calor tan intenso que comienza a fusionar el hidrógeno que rodea el núcleo en una capa exterior. Este calor adicional hace que las capas externas de la estrella se expanden enormemente: el Sol crecerá hasta engullir probablemente a Mercurio y Venus, y la Tierra quedará calcinada a temperatura de cientos de grados aunque no sea directamente engullida.

En esta fase ocurre el **"Flash del Helio" (Helium Flash — el inicio repentino y violento de la fusión de helio en el núcleo de una estrella gigante roja de masa baja; ocurre cuando el núcleo alcanza los 100 millones de Kelvin; a diferencia del hidrógeno, el helio en el núcleo está en un estado degenerado —donde la presión no depende de la temperatura— y cuando comienza a fusionarse, el calor liberado no expande el núcleo para regular la reacción, sino que aumenta la tasa de fusión en una cascada que libera en unos pocos segundos tanta energía como el Sol en 100 millones de años; este evento no es directamente observable desde el exterior porque la energía es absorbida por las capas externas)**: el núcleo se calienta tanto que el helio comienza a fusionarse en carbono y oxígeno mediante el **proceso triple alfa (Triple Alpha Process — la reacción nuclear que fusiona tres núcleos de helio-4 para formar un núcleo de carbono-12; requiere temperaturas de al menos 100 millones de Kelvin; primero dos helio-4 se fusionan en el núcleo inestable de berilio-8, y antes de que se desintegre —en 10⁻¹⁶ segundos— absorbe un tercer helio-4 para formar carbono-12; fue el proceso que permitió que el Universo fabricara carbono, el elemento base de la vida)**. La estrella vive una segunda fase activa breve y turbulenta.

Cuando el helio también se agota, para una estrella como el Sol no hay masa suficiente para fusionar el carbono. Las capas externas, ya muy débiles, se desprenden suavemente formando una **Nebulosa Planetaria (Planetary Nebula — una cáscara brillante de gas y polvo expulsada por una estrella durante su transición de gigante roja a enana blanca; el nombre es histórico y engañoso —no tiene nada que ver con los planetas—; brilla porque la radiación ultravioleta de la enana blanca central ioniza el gas expulsado; dura entre 10,000 y 30,000 años antes de dispersarse en el medio interestelar; son uno de los espectáculos más coloridos del cosmos y fuentes importantes de elementos para futuras generaciones estelares)**. El material expulsado —enriquecido con carbono, oxígeno y otros elementos fabricados durante la vida estelar— fertiliza el espacio interestelar.

Lo que queda en el centro es el cadáver estelar: una **Enana Blanca (White Dwarf — el núcleo comprimido que queda tras la muerte de una estrella de masa baja o media; tiene el tamaño aproximado de la Tierra pero la masa del Sol; su densidad es tan alta que una cucharadita pesaría toneladas; no tiene fusión nuclear activa y brilla solo con el calor residual; tardará cientos de miles de millones de años en enfriarse hasta convertirse en una fría e invisible enana negra; está sostenida contra el colapso gravitacional por la presión de degeneración electrónica —un efecto mecánico-cuántico que impide que dos electrones ocupen el mismo estado cuántico)**. Las Gigantes Rojas son las grandes recicladoras del Universo: al morir siembran el cosmos con los ingredientes químicos necesarios para que nazcan nuevas estrellas con planetas y, quizás, nueva vida.

---
**🔖 Bluebook v1 · Capítulo I, Sección 1.1** (Págs. 14–15)
**📐 NGSS: HS-ESS1-1 · HS-ESS1-3** — Usar el modelo del ciclo de vida de las estrellas para predecir su evolución y la producción de elementos.
**📋 RENAC / SEP-CONOCER: EC009 · Evolución Estelar**
**💡 Standards World:** Gigante Roja · Enana Blanca · Nebulosa Planetaria · Flash del Helio · Proceso Triple Alfa · Ciclo de Vida Estelar · Luminosidad · Nucleosíntesis""",

    "1.36": """Cuando una estrella masiva —una que tiene al menos ocho veces la masa de nuestro Sol— llega al final de su vida, no se apaga suavemente. En su lugar, protagoniza el evento más violento y energético del Universo: una **Supernova (Supernova — explosión estelar catastrófica que ocurre al final de la vida de una estrella masiva o en ciertos sistemas de estrellas binarias; durante unos días puede brillar con la intensidad de toda una galaxia de 100,000 millones de estrellas; en ese breve período libera más energía de la que el Sol emitirá en toda su vida de 10,000 millones de años; dispersa al espacio interestelar los elementos fabricados en el interior de la estrella, enriqueciendo el medio con los ingredientes para futuras generaciones estelares y planetarias)**. Durante unos pocos días, una sola estrella puede brillar con la intensidad de toda una galaxia de 100,000 millones de soles.

Existen dos tipos principales. La **Supernova Tipo Ia (Type Ia Supernova — explosión termonuclear que ocurre cuando una enana blanca en un sistema binario acumula materia de su estrella compañera hasta superar el Límite de Chandrasekhar —1.44 masas solares—; en ese punto, la presión de degeneración electrónica no puede sostener más masa y se desencadena una explosión termonuclear que destruye completamente la enana blanca; siempre produce la misma luminosidad máxima, lo que las convierte en "velas estándar" para medir distancias cósmicas)** ocurre en sistemas binarios cuando una **enana blanca (White Dwarf — ver módulo 1.35)** acumula materia de su estrella compañera hasta superar el **Límite de Chandrasekhar (Chandrasekhar Limit — la masa máxima que puede tener una enana blanca sin colapsar; equivale a 1.44 veces la masa del Sol; fue calculado por el astrofísico indio Subrahmanyan Chandrasekhar en 1930 mientras viajaba en barco desde la India a Cambridge; le valió el Premio Nobel de Física en 1983; por encima de este límite, la presión de degeneración electrónica no puede contrarrestar la gravedad y la enana blanca colapsa o explota)**. La Supernova **Tipo II (Type II / Core Collapse Supernova — explosión que ocurre cuando el núcleo de hierro de una estrella masiva —más de 8 masas solares— colapsa gravitacionalmente al no poder fusionar más hierro; el núcleo se comprime en una estrella de neutrones o agujero negro en milisegundos; la onda de choque rebota y desintegra las capas externas de la estrella; libera el 99% de su energía como neutrinos)** ocurre cuando el núcleo de hierro de una estrella masiva colapsa.

En la explosión, las temperaturas y presiones son tan extremas que se fusionan elementos más pesados que el hierro, como el **Oro (Gold — el elemento 79 de la tabla periódica; no puede fabricarse en el interior de las estrellas mediante fusión ordinaria porque requiere más energía de la que libera; se forma en explosiones de supernovas tipo II y en colisiones de estrellas de neutrones —kilonovas— mediante el proceso r de captura rápida de neutrones; todo el oro en las joyas de la Tierra fue forjado en eventos cósmicos catastróficos hace miles de millones de años)**, el **Platino (Platinum — el elemento 78; como el oro, se forma principalmente en kilonovas —colisiones de estrellas de neutrones—; la misión de LIGO que detectó la primera kilonova en 2017 confirmó que estos eventos son la fuente principal de los elementos más pesados del Universo)** y el **Uranio (Uranium — el elemento más pesado encontrado en abundancia significativa en la naturaleza; se forma en supernovas y kilonovas mediante el proceso r; su presencia en la corteza terrestre es evidencia de que el material del que está hecha la Tierra fue procesado en eventos cósmicos violentos anteriores a la formación del sistema solar)**. Sin supernovas, el Universo sería un lugar estéril de hidrógeno y helio.

En 1998, al observar supernovas Tipo Ia lejanas como velas estándar, los científicos descubrieron que el Universo no solo se expande sino que se **acelera (Accelerating Expansion — el descubrimiento de 1998 por Saul Perlmutter, Brian Schmidt y Adam Riess de que las supernovas Tipo Ia lejanas son más tenues de lo esperado, indicando que están más lejos de lo que un Universo en expansión decelerada produciría; esto implica que algo está acelerando la expansión —la energía oscura—; el descubrimiento ganó el Premio Nobel de Física 2011)**. Este hallazgo llevó a postular la **energía oscura**, el mayor misterio de la cosmología. Las supernovas no solo fabricaron tus átomos: también descubrieron que el Universo tiene un destino que nadie esperaba.

---
**🔖 Bluebook v1 · Capítulo I, Sección 1.1** (Págs. 14–16)
**📐 NGSS: HS-ESS1-3** — Comunicar información sobre cómo las estrellas producen elementos mediante la fusión y explosiones finales.
**📋 RENAC / SEP-CONOCER: EC009 · Astrofísica de Alta Energía**
**💡 Standards World:** Supernova · Tipo Ia · Tipo II · Nucleosíntesis · Límite de Chandrasekhar · Energía Oscura · Alquimia Cósmica · Velas Estándar""",

    "1.37": """En el corazón de una estrella masiva, la fusión nuclear es una lucha constante contra la gravedad. Durante millones de años, la estrella fusiona hidrógeno en helio, helio en carbono, carbono en oxígeno, y así sucesivamente, creando capas concéntricas de elementos cada vez más pesados en lo que los astrofísicos llaman la **estructura de cebolla estelar (Onion Layer Structure — la organización interna de una estrella masiva madura en capas concéntricas de elementos de diferente peso atómico; desde afuera hacia adentro: hidrógeno, helio, carbono, neón, oxígeno, silicio y en el centro —el núcleo más caliente— hierro; cada capa funde el elemento de la capa superior y produce el de la siguiente)**. Pero esta escalera energética tiene un escalón final infranqueable: el **Hierro (Iron / Fe — el elemento 26 de la tabla periódica; tiene el núcleo atómico más estable de la naturaleza —mayor energía de enlace por nucleón que cualquier otro elemento—; esto significa que ni la fisión ni la fusión del hierro liberan energía; por el contrario, ambas la consumen; es el "cementerio termodinámico" de la fusión estelar: una vez formado en el núcleo de una estrella masiva, no hay más combustible nuclear posible)**.

Hasta llegar al silicio, cada reacción de fusión libera energía —es una reacción **exotérmica (Exothermic Reaction — reacción que libera energía al sistema circundante; en el contexto de la fusión estelar, significa que el producto de la fusión pesa ligeramente menos que los reactivos —defecto de masa— y esa diferencia se convierte en energía según E=mc²; todas las reacciones de fusión hasta el hierro son exotérmicas, por eso sostienen a la estrella contra la gravedad)**—. Esa energía crea la presión de radiación que sostiene a la estrella contra su propio peso. Pero fusionar hierro no libera energía: la **consume** —es una reacción **endotérmica (Endothermic Reaction — reacción que absorbe energía del sistema circundante; en el contexto de la fusión del hierro, significa que para unir dos núcleos de hierro se necesita aportar energía en lugar de recibirla; cuando el núcleo de una estrella masiva empieza a acumular hierro, cada intento de fusión extrae energía de la estrella en lugar de generarla, acelerando el colapso gravitacional)** —. Cuando la estrella intenta fusionar hierro, el motor nuclear que la mantenía viva se detiene. La presión de radiación hacia afuera desaparece en una fracción de segundo.

En milisegundos, la gravedad gana la batalla. Las capas externas de la estrella, con la masa de varios soles, caen hacia el centro a una velocidad del **25% de la velocidad de la luz (0.25c Free-Fall Velocity — la velocidad que alcanzan las capas externas de una estrella masiva al caer hacia el núcleo colapsante en la fracción de segundo antes de la explosión de supernova; corresponde a aproximadamente 75,000 km/s; cuando este material choca contra el núcleo ultra-denso de neutrones recién formado, la onda de choque resultante viaja hacia afuera a 50,000 km/s desintegrando el resto de la estrella)**. Cuando choca contra el **núcleo de neutrones (Neutron Core — el objeto ultra-denso que se forma en milisegundos durante el colapso del núcleo de hierro; en ese instante, la presión es tan extrema que los electrones son forzados dentro de los protones formando neutrones, liberando una avalancha de neutrinos; si la masa del núcleo está entre 1.4 y 3 masas solares, queda como una estrella de neutrones; si es mayor, el colapso continúa formando un agujero negro)** recién formado, rebota con una fuerza titánica, creando la onda de choque de una supernova.

El hierro que corre por tu sangre transportando oxígeno en la **hemoglobina (Hemoglobin — la proteína del glóbulo rojo que transporta el oxígeno desde los pulmones a los tejidos y el CO₂ de regreso; cada molécula contiene 4 grupos hemo, cada uno con un átomo de hierro central que puede unirse reversiblemente a una molécula de oxígeno; la capacidad de oxígeno de la sangre depende directamente del hierro disponible; una deficiencia produce anemia)** fue el mismo elemento que detuvo el motor de una estrella masiva hace eones. Somos seres que dependen vitalmente del residuo nuclear más estable del Universo. El Fe-56 es el valle energético más profundo de la tabla periódica: el punto de equilibrio máximo de la materia, al que todo el Universo nuclear tiende a caer.

---
**🔖 Bluebook v1 · Capítulo I, Sección 1.1** (Págs. 15–16)
**📐 NGSS: HS-PS1-8 · HS-ESS1-1** — Desarrollar modelos sobre la liberación de energía y la estabilidad del núcleo atómico.
**📋 RENAC / SEP-CONOCER: EC009 · Física Nuclear Estelar**
**💡 Standards World:** Hierro · Nucleosíntesis · Estabilidad Atómica · Estructura de Cebolla · Reacción Endotérmica · Colapso de Núcleo · Hemoglobina · Valle Energético""",

    "1.38": """Si comprimieras toda la masa del Sol en una esfera que cupiera dentro de una ciudad pequeña, tendrías una **Estrella de Neutrones (Neutron Star — el objeto más denso que conocemos con superficie sólida; se forma cuando el núcleo de una estrella masiva colapsa tras una supernova tipo II; tiene entre 1.4 y 3 masas solares comprimidas en una esfera de apenas 20 km de diámetro; su densidad es tan extrema que una cucharadita de su material pesaría en la Tierra entre 10 y 100 millones de toneladas; es comparable a comprimir a toda la humanidad en un solo cubo de azúcar)**. Una sola cucharadita de su material pesaría mil millones de toneladas en la Tierra.

Estas estrellas nacen del colapso de supernovas tipo II. Durante el colapso, la presión es tan extrema que los **electrones son empujados dentro de los protones (Neutronization — el proceso durante el colapso del núcleo estelar en que la presión extrema supera la barrera energética que normalmente separa los protones y electrones; los protones y los electrones se combinan para formar neutrones y neutrinos mediante la reacción p + e⁻ → n + νₑ; este proceso libera una descarga de neutrinos de energía inmensa que es responsable del 99% de la energía total de la supernova)**, convirtiéndolos en neutrones y emitiendo una avalancha de neutrinos. Lo que queda es una bola de neutrones puros de 20 km, mantenida por la **Presión de Degeneración de Neutrones (Neutron Degeneracy Pressure — la fuerza cuántica que resiste el colapso de una estrella de neutrones; es el resultado del Principio de Exclusión de Pauli aplicado a los neutrones: dos neutrones no pueden ocupar el mismo estado cuántico simultáneamente; esta restricción cuántica genera una presión que resiste la gravedad; si la masa supera ~3 masas solares, ni esta presión es suficiente y la estrella colapsa en un agujero negro)**.

La gravedad en la superficie de una estrella de neutrones es dos mil millones de veces más fuerte que en la Tierra. El campo magnético de estos objetos es trillones de veces más potente que el terrestre, capaz de distorsionar los átomos en formas de agujas alargadas. Debajo de su delgada corteza de hierro cristalizado, la materia entra en un estado exótico llamado **Pasta Nuclear (Nuclear Pasta — el estado exótico de la materia en las capas internas de una estrella de neutrones, donde la competencia entre la fuerza nuclear fuerte y la repulsión eléctrica organizan los neutrones y protones en estructuras que se asemejan geométricamente a lasaña, espagueti, macarrones o suizo —según la profundidad—; es el material más resistente conocido, unas diez mil millones de veces más resistente que el acero; su estudio ayuda a entender los límites de la materia densa)**.

En 2017, la humanidad presenció la primera **kilonova (Kilonova — la explosión que resulta de la fusión de dos estrellas de neutrones en un sistema binario; libera energía equivalente a 1,000 supernovas ordinarias —de ahí el nombre—; es el principal proceso de formación de elementos más pesados que el hierro —oro, platino, uranio— mediante el proceso r de captura rápida de neutrones; el evento GW170817 fue detectado simultáneamente por LIGO —ondas gravitacionales— y múltiples telescopios —luz— en lo que se llamó "astronomía multimensajero")** detectada simultáneamente por ondas gravitacionales y luz visible, confirmando que las fusiones de estrellas de neutrones son la fuente principal del oro y el platino del Universo. Fue la primera vez que la humanidad escuchó y vio un evento cósmico al mismo tiempo, inaugurando la era de la **astronomía multimensajero (Multi-Messenger Astronomy — el campo emergente que combina observaciones simultáneas en distintos "canales" —ondas gravitacionales, neutrinos, fotones de todo el espectro electromagnético— para estudiar eventos cósmicos; cada mensajero revela una dimensión diferente del mismo fenómeno; GW170817 en 2017 fue el primer evento estudiado con ondas gravitacionales + luz + neutrinos simultáneamente)**.

---
**🔖 Bluebook v1 · Capítulo I, Sección 1.1** (Pág. 16)
**📐 NGSS: HS-PS2-4 · HS-ESS1-1** — Analizar fuerzas gravitatorias y campos magnéticos extremos en objetos compactos.
**📋 RENAC / SEP-CONOCER: EC009 · Física de la Materia Condensada**
**💡 Standards World:** Estrella de Neutrones · Densidad Extrema · Pasta Nuclear · Presión de Degeneración · Kilonova · Ondas Gravitacionales · Astronomía Multimensajero""",

    "1.39": """Cuando una estrella de neutrones gira a velocidades increíbles —algunas lo hacen cientos de veces por segundo— actúa como un faro cósmico. Estos objetos se llaman **Púlsares (Pulsars — estrellas de neutrones en rotación rápida que emiten haces de radiación electromagnética desde sus polos magnéticos; si el eje de rotación y el eje magnético están ligeramente desalineados, el haz barre el espacio como un faro; si la Tierra queda en el camino del haz, detectamos pulsos de radio u otras radiaciones con una regularidad comparable a la de los mejores relojes atómicos; su nombre proviene de "pulsating radio sources")**.

El descubrimiento de los púlsares en 1967 por **Jocelyn Bell Burnell (Jocelyn Bell Burnell — astrofísica irlandesa que como estudiante de doctorado en Cambridge detectó la primera señal de un púlsar en julio de 1967 al analizar tiras de papel de un radiotelescopio; la señal era tan regular —un pulso exacto cada 1.337 segundos— que inicialmente se llamó "LGM-1" —Little Green Men—; el Nobel de Física 1974 fue otorgado a su supervisor Antony Hewish y a Martin Ryle por el descubrimiento, en una controversia histórica por no incluir a Bell Burnell)** fue tan extraño que inicialmente se pensó en señales extraterrestres. Sin embargo, la física explicó la precisión de los pulsos por la conservación del **Momento Angular (Conservation of Angular Momentum — el principio físico por el que un objeto que rota conserva su momento angular total en ausencia de fuerzas externas; cuando una estrella colapsa reduciendo su radio miles de veces, su velocidad de rotación aumenta drásticamente —como una patinadora que recoge los brazos—; una estrella que rotaba una vez por semana puede convertirse en una estrella de neutrones que rota cientos de veces por segundo)**. Como una patinadora que retrae los brazos, la estrella colapsa y gira cada vez más rápido.

Los púlsares son los cronómetros más exactos del Universo. Las sondas **Voyager** llevaron grabado en su placa de aluminio un mapa de **14 púlsares (Pulsar Map on Voyager — el mapa diseñado por Carl Sagan y Frank Drake incluido en las placas doradas de las sondas Voyager y Pioneer; muestra las posiciones relativas de 14 púlsares conocidos respecto al Sol con sus períodos de pulso codificados; cualquier civilización que encuentre la sonda y comprenda física de pulsares podría calcular de dónde vino y cuándo fue lanzada; es la "dirección de retorno" de la humanidad en el cosmos)** para indicar la posición exacta de la Tierra a cualquier civilización que los encuentre.

Los **Magnetares (Magnetars — el tipo de estrella de neutrones con los campos magnéticos más intensos del Universo observable, entre 10¹⁴ y 10¹⁵ Gauss —cuadrillones de veces más fuertes que el campo magnético terrestre—; se forman en supernovas tipo II bajo condiciones de rotación extrema; liberan ocasionalmente explosiones de rayos X y gamma enormes llamadas "giant flares"; un magnetar a la distancia de la Luna podría borrar la información de todas las tarjetas de crédito de la Tierra y alterar la química de las moléculas de tu cuerpo)** son una subclase especial con los campos magnéticos más poderosos del Universo. Un magnetar a mitad de camino a la Luna podría borrar las tarjetas de crédito de toda la Tierra. Afortunadamente, el más cercano conocido está a miles de años luz.

Para los científicos, los púlsares son herramientas de precisión para poner a prueba la **Relatividad General (Tests of General Relativity with Pulsars — el sistema de dos púlsares orbitándose mutuamente —"double pulsar" PSR J0737-3039— ha permitido verificar las predicciones de la relatividad general con una precisión de hasta el 0.05%; incluyen la precesión del periapsis, la dilatación temporal gravitacional, el retraso de Shapiro y la disminución de la órbita por emisión de ondas gravitacionales; son las pruebas más precisas de la relatividad general disponibles actualmente)** de Einstein con una precisión sin precedentes. Son los relojes más precisos del cosmos, los faros más confiables del espacio profundo, y la evidencia más directa de que los cadáveres de las estrellas pueden ser tan interesantes como las propias estrellas vivas.

---
**🔖 Bluebook v1 · Capítulo I, Sección 1.1** (Pág. 16)
**📐 NGSS: HS-PS4-5 · HS-ESS1-4** — Evaluar la validez de modelos del movimiento de objetos en sistemas estelares.
**📋 RENAC / SEP-CONOCER: ET002 · Astronomía Observacional y Telecomunicaciones**
**💡 Standards World:** Púlsar · Radiación Electromagnética · Momento Angular · Magnetar · Reloj Atómico · GPS Galáctico · Jocelyn Bell Burnell · Relatividad General""",

    "1.40": """Imagina un lugar donde la gravedad es tan fuerte que ni siquiera la luz —lo más rápido que existe— puede escapar. Un lugar donde las leyes conocidas de la física se rompen y el tiempo mismo parece detenerse. Bienvenido al **Agujero Negro (Black Hole — una región del espacio-tiempo donde la curvatura gravitacional es tan extrema que nada, ni siquiera la luz, puede escapar una vez que cruza el horizonte de eventos; no son "agujeros" en el espacio sino objetos con masa concentrada a tal densidad que su velocidad de escape supera la velocidad de la luz; se forman cuando el núcleo de una estrella masiva —o una agrupación de masa suficiente— colapsa más allá del límite de la presión de degeneración de neutrones)**.

Un agujero negro nace cuando el núcleo de una estrella más masiva que aproximadamente 20 masas solares colapsa completamente. Sin ninguna fuerza capaz de detener la gravedad, la materia se comprime infinitamente en un punto de volumen cero y densidad infinita llamado **Singularidad (Singularity — el punto en el centro de un agujero negro donde, según las ecuaciones de la relatividad general, la densidad y la curvatura del espacio-tiempo se vuelven infinitas y las leyes de la física dejan de funcionar tal como las conocemos; se cree que una teoría de gravedad cuántica —que todavía no existe— describirá correctamente lo que ocurre en la singularidad; es uno de los grandes pendientes de la física teórica)**. Alrededor de este punto existe el **Horizonte de Eventos (Event Horizon — la superficie esférica imaginaria alrededor de un agujero negro que marca el punto de no retorno; su radio se llama radio de Schwarzschild, calculado por Karl Schwarzschild en 1916 pocos meses después de que Einstein publicara la relatividad general; para el Sol, sería de 3 km; para la Tierra, de 9 mm; una vez cruzado el horizonte, el futuro de cualquier objeto apunta inevitablemente hacia la singularidad)**: una vez que lo cruzas, no hay forma de volver.

Lo más fascinante de los agujeros negros es cómo distorsionan el espacio-tiempo. Si estuvieras cerca de uno, el tiempo pasaría mucho más lento para ti que para alguien en la Tierra: horas cerca del agujero negro podrían equivaler a décadas en el resto del Universo —**dilatación temporal extrema**—. Si intentaras entrar en uno de tamaño estelar, sufrirías un proceso llamado **Espaguetización (Spaghettification — el proceso de estiramiento y compresión de un objeto que cae hacia un agujero negro; ocurre porque la fuerza gravitacional en los pies es inmensamente mayor que en la cabeza —fuerza de marea—; esto estira el objeto verticalmente y lo comprime lateralmente hasta desintegrarlo en una corriente de partículas; en agujeros negros estelares ocurre antes de cruzar el horizonte; en agujeros negros supermasivos, el gradiente es más suave y se podría cruzar el horizonte sin sentirlo inmediatamente)**: la diferencia de gravedad entre tus pies y tu cabeza te estiraría como pasta antes de desintegrarte.

En 2019, el **Event Horizon Telescope (EHT — Event Horizon Telescope; una red global de radiotelescopios coordinados que actúa como un telescopio del tamaño de la Tierra mediante interferometría de muy larga base —VLBI—; en abril de 2019 capturó la primera imagen directa de un agujero negro —M87* en la galaxia M87, a 55 millones de años luz—; la imagen muestra la sombra del agujero negro rodeada por un anillo brillante del gas incandescente que lo orbita; confirmó cuantitativamente las predicciones de la relatividad general sobre la forma del horizonte de eventos)** capturó la primera imagen real de un agujero negro —M87*—. No vimos el agujero en sí sino la sombra que proyecta sobre el gas ardiente que lo rodea. En 2022 lograron la imagen del agujero negro central de nuestra propia Vía Láctea: Sagitario A*.

Los agujeros negros no son solo "aspiradoras cósmicas": son motores fundamentales que regulan el crecimiento de las galaxias emitiendo **Jets de Plasma (Relativistic Jets — chorros de plasma a velocidades relativistas —cercanas a c— emitidos desde los polos del disco de acreción de un agujero negro supermasivo; pueden extenderse decenas de miles de años luz desde la galaxia; la energía liberada puede calefaccionar el gas intergaláctico e inhibir la formación de nuevas estrellas en la galaxia huésped, regulando su crecimiento a lo largo de miles de millones de años)** desde sus polos que influyen en la formación de estrellas a miles de años luz de distancia. Son los objetos más extremos del cosmos y el laboratorio definitivo para la física que aún no comprendemos completamente.

---
**🔖 Bluebook v1 · Capítulo I, Sección 1.1** (Pág. 16)
**📐 NGSS: HS-PS2-4 · HS-ESS1-1** — Desarrollar modelos matemáticos para describir la gravitación en condiciones extremas.
**📋 RENAC / SEP-CONOCER: EC009 · Astrofísica Teórica y Cosmología**
**💡 Standards World:** Agujero Negro · Horizonte de Eventos · Singularidad · Espaguetización · Dilatación Temporal · M87* · Jets de Plasma · EHT · Sagitario A*"""
}

updated = 0
for ch in data['chapters']:
    for m in ch['modules']:
        if m['id'] in fullTexts:
            text = fullTexts[m['id']]
            m['fullText'] = text
            
            # Recalculate duration
            word_count = len(text.split())
            new_duration = math.ceil(word_count / 100) + 5
            m['duration'] = f"{new_duration} min"
            
            # Ensure Title has ID
            if not m['title'].startswith(m['id']):
                m['title'] = f"{m['id']} {m['title']}"
                
            updated += 1
            print(f"Updated {m['id']}: {word_count} words -> {new_duration} min")

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"✅ {updated} módulos de la Sección 6 actualizados correctamente.")
