# -*- coding: utf-8 -*-
import json
import os

path = '/Users/yepz/JSweb/data/modules.json'

with open(path, 'r', encoding='utf-8') as f:
    data = json.load(f)

fullTexts = {
    "1.26": """Cuando se habla de órbitas, la imagen instintiva es un planeta girando alrededor de una estrella fija y estática en el centro del sistema. Pero esta imagen es técnicamente incorrecta. Ningún cuerpo astronómico orbita alrededor de otro como si el segundo estuviera clavado al espacio. Todos los cuerpos del sistema solar —incluyendo el Sol— orbitan alrededor de un punto común llamado el **baricentro (Barycenter — el centro de masa de un sistema de dos o más cuerpos; es el punto en el que, si colgaras el sistema como si fuera un móvil, estaría perfectamente equilibrado; todos los cuerpos del sistema orbitan alrededor de este punto, no unos alrededor de otros; su posición depende de las masas relativas de los cuerpos y de la distancia entre ellos)**: el centro de masa del sistema.

El baricentro siempre está ubicado sobre la línea que une los dos cuerpos, más cerca del objeto más masivo. En el sistema **Tierra-Luna**, el baricentro se encuentra a unos 4,671 km del centro de la Tierra, que tiene un radio de 6,371 km. Esto significa que el baricentro está aproximadamente **1,700 km por debajo de la superficie terrestre**. Técnicamente, la Tierra oscila o **"bambolea" (Wobble — el movimiento oscilatorio pequeño pero real que experimenta un cuerpo masivo cuando otro cuerpo lo orbita; ambos orbitan alrededor de su baricentro común; el bamboleo del Sol causado por Júpiter es suficientemente grande para ser detectable desde otras estrellas con instrumentos modernos)** alrededor de este punto interior mientras la Luna orbita. Este bamboleo es pequeño pero medible con instrumentos **geodésicos (Geodetic Instruments — herramientas de precisión para medir la forma, tamaño y movimiento de la Tierra; incluyen receptores GPS diferenciales, interferometría de muy larga base —VLBI— y sismómetros de banda ancha; pueden detectar movimientos de la corteza terrestre de milímetros por año)** de alta precisión.

Para el sistema **Sol-Júpiter**, el dinamismo es mucho más dramático. La masa de Júpiter es 317 veces la masa de la Tierra y su efecto gravitacional sobre el Sol es significativo. El baricentro Sol-Júpiter se ubica a aproximadamente 742,000 km del centro del Sol —ligeramente **fuera de la fotosfera solar (Solar Photosphere — la superficie visible del Sol; la capa de gas desde la que escapa la mayor parte de la luz solar hacia el espacio; tiene una temperatura de aproximadamente 5,500°C y un radio de 696,000 km; por encima de ella están la cromosfera y la corona solar)**, que tiene un radio de 696,000 km. Esto significa que el Sol realiza una pequeña órbita alrededor de este punto exterior cada casi 12 años.

Este movimiento del Sol tiene una aplicación astronómica brillante: es la base del **método de velocidad radial (Radial Velocity Method / Doppler Spectroscopy — técnica para detectar exoplanetas midiendo los pequeños cambios periódicos en la velocidad del movimiento de una estrella hacia o lejos del observador causados por el tirón gravitacional de un planeta en órbita; produce cambios Doppler en las líneas espectrales de la estrella de apenas metros por segundo; fue el primer método que permitió detectar exoplanetas con seguridad, en 1995, por Michel Mayor y Didier Queloz)** para detectar exoplanetas. Cuando la estrella se mueve hacia nosotros por el tirón de su planeta, la luz que emite se comprime ligeramente —se desplaza hacia el azul en el **efecto Doppler (Doppler Effect — el cambio aparente en la frecuencia de una onda causado por el movimiento relativo entre la fuente y el observador; cuando la fuente se acerca, las ondas se comprimen —frecuencia mayor, sonido más agudo o luz más azul—; cuando se aleja, se estiran —frecuencia menor, sonido más grave o luz más roja—; es la base de los radares de velocidad, los ultrasonidos médicos y la detección de exoplanetas)**—. Cuando se aleja, la luz se estira —se desplaza hacia el rojo—. Estos desplazamientos de apenas metros por segundo son detectables con **espectrómetros (Spectrometers — instrumentos que separan la luz en sus longitudes de onda componentes para analizar su composición; los de alta resolución pueden detectar cambios de velocidad de 30 cm/s en estrellas distantes midiendo el desplazamiento de sus líneas de absorción; son los instrumentos principales de la astronomía observacional moderna)** de alta resolución y han permitido descubrir cientos de exoplanetas.

La danza de los baricentros escala hasta las galaxias enteras. Las mismas leyes aplican: dos galaxias que se orbitan mutuamente lo hacen alrededor de su baricentro compartido. La Vía Láctea y Andrómeda ya se están influenciando mutuamente gravitacionalmente, y el baricentro del **Grupo Local** determina la dinámica a gran escala de nuestro vecindario cósmico.

Entender los baricentros también es esencial para la estabilidad de misiones espaciales en los **Puntos de Lagrange (Lagrange Points — las cinco posiciones en el espacio alrededor de un sistema de dos cuerpos —como la Tierra y el Sol— donde las fuerzas gravitacionales y centrífugas se equilibran exactamente; objetos colocados en estos puntos requieren mínima propulsión para mantenerse estables; el punto L2, a 1.5 millones de km de la Tierra en dirección opuesta al Sol, es donde orbita el JWST; el L4 y L5 acumulan asteroides troyanos)**: el JWST orbita en el punto L2 del sistema Tierra-Sol, donde las fuerzas gravitacionales y centrífugas se equilibran, permitiéndole mantenerse relativamente estático respecto a la Tierra con un mínimo de combustible correctivo. El baricentro no es solo un concepto teórico: es la razón por la que el telescopio más poderoso de la humanidad puede mantenerse apuntando siempre en la misma dirección sin gastar propelente constantemente.""",
    "1.27": """¿Por qué la Tierra tiene océanos líquidos, Venus es un infierno de 465°C y Marte tiene desiertos helados? La respuesta no está solo en la composición de los planetas sino en su distancia exacta a su estrella. Existe un rango de distancias orbitales alrededor de cualquier estrella donde las temperaturas permiten que el agua exista en estado líquido en la superficie de un planeta rocoso. Los astrónomos llaman a este rango la **Zona de Habitabilidad (Habitable Zone / Circumstellar Habitable Zone — la región alrededor de una estrella donde un planeta rocoso puede mantener agua líquida en su superficie bajo una presión atmosférica adecuada; su posición y anchura dependen principalmente de la luminosidad de la estrella; fue formalizada conceptualmente por el astrofísico Stephen Dole en 1964 y ampliada posteriormente por muchos investigadores)**, y coloquialmente la **Zona de Ricitos de Oro (Goldilocks Zone — nombre coloquial de la zona de habitabilidad; alude al cuento infantil donde la protagonista busca la papilla ni muy caliente ni muy fría sino "exactamente como debe ser"; refleja la idea de que la distancia orbital de un planeta debe ser ni demasiado cercana ni demasiado lejana a su estrella para permitir agua líquida)**: no demasiado caliente, no demasiado fría.

Para el Sol, la zona de habitabilidad convencional se extiende aproximadamente entre **0.95 y 1.67 Unidades Astronómicas (Astronomical Unit / UA — unidad de distancia usada en astronomía equivalente a la distancia media entre la Tierra y el Sol; exactamente 149,597,870.7 km; es útil para describir distancias dentro de sistemas solares; más allá del sistema solar se usan años luz o parsecs)**. La Tierra orbita a exactamente 1 UA. Venus orbita a 0.72 UA —demasiado cerca— y Marte a 1.52 UA, en el borde exterior.

La zona de habitabilidad no es una línea fija; es dinámica y depende de múltiples factores. La **luminosidad estelar (Stellar Luminosity — la potencia total de energía radiada por una estrella en todas las direcciones; se mide en vatios o en unidades de luminosidad solar; determina directamente la distancia a la que debe estar un planeta para recibir suficiente calor para tener agua líquida; las estrellas más masivas son exponencialmente más luminosas)** determina dónde se ubica la zona: las enanas rojas la tienen muy cercana, las estrellas azules muy alejada. La **composición atmosférica** es un amplificador de temperatura fundamental. Venus tiene una atmósfera densa de CO₂ que crea un **efecto invernadero desbocado (Runaway Greenhouse Effect — el proceso por el que el calentamiento inicial evita que el vapor de agua —potente gas de efecto invernadero— escape, lo que retiene más calor, evaporando más agua en un ciclo de retroalimentación positiva)** elevando su temperatura de unos -15°C hipotéticos sin atmósfera a 465°C. Sin su efecto invernadero moderado, la temperatura media terrestre sería de -18°C y los océanos estarían completamente congelados.

Las **retroalimentaciones climáticas (Climate Feedbacks — los mecanismos que amplifican o amortiguan un cambio climático inicial; el ciclo carbono-silicato es un ejemplo de retroalimentación negativa estabilizadora: si la Tierra se enfría, la erosión disminuye, el CO₂ volcánico se acumula y calienta el planeta; si se calienta, la erosión aumenta, el CO₂ se consume más rápido y el planeta se enfría; este termostato geológico opera en escalas de millones de años)** también definen la habitabilidad a largo plazo. El ciclo **carbono-silicato (Carbon-Silicate Cycle — el ciclo geoquímico de largo plazo que regula el CO₂ atmosférico terrestre a lo largo de millones de años; el CO₂ reacciona con la lluvia formando ácido carbónico que erosiona las rocas silíceas, los productos se depositan como carbonatos en el fondo oceánico, y la subducción tectónica los devuelve al manto donde el vulcanismo los libera de nuevo como CO₂; este ciclo ha mantenido la Tierra habitable durante 3,800 millones de años)** ha mantenido la Tierra habitable durante casi 4,000 millones de años actuando como un termostato planetario a escala geológica.

El concepto de zona de habitabilidad también se ha expandido significativamente en la última década. Los astrobiólogos hablan ahora de la **zona de habitabilidad subsuperficial (Subsurface Habitable Zone — regiones bajo la superficie de planetas o lunas donde el calor interno —generado por radioactividad o por fuerzas de marea— puede mantener agua líquida incluso lejos de la zona de habitabilidad convencional; los mejores ejemplos son Europa y Encélado)**: océanos de agua líquida mantenidos bajo superficies de hielo por calor de marea, como ocurre en **Europa (Europa — la sexta luna más grande de Júpiter; tiene una superficie de hielo que oculta un océano global de agua líquida salada de entre 60 y 150 km de profundidad mantenido por el calor de la flexión gravitacional de Júpiter; la misión Europa Clipper de la NASA, lanzada en 2024, estudiará si sus condiciones son habitables)** y **Encélado (Enceladus — la sexta luna más grande de Saturno; tiene géiseres activos en su polo sur que expulsan agua líquida, partículas de hielo y moléculas orgánicas al espacio; la sonda Cassini detectó hidrógeno molecular en estos géiseres, indicando reacciones hidrotermales en el fondo de su océano subsuperficial compatibles con la química necesaria para la vida)**, lunas de Júpiter y Saturno respectivamente. Son hoy los candidatos más prometedores para encontrar vida microbiana dentro de nuestro propio sistema solar, sin necesidad de buscar en otras estrellas.""",
    "1.28": """Imagina que estás sumergido en el fondo de un océano de gas. No lo sientes porque has vivido ahí toda tu vida, pero cada centímetro de tu piel está siendo presionado por una mezcla invisible de moléculas que llamamos **aire (Air — la mezcla de gases que compone la atmósfera terrestre; no es una sustancia pura sino una solución gaseosa de múltiples componentes; su composición permanece extraordinariamente estable hasta los 80 km de altitud gracias a la mezcla turbulenta constante de la troposfera y la estratosfera)**. El aire no es una sustancia única; es un cóctel químico perfectamente equilibrado que permite que respiremos, que el fuego arda de forma controlada y que los sonidos viajen a nuestros oídos.

La composición del aire terrestre es una de las "marcas registradas" de nuestro planeta. El **Nitrógeno (Nitrogen / N₂ — el gas más abundante de la atmósfera terrestre con un 78.08%; es molecularmente muy estable porque el triple enlace que une sus dos átomos es uno de los más fuertes de la química; esta estabilidad lo hace inerte en condiciones normales, lo que es crucial porque diluye el oxígeno y evita que todo se encienda espontáneamente; sin embargo, las bacterias fijadoras de nitrógeno y los rayos lo convierten en formas reactivas esenciales para la vida)** ocupa el 78.08% de la atmósfera. Su inercia química es vital: diluye el oxígeno hasta una concentración segura. Si la atmósfera fuera de oxígeno puro, cualquier chispa causaría incendios incontrolables que consumirían toda la materia orgánica en minutos.

El **Oxígeno (Oxygen / O₂ — el segundo componente de la atmósfera con un 20.95%; es el comburente de la respiración aeróbica y la combustión; fue prácticamente inexistente en la atmósfera primitiva hace 3,500 millones de años; comenzó a acumularse gracias a la fotosíntesis de las cianobacterias en el evento conocido como Gran Oxidación hace 2,400 millones de años; su presencia en la atmósfera de un exoplaneta sería una potente biosignatura)** es el motor de la vida aeróbica. Lo más fascinante es que este oxígeno no estaba aquí originalmente. Fue la invención de la **fotosíntesis (Photosynthesis — el proceso bioquímico por el que las plantas, algas y cianobacterias convierten CO₂ y agua en glucosa y oxígeno usando la energía de la luz solar; la ecuación simplificada es: 6CO₂ + 6H₂O + luz → C₆H₁₂O₆ + 6O₂; es la base de casi toda la cadena alimentaria en la Tierra y la fuente de todo el oxígeno atmosférico)** por las cianobacterias lo que comenzó a liberar oxígeno como subproducto hace 3,500 millones de años. El **Gran Evento de Oxidación (Great Oxidation Event — el cambio drástico en la composición de la atmósfera terrestre ocurrido hace aproximadamente 2,400 millones de años, cuando el oxígeno producido por las cianobacterias comenzó a acumularse en la atmósfera; fue catastrófico para los organismos anaeróbicos que dominaban la Tierra pero abrió el camino para el metabolismo aeróbico y, eventualmente, para toda la vida compleja multicelular)** hace 2,400 millones de años transformó para siempre la química de la atmósfera y la trayectoria evolutiva de la vida.

El 0.93% restante es **Argón (Argon / Ar — el tercer componente más abundante de la atmósfera con un 0.93%; es un gas noble completamente inerte que no forma compuestos químicos bajo ninguna condición normal; se acumuló en la atmósfera durante miles de millones de años a través de la desintegración radiactiva del potasio-40 en el interior de la Tierra; no tiene función biológica conocida pero tampoco causa daño)**, un gas noble completamente inerte. Y luego el último 0.04% que determina el destino del clima planetario: los **gases de efecto invernadero (Greenhouse Gases — gases que absorben y reemiten radiación infrarroja en la atmósfera, atrapando el calor solar y elevando la temperatura superficial; los principales son el vapor de agua, el CO₂, el metano, el óxido nitroso y el ozono; sin ellos la temperatura media terrestre sería -18°C; el problema actual es el aumento antropogénico de su concentración, especialmente del CO₂)**, principalmente el **Dióxido de Carbono (CO₂ — gas de efecto invernadero con concentración pre-industrial de 280 ppm; actualmente supera las 422 ppm, el nivel más alto en al menos 3 millones de años; cada molécula de CO₂ tiene una vida útil en la atmósfera de entre 100 y 300 años; es también el bloque de construcción de todos los tejidos vegetales mediante la fotosíntesis)**.

Entender la composición del aire es vital para la ingeniería. El proceso **Haber-Bosch (Haber-Bosch Process — proceso industrial desarrollado por Fritz Haber y Carl Bosch en Alemania entre 1909 y 1913; sintetiza amoniaco a partir del nitrógeno atmosférico y el hidrógeno a alta temperatura y presión con un catalizador de hierro; el amoniaco producido es la base de los fertilizantes nitrogenados sintéticos; se estima que sin este proceso no podrían alimentarse más de la mitad de los 8,000 millones de personas que habitan actualmente la Tierra)** extrae nitrógeno del aire para fabricar fertilizantes, una tecnología que permite alimentar a casi la mitad de la población mundial actual. El aire no solo es lo que respiramos: es una reserva de recursos químicos que la humanidad ha aprendido a explotar con consecuencias tanto extraordinariamente positivas como preocupantes para el clima del planeta.""",
    "1.29": """Aunque parezca ligero como una pluma, el aire tiene peso. Si pudieras aislar una columna de aire de un centímetro cuadrado desde el nivel del mar hasta el borde del espacio, pesaría aproximadamente 1.03 kilogramos. Eso significa que en este momento tienes el equivalente a cientos de kilogramos de aire presionando sobre tus hombros y cabeza. La razón por la que no te aplasta es que tus fluidos internos y el aire dentro de tus pulmones ejercen la misma presión hacia afuera en equilibrio perfecto con el exterior. Esta fuerza se llama **Presión Atmosférica (Atmospheric Pressure — la fuerza por unidad de área ejercida por el peso de la columna de aire sobre cualquier superficie; al nivel del mar es de 101,325 pascales o 1 atmósfera; disminuye exponencialmente con la altitud porque hay menos masa de aire por encima; varía también con el clima local por los sistemas de alta y baja presión)**.

La presión atmosférica fue medida por primera vez de forma científica por **Evangelista Torricelli (Evangelista Torricelli — matemático y físico italiano (1608–1647); discípulo de Galileo; en 1643 demostró que el peso del aire podía sostener una columna de mercurio de 760 mm de altura en un tubo invertido; inventó el primer barómetro; su experimento demostró la existencia del vacío —anteriormente considerado imposible— y estableció las bases de la hidrostática)** en 1643. Torricelli llenó un tubo de vidrio con mercurio, lo invirtió en un plato y observó que el mercurio se detenía exactamente a 760 milímetros de altura: era el peso del aire exterior empujando el mercurio hacia arriba desde el plato. Así nació el **barómetro (Barometer — instrumento para medir la presión atmosférica; el diseño original de Torricelli usaba mercurio; los barómetros modernos son aneroides —sin líquido— y usan una cápsula metálica sellada que se comprime o expande con los cambios de presión; son fundamentales en meteorología para predecir el tiempo porque los cambios de presión preceden a los cambios climáticos)**.

La unidad de medida estándar es la **atmósfera (Atmosphere / atm — unidad de presión definida como la presión media al nivel del mar; equivale a 101,325 pascales, 760 mmHg o 14.7 psi; el pascal —Pa— es la unidad del Sistema Internacional de Unidades para presión: equivale a 1 Newton por metro cuadrado)** (atm). La presión disminuye rápidamente con la **altitud (Altitude Effect on Pressure — a mayor altitud, menor es la masa de aire por encima y por tanto menor la presión; la presión disminuye aproximadamente a la mitad cada 5,500 metros de ascenso; a la altitud del Everest —8,848 m— la presión es de solo 33,7 kPa, un tercio de la del nivel del mar; esto significa que hay un tercio menos de moléculas de oxígeno por inhalación)**. A la altura del Everest, la presión es apenas un tercio de la del nivel del mar.

Esta diferencia de presión es la que genera el **viento (Wind — el movimiento horizontal de masas de aire causado por diferencias de presión atmosférica; el aire siempre fluye de zonas de alta presión hacia zonas de baja presión intentando equilibrarlas; la rotación de la Tierra desvía estos flujos mediante el efecto Coriolis, creando los patrones de viento global: alisios, vientos del oeste y vientos polares)**. En un mapa meteorológico, las **isobaras (Isobars — líneas que unen puntos de igual presión atmosférica en un mapa meteorológico; cuando están muy juntas, la presión cambia rápidamente en distancias cortas, lo que produce vientos fuertes; cuando están separadas, el gradiente de presión es suave y el viento es débil; su patrón y densidad permiten predecir la velocidad e intensidad del viento)** son líneas que unen puntos de igual presión: donde están juntas, los vientos son fuertes; donde están separadas, el tiempo es calmado.

Para la ingeniería aeronáutica, la presión es el principio fundamental del vuelo. Según el **Principio de Bernoulli (Bernoulli's Principle — enunciado por Daniel Bernoulli en 1738; establece que en un fluido en movimiento, el aumento de velocidad se produce simultáneamente con una disminución de presión; en las alas de los aviones, la forma curvada superior obliga al aire a recorrer mayor distancia y por tanto a moverse más rápido que por la parte inferior plana, generando menor presión arriba que abajo; esta diferencia de presión produce la fuerza de sustentación que eleva el avión)**, el aire que se mueve más rápido por la parte superior curva de un ala ejercera menos presión que el aire más lento por debajo, creando la **sustentación (Lift — la fuerza aerodinámica perpendicular a la dirección del movimiento de un ala; es el resultado de la diferencia de presión entre las superficies superior e inferior del perfil alar; debe superar el peso del avión para que este despegue; depende de la densidad del aire, la velocidad, el área del ala y el ángulo de ataque)** que permite a un avión de 500 toneladas despegar. Sin la presión atmosférica, no habría vuelo, no habría clima, no habría sonido que viajar. La presión invisible del aire es la condición de casi todo lo que ocurre en la superficie de este planeta.""",
    "1.30": """Si quieres ver lo que sucede cuando el efecto invernadero se sale de control, no mires a la Tierra; mira a Venus. A menudo llamado el "gemelo malvado" de la Tierra, Venus tiene casi el mismo tamaño, masa y composición rocosa que nuestro planeta. Pero ahí terminan las similitudes. Venus es el lugar más caliente de todo el sistema solar, con una temperatura superficial constante de 465°C —suficiente para fundir el plomo— y la razón no es su cercanía al Sol sino su atmósfera: un **efecto invernadero desbocado (Runaway Greenhouse Effect — el proceso de retroalimentación positiva en el que el calentamiento inicial evapora más gas de efecto invernadero, que causa más calentamiento, que evapora más gas, sin posibilidad de estabilización; en Venus se cree que fue desencadenado hace miles de millones de años cuando el Sol se hizo más luminoso y evaporó los océanos primitivos; el CO₂ liberado por el vulcanismo no tuvo forma de ser reabsorbido sin océanos, acumulándose indefinidamente en la atmósfera)**.

La atmósfera de Venus es **90 veces más densa (90 atm Surface Pressure — la presión en la superficie de Venus equivale a la que experimentaría un humano a 900 metros de profundidad bajo el océano terrestre; cualquier estructura metálica sin diseño especial sería aplastada en minutos; fue la causa del rápido fracaso de las primeras sondas soviéticas que no aguantaron la presión)** que la de la Tierra, compuesta en un 96% por **CO₂ (Carbon Dioxide on Venus — el dióxido de carbono representa el 96.5% de la atmósfera venusiana; en la Tierra el ciclo carbono-silicato mantiene el CO₂ atmosférico en niveles bajos mediante su disolución en los océanos y conversión en rocas carbonatadas; en Venus sin océanos este ciclo no opera y todo el carbono volcánico permanece en la atmósfera como CO₂; la cantidad total de carbono en la atmósfera de Venus y en las rocas carbonatadas de la Tierra es aproximadamente la misma, lo que sugiere que ambos planetas comenzaron con composiciones similares)**. La radiación solar atraviesa las nubes de **ácido sulfúrico (Sulfuric Acid Clouds — las nubes de Venus no son de agua sino de gotitas de ácido sulfúrico concentrado H₂SO₄ a 96%; se forman a entre 45 y 70 km de altitud; reflejan el 70% de la luz solar incidente —Venus es el objeto más brillante del cielo nocturno después de la Luna— pero también producen lluvia ácida que se evapora antes de llegar a la superficie)** y llega a la superficie, pero cuando el planeta intenta irradiar ese calor de vuelta al espacio, el CO₂ lo atrapa con una eficiencia brutal. El calor no puede escapar.

Las sondas soviéticas **Venera (Venera Program — serie de misiones soviéticas a Venus entre 1961 y 1985; las sondas Venera 7-14 lograron aterrizar y transmitir datos desde la superficie; Venera 9 y 10 enviaron las primeras fotografías desde la superficie de otro planeta en 1975; la sonda más duradera, Venera 13, sobrevivió 127 minutos antes de ser destruida por la combinación de temperatura extrema, presión aplastante y corrosión ácida)** que lograron aterrizar allí en los años 70 y 80 sobrevivieron entre 20 y 127 minutos antes de ser destruidas por la combinación de calor extremo, presión aplastante y corrosión ácida.

Venus es una advertencia cosmológica directamente aplicable a la Tierra. Ambos planetas comenzaron con condiciones similares: mismo tamaño, misma masa, misma distancia al Sol en la escala evolutiva del sistema solar, posiblemente con océanos primitivos. La diferencia entre Venus hoy y la Tierra hoy es el resultado de ciclos geoquímicos que se mantuvieron estables en uno y colapsaron en el otro. Estudiar el infierno de Venus es entender el **balance energético planetario (Planetary Energy Balance — el equilibrio entre la energía solar que absorbe un planeta y la energía infrarroja que irradia de vuelta al espacio; cuando hay equilibrio, la temperatura es estable; cuando los gases de efecto invernadero aumentan, se irradia menos energía y la temperatura sube hasta alcanzar un nuevo equilibrio más caliente; en Venus este balance se alcanzó a 465°C)** y los límites de lo que un planeta puede tolerar.

En 2020, la detección de **fosfina (Phosphine / PH₃ — gas formado por fósforo e hidrógeno; en la Tierra es producida principalmente por microorganismos anaeróbicos y procesos industriales; en 2020 un equipo liderado por Jane Greaves anunció su detección en las nubes de Venus mediante espectroscopía de radio; la detección fue cuestionada y reanalizada posteriormente; sigue siendo un dato controvertido pero abrió el debate sobre si microorganismos podrían sobrevivir en las capas altas de la atmósfera venusiana a temperaturas y presiones más moderadas)** en las nubes de Venus reabrió el debate sobre vida en los cielos del planeta más hostil del sistema solar.""",
    "1.31": """La Tierra tiene un escudo invisible que nos protege de la mayor amenaza del espacio profundo: el **Viento Solar (Solar Wind — el flujo continuo de partículas cargadas —principalmente protones y electrones— que emana del Sol a velocidades de 400–800 km/s; si alcanzara la superficie terrestre sin obstáculo, erosionaría la atmósfera, dañaría el ADN de los organismos y haría la vida tal como la conocemos imposible; Marte perdió la mayor parte de su atmósfera así, al perder su campo magnético hace 4,000 millones de años)**. Sin este escudo, la atmósfera terrestre habría sido barrida hace miles de millones de años. Este escudo es la **Magnetósfera (Magnetosphere — la región del espacio alrededor de la Tierra dominada por su campo magnético; se extiende desde la superficie terrestre hasta miles de kilómetros en el espacio, formando una burbuja protectora en forma de lágrima asimétrica comprimida por el viento solar en el lado del Sol y extendida como una cola en el lado opuesto)**, un campo magnético colosal generado en las profundidades de nuestro planeta.

El origen de este campo está en el **Efecto Dínamo (Dynamo Effect / Geodynamo — el mecanismo por el que el movimiento convectivo de materiales conductores en el núcleo externo de la Tierra genera el campo magnético terrestre; funciona de forma análoga a un generador eléctrico: el hierro líquido en movimiento actúa como un conductor en un campo magnético preexistente, generando corrientes que refuerzan y mantienen el campo; requiere tanto la conductividad del material como la rotación del planeta)**: el hierro y níquel fundidos del núcleo externo están en constante movimiento convectivo por el calor del núcleo interno sólido. Como el hierro es un excelente conductor eléctrico, este movimiento genera corrientes eléctricas que a su vez producen el campo magnético.

Cuando una ráfaga de viento solar choca contra la magnetósfera, las partículas cargadas son canalizadas por las líneas de campo hacia los polos norte y sur magnéticos. Al chocar con los gases de la alta atmósfera, estas partículas excitan átomos de oxígeno y nitrógeno que emiten luz al relajarse: las magníficas **Auroras Boreales y Australes (Aurora Borealis / Aurora Australis — fenómeno luminoso en la alta atmósfera —entre 100 y 300 km de altitud— causado por partículas cargadas del viento solar que siguen las líneas del campo magnético hacia los polos y colisionan con moléculas de oxígeno y nitrógeno; el oxígeno produce verde y rojo, el nitrógeno produce azul y púrpura; son más intensas durante las tormentas geomagnéticas)**, el espectáculo más hermoso de la naturaleza.

Sin embargo, el campo magnético no es estático. A lo largo de la historia geológica, los polos magnéticos se han intercambiado en un proceso llamado **Inversión de los Polos (Geomagnetic Reversal / Pole Reversal — el proceso por el que el norte y sur magnéticos intercambian posiciones; ocurre irregularmente cada 200,000 a 300,000 años en promedio; la última ocurrió hace 780,000 años —más allá del promedio histórico—; durante la transición, que dura entre 1,000 y 10,000 años, el campo se debilita y se vuelve caótico, dejando a la Tierra con menor protección frente a la radiación solar y cósmica)**. La última ocurrió hace 780,000 años.

Para la civilización tecnológica, la magnetósfera es crítica. El **Evento Carrington (Carrington Event — la tormenta geomagnética más intensa registrada en la historia; ocurrió en septiembre de 1859 cuando una eyección de masa coronal gigante alcanzó la Tierra; produjo auroras visibles en el Caribe y México; indujo corrientes eléctricas tan poderosas en los cables de telégrafo que causaron incendios y permitió a los operadores telegrafiar sin batería; si un evento similar ocurriera hoy, los daños a satélites, redes eléctricas y sistemas de comunicación se estiman en billones de dólares)** de 1859 fue tan poderoso que indujo corrientes en los cables telegráficos que los quemaron. Un evento equivalente hoy causaría daños catastróficos a la infraestructura tecnológica global. Entender y monitorear la magnetósfera no es solo ciencia fundamental: es proteger la civilización digital moderna.""",
    "1.32": """¿Dónde termina la Tierra y empieza el espacio? No hay una línea pintada en el cielo ni un cambio abrupto en la oscuridad. Lo que hay es una transición gradual donde las moléculas del aire se vuelven cada vez más escasas hasta que el concepto de "atmósfera" deja de tener sentido físico. Esta última frontera se llama la **Exósfera (Exosphere — la capa más externa de la atmósfera terrestre; comienza aproximadamente a 500–700 km de altitud y se extiende hasta unos 10,000 km; en ella las partículas están tan separadas que raramente colisionan entre sí; los átomos siguen trayectorias balísticas bajo la gravedad, y algunos con suficiente energía térmica alcanzan la velocidad de escape y se pierden al espacio)**.

En la exósfera, el aire es tan tenue que los átomos y moléculas están separados por cientos de kilómetros. Aquí, las partículas no interactúan como en las capas inferiores; siguen **trayectorias balísticas (Ballistic Trajectories — las curvas parabólicas o elípticas que sigue un objeto bajo la influencia exclusiva de la gravedad, sin resistencia del aire; en la exósfera, las partículas rebotan entre colisiones tan raras que sus trayectorias son esencialmente balísticas; los satélites a bajas altitudes están técnicamente en la exósfera superior y experimentan un freno atmosférico mínimo pero acumulado)** bajo la gravedad. Algunas partículas se mueven tan rápido que alcanzan la **velocidad de escape (Escape Velocity — la velocidad mínima que necesita un objeto para escapar del campo gravitacional de un cuerpo celeste sin propulsión adicional; para la Tierra es 11.2 km/s; los átomos ligeros como el hidrógeno y el helio pueden alcanzarla por agitación térmica y se pierden lentamente al espacio —"escape atmosférico"—; es por eso que la Tierra retiene el nitrógeno y el oxígeno pero ha perdido gran parte de su hidrógeno y helio primitivos)** y se pierden para siempre en el espacio.

Para fines legales y de aviación, el mundo utiliza la **Línea de Kármán (Kármán Line — la frontera convencional entre la atmósfera y el espacio exterior, ubicada a 100 km de altitud; fue propuesta por el ingeniero aeroespacial Theodore von Kármán; por encima de esta altitud, el aire es tan tenue que un ala aerodinámica necesitaría moverse a velocidad orbital para generar sustentación, lo que hace que la distinción entre aviación y astronáutica pierda sentido; la FAI —Federación Aeronáutica Internacional— la usa como definición oficial de "espacio")** a 100 km de altitud. Cruzar esta línea te define oficialmente como astronauta. Por encima de ella están la mayoría de los satélites artificiales y la **ISS (International Space Station — la Estación Espacial Internacional; orbita la Tierra a unos 408 km de altitud, bien dentro de la exósfera; completa una órbita cada 92 minutos a 7.66 km/s; ha albergado a más de 270 astronautas de 20 países desde el lanzamiento de su primer módulo en 1998; el arrastre atmosférico residual de la exósfera a esa altitud hace que su órbita decaiga gradualmente y requiera reboosting periódico)**.

Los **Cinturones de Van Allen (Van Allen Radiation Belts — dos regiones en forma de toroide dentro de la magnetósfera donde partículas cargadas de alta energía del viento solar quedan atrapadas por el campo magnético terrestre; el cinturón interior, a 700–6,000 km de altitud, está dominado por protones de alta energía; el exterior, a 13,000–60,000 km, por electrones; representan una dosis de radiación significativa para los astronautas y los electrónicos de los satélites; las misiones Apollo tuvieron que cruzarlos rápidamente para minimizar la exposición)** son dos regiones de partículas de alta energía atrapadas por el campo magnético que representan peligro para los astronautas y los electrónicos de los satélites.

Hoy la exósfera se ha poblado de **basura espacial (Space Debris / Orbital Debris — los fragmentos de satélites y cohetes desactivados que orbitan la Tierra a velocidades de hasta 28,000 km/h; un objeto de 1 cm a esa velocidad tiene la energía cinética de una granada de mano; hay más de 27,000 fragmentos rastreados y millones de objetos demasiado pequeños para ser seguidos individualmente; el Síndrome de Kessler —propuesto por Donald Kessler en 1978— advierte que si la densidad de desechos supera un umbral crítico, las colisiones en cadena podrían hacer inutilizables algunas órbitas de forma permanente)**. La exósfera nos recuerda que somos un sistema abierto: la Tierra libera continuamente hidrógeno y helio al espacio mientras recibe polvo de meteoritos y energía solar. No somos una cápsula sellada sino un planeta que respira hacia el cosmos a través de su frontera más sutil.""",
}

updated = 0
for ch in data['chapters']:
    for m in ch['modules']:
        if m['id'] in fullTexts:
            m['fullText'] = fullTexts[m['id']]
            updated += 1

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"✅ {updated} módulos actualizados correctamente.")
