import json

updates = {
"1.8.5": """En el corazón de los átomos más pesados de la naturaleza, existe una tensión energética tan grande que un solo gramo de materia puede contener la misma energía que toneladas de carbón. El proceso para liberar este poder se basa en la ruptura del núcleo atómico, una proeza de la física conocida como la **Fisión de Uranio (Uranium Fission — una reacción nuclear en la que el núcleo de un átomo pesado, típicamente Uranio-235, se divide en dos núcleos más pequeños tras ser impactado por un neutrón lento; este proceso libera una cantidad masiva de energía en forma de calor y radiación, además de más neutrones que pueden inducir nuevas fisiones; es la base de los reactores nucleares actuales y de las primeras armas atómicas, representando la transición de la humanidad hacia una civilización capaz de manejar las energías fundamentales del núcleo)**. La fisión del uranio es el motor que ha impulsado la era atómica, ofreciendo una fuente de energía densa y sin carbono, pero con retos tecnológicos y éticos inmensos.

El uranio no es un combustible común; es un elemento forjado en las condiciones extremas de las supernovas que ahora descansa en la corteza terrestre esperando ser activado. Cuando un neutrón golpea un núcleo de Uranio-235, el núcleo se vuelve inestable y se estira hasta que la repulsión eléctrica entre sus protones vence a la fuerza nuclear fuerte, rompiéndolo en pedazos. Esta ruptura convierte una pequeña fracción de la masa del átomo directamente en energía pura, siguiendo la famosa ecuación de Einstein E=mc². Es la forma más eficiente que conocemos de extraer energía de la materia sólida.

Para que la fisión sea útil para generar electricidad, debe mantenerse en un estado de **Reacción en Cadena Controlada (Controlled Chain Reaction — proceso en el que los neutrones liberados por una fisión inducen al menos una nueva fisión en otros núcleos cercanos, manteniendo un flujo constante de energía; en un reactor nuclear, esto se logra mediante el uso de moderadores —que frenan los neutrones— y barras de control —que absorben el exceso de neutrones— para asegurar que la reacción no se acelere fuera de control ni se apague espontáneamente)**. Dominar esta reacción es el objetivo principal de la ingeniería nuclear moderna.

El isótopo clave para este proceso es el **Uranio-235 (U-235 — el único isótopo fisible por neutrones lentos que se encuentra en la naturaleza en cantidades significativas; representa solo el 0.7% del uranio natural, siendo el resto principalmente Uranio-238, que no es fácilmente fisible; para ser usado en la mayoría de los reactores, el uranio natural debe someterse a un proceso de enriquecimiento para aumentar la proporción de U-235, una tarea tecnológica compleja que utiliza centrifugadoras de alta velocidad)**. El acceso al U-235 es, por tanto, un tema de gran importancia estratégica y geopolítica.

Un subproducto inevitable de la fisión son los **Productos de Fisión (Fission Products — los fragmentos de los núcleos de uranio rotos, como el cesio, el estroncio o el yodo; estos nuevos átomos suelen ser altamente radiactivos y son los responsables de la mayor parte de la radiactividad de los residuos nucleares; su manejo requiere sistemas de enfriamiento y blindaje extremadamente robustos debido al calor residual que generan incluso después de que el reactor se apague)**. La gestión de estos productos es el mayor desafío ambiental de la energía nuclear.

**Casos de Estudio y Aplicaciones Reales**

Un caso de estudio fundamental es el diseño de los **Reactores de Agua a Presión (PWR / Pressurized Water Reactors)**, que son el tipo de reactor más común en el mundo hoy en día. En estos sistemas, el calor generado por la fisión del uranio calienta agua a presiones tan altas que no llega a hervir; este calor se transfiere luego a un segundo circuito de agua que sí se convierte en vapor para mover las turbinas eléctricas. Este diseño de doble circuito actúa como una barrera de seguridad crítica, manteniendo el agua que ha estado en contacto directo con el uranio aislada del medio ambiente y del sistema de generación de electricidad.

En la historia de la ciencia, el experimento de la **Primera Pila Atómica (Chicago Pile-1)** liderado por Enrico Fermi en 1942 es el ejemplo supremo de prueba de concepto. En una cancha de squash subterránea en Chicago, los científicos demostraron por primera vez que era posible iniciar y detener una reacción en cadena de uranio de forma controlada. Fue el momento en que la energía nuclear pasó de ser una teoría matemática a una realidad de ingeniería, abriendo las puertas tanto a la promesa de energía ilimitada como a los peligros de la proliferación nuclear.

Otro ejemplo de aplicación de vanguardia es el desarrollo de los **Pequeños Reactores Modulares (SMRs / Small Modular Reactors)**. A diferencia de las centrales nucleares gigantes del pasado, los SMRs están diseñados para ser fabricados en serie en fábricas y transportados listos para usar. Utilizan sistemas de seguridad pasiva que no requieren intervención humana ni energía externa para detener la fisión en caso de emergencia, representando el futuro de la energía nuclear segura y flexible para alimentar ciudades inteligentes o bases remotas en el Ártico o incluso en otros planetas.

**Conclusión Estratégica**

La fisión del uranio es la herramienta que permitió a la humanidad superar los límites de la energía química de los combustibles fósiles. Para los futuros ingenieros nucleares, físicos de materiales y especialistas en política energética, comprender la fisión es esencial para gestionar un recurso que puede ser la solución al cambio climático si se maneja con la responsabilidad y la técnica adecuadas. Es una tecnología que nos obliga a ser una especie más madura y cuidadosa.

Entender la fisión nos enseña que el átomo es una fuente de poder casi inimaginable, pero que ese poder requiere un respeto absoluto por las leyes de la física y la seguridad ambiental. Para un estudiante STEM, el estudio del uranio es una lección de cómo la ciencia básica puede transformar la geopolítica mundial y cómo la ingeniería de precisión puede convertir un material peligroso en la luz que ilumina millones de hogares. La era del uranio ha sido solo el comienzo de nuestra relación con las fuerzas del núcleo.

🔖 Bluebook v1 · Capítulo I, Sección 1.8.5 — Fisión de Uranio (Págs. 276–279)
📐 NGSS: HS-PS1-8 (Nuclear processes and fission) — Develop models to illustrate the changes in the composition of the nucleus of the atom and the energy released during fission.
📋 RENAC: ET005 · Ingeniería de Reactores Nucleares y Ciclo del Combustible
💡 Standards World: Uranium Fission (Fisión de Uranio) · Chain Reaction (Reacción en Cadena) · Nuclear Fuel (Combustible Nuclear)""",

"1.8.6": """En las misiones espaciales que se aventuran hacia los rincones más oscuros y fríos del sistema solar, donde la luz del Sol es demasiado tenue para alimentar paneles solares, la humanidad depende de un tipo de batería extraordinario que no se agota durante décadas. Estas fuentes de energía, silenciosas y sin partes móviles, funcionan gracias al calor natural de la desintegración radiactiva. Se conocen como **RTGs: Baterías Atómicas (Radioisotope Thermoelectric Generators — dispositivos que convierten el calor liberado por la desintegración espontánea de un isótopo radiactivo, comúnmente Plutonio-238, en electricidad mediante el efecto Seebeck; a diferencia de un reactor nuclear, no hay reacción en cadena ni fisión inducida, solo el aprovechamiento del calor natural de la radiactividad; son la fuente de energía preferida para sondas de espacio profundo y rovers marcianos debido a su increíble fiabilidad y longevidad)**. Los RTGs son los "corazones atómicos" que han permitido a la humanidad ver por primera vez los mundos exteriores.

La magia tecnológica de un RTG reside en su simplicidad y robustez. Mientras que una batería química o un motor de combustión fallarían en el frío extremo del espacio o se agotarían en poco tiempo, un RTG sigue produciendo energía de forma constante mientras los átomos en su interior se desintegren. Para misiones como las Voyager, que llevan más de 45 años en el espacio interestelar, el RTG es lo único que mantiene encendidos sus instrumentos y su radio para comunicarse con la Tierra a miles de millones de kilómetros de distancia.

El componente que transforma el calor en luz eléctrica es el **Termopar (Thermocouple — un dispositivo compuesto por dos metales o semiconductores diferentes unidos en un extremo; cuando existe una diferencia de temperatura entre la unión caliente —calentada por el radioisótopo— y la unión fría —enfriada por el vacío del espacio—, se genera un voltaje eléctrico proporcional; este fenómeno físico se llama efecto Seebeck y permite una conversión directa de calor en electricidad sin necesidad de turbinas, pistones o fluidos en movimiento, lo que elimina el riesgo de fallos mecánicos)**. Es la proeza definitiva de la física de estado sólido aplicada a la energía.

El combustible más utilizado es el **Plutonio-238 (Pu-238 — un isótopo radiactivo del plutonio que emite partículas alfa de alta energía; se elige para los RTGs porque tiene una vida media ideal de 87.7 años, lo que garantiza energía durante décadas, y porque su radiación alfa es fácil de blindar, minimizando el daño a la electrónica sensible de la nave; además, tiene una alta densidad de potencia térmica, produciendo unos 0.5 vatios de calor por gramo de material)**. El Pu-238 es un material extremadamente raro y valioso que solo se produce en reactores nucleares especializados.

La seguridad de estos dispositivos es una prioridad absoluta en la ingeniería aeroespacial, utilizando el **Blindaje de Grafito Multicapa (Multilayer Graphite Shielding — sistema de protección extremadamente resistente diseñado para contener el combustible radiactivo incluso en caso de una explosión del cohete lanzador o una reentrada accidental en la atmósfera terrestre; el plutonio se encapsula en cerámica de alta resistencia y se rodea de capas de grafito que pueden soportar temperaturas y presiones inmensas, garantizando que el material radiactivo nunca se disperse en el medio ambiente)**. Los RTGs están diseñados para ser las baterías más seguras del sistema solar.

**Casos de Estudio y Aplicaciones Reales**

El caso de estudio más exitoso y vigente es el del rover **Curiosity y el Perseverance en Marte**. Estos laboratorios móviles del tamaño de un coche no tienen paneles solares; en su lugar, llevan un MMRTG (Multi-Mission Radioisotope Thermoelectric Generator) en su parte trasera. Esto les permite operar de noche, durante las tormentas de polvo globales que oscurecen el cielo marciano y en el invierno helado del planeta rojo. Sin esta batería atómica, el Perseverance no podría alimentar su láser de alta potencia para analizar rocas ni mantener caliente su electrónica crítica, demostrando que la energía nuclear es el habilitador tecnológico de la exploración planetaria moderna.

Otro ejemplo histórico son las sondas **Voyager 1 y 2**. Lanzadas en 1977, sus RTGs han estado funcionando continuamente durante casi medio siglo. A medida que el plutonio se desintegra y los termopares se degradan lentamente, la potencia disponible disminuye unos pocos vatios cada año. Los ingenieros de la NASA deben apagar instrumentos de forma selectiva para conservar la energía restante, una proeza de gestión de recursos a distancia que nos permite seguir recibiendo datos del medio interestelar. Es el ejemplo supremo de longevidad tecnológica y planificación de ingeniería a largo plazo.

En la Tierra, los RTGs también tuvieron aplicaciones en lugares remotos, como los **Faros Árticos de la antigua Unión Soviética**. Durante la Guerra Fría, se instalaron cientos de generadores atómicos para alimentar faros automáticos en las costas desoladas del Ártico donde era imposible llevar combustible o cables eléctricos. Aunque muchos han sido retirados por seguridad, representaron una solución de ingeniería radical para el problema de la energía en entornos extremos, demostrando que la radiactividad puede ser una herramienta de infraestructura civil vital.

**Conclusión Estratégica**

Los RTGs son el puente entre la física nuclear y la conquista del espacio profundo. Para los futuros ingenieros aeroespaciales, especialistas en sistemas de energía y astrofísicos, comprender estos generadores es fundamental para diseñar misiones que vayan más allá de Marte o que busquen explorar los océanos helados de Europa y Encélado. Sin la densidad energética y la fiabilidad de la desintegración radiactiva, la mayor parte del sistema solar seguiría siendo invisible para nosotros.

Entender cómo el calor de un átomo puede alimentar una radio a billones de kilómetros nos enseña la potencia de las leyes físicas fundamentales. Para un estudiante STEM, el RTG es un recordatorio de que la innovación consiste a menudo en encontrar formas elegantes y simples de aprovechar procesos naturales complejos. La energía nuclear no es solo una opción para la Tierra; es la condición necesaria para que la humanidad se convierta en una especie capaz de explorar la verdadera inmensidad del cosmos.

🔖 Bluebook v1 · Capítulo I, Sección 1.8.6 — RTGs: Baterías Atómicas (Págs. 280–283)
📐 NGSS: HS-PS3-3 (Energy conversion devices) — Design, build, and refine a device that works within given constraints to convert one form of energy into another form of energy (applied to thermoelectric effects).
📋 RENAC: EC009 · Tecnología Aeroespacial y Sistemas de Energía Espacial
💡 Standards World: RTG (RTG) · Thermoelectric Effect (Efecto Termoeléctrico) · Plutonium-238 (Plutonio-238)""",

"1.8.7": """En la intersección entre la física atómica y la biología molecular, existe un campo de estudio crítico para la supervivencia de la vida en la Tierra y en el espacio. La radiación ionizante, aunque invisible, tiene la capacidad de interactuar directamente con la molécula más importante de nuestro cuerpo, alterando el código de la vida. Esta interacción es lo que estudiamos en **ADN y Radiación (DNA & Radiation — el proceso por el cual las partículas alfa, beta o los rayos gamma impactan las moléculas de ADN, causando daños directos como la rotura de las hebras o daños indirectos mediante la creación de radicales libres; si estos daños no son reparados correctamente por la célula, pueden dar lugar a mutaciones, cáncer o muerte celular; sin embargo, este mismo proceso es la base de la evolución biológica y de tratamientos médicos avanzados contra tumores)**. Comprender esta relación es la base de la medicina moderna y de la seguridad de los futuros astronautas que viajen a Marte.

El ADN es una estructura asombrosamente resistente pero vulnerable a los proyectiles atómicos. Cada día, las células de nuestro cuerpo sufren miles de daños en su ADN debido a causas naturales, y han desarrollado mecanismos de reparación increíblemente sofisticados para corregirlos. Sin embargo, la radiación de alta energía puede causar daños tan complejos que superan la capacidad de reparación de la célula. Este equilibrio entre el daño atómico y la reparación biológica es lo que define nuestra salud y nuestra longevidad en un universo lleno de radiación.

El principal mecanismo de daño es la **Ionización Indirecta (Indirect Ionization — proceso en el que la radiación choca con las moléculas de agua que rodean al ADN, rompiéndolas y creando radicales libres altamente reactivos como el hidroxilo OH•; estos radicales atacan químicamente al ADN, causando la mayoría de los daños biológicos observados; se estima que el 70% del daño por radiación en las células humanas es causado por este proceso indirecto mediado por el agua)**. Nuestra propia composición líquida es lo que nos hace vulnerables a la radiación.

Cuando la radiación golpea directamente la doble hélice, puede causar una **Rotura de Doble Hebra (Double-Strand Break / DSB — el tipo de daño más peligroso para el ADN, donde ambas hebras de la hélice se rompen en el mismo lugar; a diferencia de las roturas de hebra simple, que son fáciles de reparar usando la otra hebra como plantilla, las DSB son difíciles de arreglar y suelen llevar a errores en el código genético o al suicidio celular programado —apoptosis—; es el mecanismo principal por el cual la radioterapia destruye las células cancerosas)**. Es el "corte" definitivo en el manual de instrucciones de la vida.

En respuesta a estos ataques, nuestras células activan complejos de proteínas llamados **Mecanismos de Reparación del ADN (DNA Repair Mechanisms — un conjunto de procesos biológicos enzimáticos que detectan y corrigen los daños en el genoma; incluyen la reparación por escisión de bases y la unión de extremos no homólogos; la eficiencia de estos mecanismos varía entre individuos y especies, y es lo que determina la resistencia a la radiación; los organismos extremófilos, por ejemplo, tienen mecanismos de reparación tan potentes que pueden sobrevivir a dosis de radiación miles de veces superiores a las que matarían a un ser humano)**. Estos mecanismos son la verdadera armadura biológica de la vida.

**Casos de Estudio y Aplicaciones Reales**

Un caso de estudio fascinante es el de la bacteria **Deinococcus radiodurans**, conocida como "la bacteria Conan". Este organismo puede sobrevivir a dosis de radiación de hasta 5,000 Gray (10 Gray es letal para un humano). Su secreto no es que su ADN no se rompa —la radiación lo hace pedazos—, sino que posee múltiples copias de su genoma y un sistema de reparación ultra-rápido que reconstruye su código genético en cuestión de horas. Estudiar a esta bacteria está ayudando a los científicos a diseñar terapias génicas y fármacos protectores para los astronautas que deberán pasar años expuestos a la radiación cósmica en su viaje a Marte.

En la medicina oncológica, la **Radiocirugía (Radiosurgery)** es la aplicación práctica más directa de este conocimiento. Utilizando múltiples haces de rayos gamma o protones que convergen en un solo punto, los médicos pueden causar daños masivos e irreparables en el ADN de un tumor cerebral profundo sin necesidad de abrir el cráneo. La precisión de la física permite que solo las células del tumor reciban una dosis superior a su capacidad de reparación, mientras que el tejido sano circundante sobrevive. Es la cirugía sin bisturí, realizada mediante proyectiles atómicos dirigidos al corazón del código genético.

Otro ejemplo crítico es el estudio del **Efecto de la Radiación Cósmica en Astronautas**. En la ISS y más allá de la magnetósfera terrestre, los astronautas están expuestos a núcleos pesados de alta energía (HZE particles) que causan daños en el ADN muy diferentes a los de los rayos X terrestres. La NASA estudia constantemente la sangre de los astronautas para detectar cambios en sus cromosomas y entender el riesgo a largo plazo de desarrollar cáncer o enfermedades degenerativas. Este conocimiento es fundamental para diseñar el blindaje de las futuras naves espaciales y los hábitats lunares y marcianos.

**Conclusión Estratégica**

La interacción entre el ADN y la radiación es la frontera última de la biofísica. Para los futuros médicos, genetistas, bioingenieros y especialistas en medicina espacial, comprender este proceso es vital para proteger la vida en entornos extremos y para mejorar los tratamientos contra el cáncer. No es solo un tema de peligro; es un tema de diseño biológico y resistencia ante las fuerzas fundamentales del universo.

Entender cómo la radiación puede tanto destruir la vida como ser la herramienta para curarla nos enseña la importancia de la dosis, la precisión y el tiempo. Para un estudiante STEM, este campo es el ejemplo perfecto de cómo la física atómica gobierna los procesos biológicos más íntimos. La vida ha aprendido a convivir con la radiación durante billones de años; nuestro reto ahora es usar la ciencia para dominar esa relación y permitir que la humanidad dé el siguiente paso hacia las estrellas de forma segura y saludable.

🔖 Bluebook v1 · Capítulo I, Sección 1.8.7 — ADN y Radiación (Págs. 284–287)
📐 NGSS: HS-LS3-2 (Inheritance and variation of traits) — Make and defend a claim based on evidence that inheritable genetic variations may result from: (1) viable errors during replication, and/or (2) mutations caused by environmental factors (radiation).
📋 RENAC: EC009 · Radiobiología y Genética Molecular
💡 Standards World: DNA Repair (Reparación del ADN) · Ionizing Radiation (Radiación Ionizante) · Mutagenesis (Mutagénesis)""",

"1.8.8": """En el gran teatro del universo, existe una ley tan absoluta y poderosa que gobierna desde el funcionamiento de tu smartphone hasta la muerte de las estrellas y el destino final del cosmos. Esta ley nos dice que la energía no se puede crear ni destruir, solo transformar, pero que en cada transformación, una parte de esa energía se vuelve inevitablemente inútil y se pierde en forma de desorden. Este estudio del calor, el trabajo y el flujo de la energía es lo que llamamos **Termodinámica (Thermodynamics — la rama de la física que estudia las relaciones entre el calor, la energía, el trabajo y las propiedades físicas de la materia; se basa en cuatro leyes fundamentales que definen conceptos como la temperatura, la conservación de la energía y la entropía; es la ciencia que explica por qué los motores se calientan, por qué el hielo se derrite y por qué el tiempo siempre fluye en una sola dirección hacia el futuro)**. La termodinámica es la regla de juego definitiva de la naturaleza.

Entender la termodinámica es entender los límites de lo posible en ingeniería y ciencia. Nos enseña que no existen las máquinas de movimiento perpetuo y que siempre hay un "impuesto" energético que pagar en forma de calor. Esta realidad física es la que impulsa la búsqueda de la eficiencia en todo lo que construimos, desde motores de cohetes hasta procesadores de computadoras. La termodinámica es la brújula que nos dice qué tan cerca estamos de la perfección técnica y cuánta energía realmente necesitamos para realizar una tarea.

La base de todo el universo energético es la **Primera Ley de la Termodinámica (First Law of Thermodynamics / Conservation of Energy — principio que establece que la energía total de un sistema aislado se mantiene constante; la energía puede cambiar de forma —por ejemplo, de energía química a calor o de electricidad a movimiento— pero la suma total siempre es la misma; en términos de ingeniería, significa que no puedes obtener más trabajo de una máquina de la energía que le suministras)**. Es la ley de la honestidad energética universal.

Sin embargo, la ley más profunda y misteriosa es la **Segunda Ley de la Termodinámica (Second Law of Thermodynamics / Entropy — principio que establece que en cualquier proceso espontáneo, el desorden total del universo —la entropía— siempre aumenta; esto implica que el calor siempre fluye de forma natural de los cuerpos calientes a los fríos y nunca al revés de forma espontánea; la entropía es la que da al tiempo su flecha, marcando la diferencia entre el pasado ordenado y el futuro desordenado; es la razón por la que las cosas se rompen, se oxidan y envejecen)**. La entropía es la medida del caos en el sistema.

Para medir la eficiencia de cualquier proceso, los ingenieros utilizan el concepto de **Ciclo de Carnot (Carnot Cycle — un modelo teórico ideal que define la eficiencia máxima que cualquier motor térmico puede alcanzar al operar entre dos temperaturas; fue propuesto por Sadi Carnot en 1824 y demostró que la eficiencia nunca puede ser del 100% debido a la inevitable pérdida de calor hacia el entorno; este límite es el que guía el diseño de turbinas en centrales eléctricas, motores de combustión y sistemas de refrigeración modernos)**. Es el "estándar de oro" de la eficiencia energética.

**Casos de Estudio y Aplicaciones Reales**

Un caso de estudio fundamental es el diseño de la **Refrigeración por Compresión de Vapor** que usamos en nuestros hogares. Para enfriar el interior de un refrigerador (disminuir su entropía local), debemos realizar un trabajo eléctrico para extraer el calor y expulsarlo al exterior, aumentando la entropía total de la habitación. Este proceso es una aplicación directa de las leyes de la termodinámica, demostrando que para crear orden y frío en un lugar, debemos crear aún más desorden y calor en otro. La ingeniería de refrigeración es el arte de manipular el flujo de calor contra su tendencia natural.

En la escala cósmica, el estudio de la **Muerte Térmica del Universo (Heat Death of the Universe)** es la aplicación más extrema de la segunda ley. Si la entropía siempre aumenta, llegará un momento en el futuro lejano (trillones de años) en el que toda la energía útil se habrá convertido en calor uniforme y el universo alcanzará un estado de equilibrio térmico donde ya no podrá ocurrir ningún proceso físico ni biológico. Este es el destino final de la termodinámica: un universo frío, oscuro y estático donde el tiempo mismo dejará de tener sentido. Es la lección definitiva de humildad ante las leyes de la energía.

En la ingeniería de vanguardia, el desarrollo de la **Termodinámica a Escala Nanométrica** es crucial para el futuro de la computación. A medida que los transistores se vuelven más pequeños, el calor que generan se vuelve más difícil de manejar, amenazando con derretir los chips. Los ingenieros de Intel y AMD utilizan modelos termodinámicos avanzados para diseñar sistemas de disipación de calor que permitan que los procesadores sigan aumentando su velocidad sin violar los límites térmicos impuestos por la física. Gestionar el calor es hoy el mayor obstáculo para la inteligencia artificial y la computación de alto rendimiento.

**Conclusión Estratégica**

La termodinámica es la ley que rige la economía de la energía en el universo. Para los futuros ingenieros mecánicos, arquitectos sustentables, físicos y ecólogos, comprender el flujo del calor y el trabajo es esencial para diseñar un mundo que aproveche mejor sus recursos limitados. En un planeta con recursos energéticos finitos, la eficiencia termodinámica no es solo una cuestión de física, sino una necesidad ética y de supervivencia global.

Aprender termodinámica nos enseña a ser humildes ante la naturaleza y creativos ante sus limitaciones. Nos muestra que el universo tiene reglas inquebrantables, pero que dentro de esas reglas, el ingenio humano puede construir maravillas de eficiencia y belleza. Para un estudiante STEM, la termodinámica es la base de toda la ingeniería moderna y el recordatorio de que somos seres que consumen energía para crear orden, un acto heroico de desafío contra la entropía que define nuestra propia existencia.

🔖 Bluebook v1 · Capítulo I, Sección 1.8.8 — Termodinámica (Págs. 288–291)
📐 NGSS: HS-PS3-2 (Conservation of energy and energy transfer) — Develop and use models to illustrate that energy at the macroscopic scale can be accounted for as a combination of energy associated with the motions of particles and energy associated with the relative positions of particles.
📋 RENAC: EC009 · Termofísica e Ingeniería de Energía
💡 Standards World: Thermodynamics (Termodinámica) · Entropy (Entropía) · Efficiency (Eficiencia)"""
}

with open('/Users/yepz/JSweb/data/modules.json', 'r') as f:
    data = json.load(f)

count = 0
for chapter in data['chapters']:
    for module in chapter['modules']:
        if module['id'] in updates:
            module['fullText'] = updates[module['id']]
            count += 1

with open('/Users/yepz/JSweb/data/modules.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Updated {count} modules")
for mid, text in updates.items():
    words = len(text.split())
    print(f"  {mid}: {words} words / {len(text)} chars")
