import json

updates = {
"1.1.2": """Si el Big Bang es el "cuándo" del origen del universo, las Eras de la Materia son el "cómo": la secuencia de transformaciones que convirtió una sopa de energía pura en los protones, neutrones y electrones que componen todo lo que existe. En los primeros instantes, el universo era tan caliente que ni siquiera los quarks podían unirse para formar partículas. La materia que conocemos —átomos, moléculas, estrellas, tú— fue construida en etapas bien definidas, cada una gobernada por las mismas leyes de la física que podemos estudiar hoy en aceleradores de partículas. Entender estas eras no es solo historia cósmica; es entender la arquitectura fundamental de la materia.

La física de partículas es la disciplina que permite reconstruir estas épocas con precisión. En el CERN, colisiones de protones a velocidades relativistas recrean brevemente las condiciones del universo en sus primeros microsegundos. Cada vez que el LHC detecta una partícula nueva o mide una propiedad con mayor precisión, añade una página al libro de las eras de la materia. Esta conexión entre el cosmos y el laboratorio hace de la física de partículas una de las ciencias más fundamentales y más apasionantes de nuestro tiempo.

La primera era distinguible es la **Época de los Quarks (Quark Epoch — período de 10⁻¹² a 10⁻⁶ segundos después del Big Bang; la temperatura oscilaba entre 10¹⁵ y 10¹² K; quarks y gluones existían libremente como un plasma de quarks y gluones; las partículas producidas incluían quarks de todos los sabores —up, down, strange, charm, bottom y top— así como sus antiquarks correspondientes; al enfriarse, los quarks se confinaron irreversiblemente en hadrones mediante la fuerza nuclear fuerte; este confinamiento es permanente: los quarks libres nunca se observan en condiciones normales)**. En este período, la materia y la antimateria se producían en cantidades casi iguales, con una asimetría minúscula de una parte en un billón a favor de la materia —asimetría que resultó ser la diferencia entre la existencia del universo tal como lo conocemos y la aniquilación total.

Al enfriarse el plasma, los quarks se unieron en la **Época de los Hadrones (Hadron Epoch — período de 10⁻⁶ segundos a 1 segundo después del Big Bang; la temperatura cayó de 10¹² a 10¹⁰ K; quarks se combinaron para formar hadrones, principalmente bariones como protones (uud) y neutrones (udd); la mayor parte de los hadrones y antihadrones se aniquilaron mutuamente al enfriarse el universo; solo sobrevivió la fracción de bariones sin antibarión correspondiente —aproximadamente uno por cada 10⁹ fotones—; el exceso resultante de un barión por cada 10⁹ fotones es toda la materia ordinaria que existe hoy en el universo)**. En este punto, el universo contenía principalmente fotones, neutrinos, electrones y el exceso minúsculo de protones y neutrones que formaría todo lo que existe hoy.

A continuación llegó la **Época de los Leptones (Lepton Epoch — período de 1 segundo a 10 segundos después del Big Bang; temperatura entre 10¹⁰ y 10⁹ K; dominada por leptones —electrones, positrones y neutrinos—; los neutrinos se desacoplaron del resto de la materia al segundo uno, creando el Fondo Cósmico de Neutrinos que permea el universo hasta hoy pero que aún no ha sido detectado directamente debido a la extrema debilidad de la interacción de los neutrinos; los electrones y positrones se aniquilaron masivamente, dejando solo el exceso neto de electrones que se combinaría luego con los protones para formar átomos de hidrógeno)**. El universo era completamente opaco: los fotones chocaban continuamente con las partículas cargadas y no podían viajar libremente.

Entre los 3 y 20 minutos de vida del cosmos ocurrió la **Nucleosíntesis Primordial (Big Bang Nucleosynthesis — síntesis de los primeros núcleos atómicos; protones y neutrones se combinaron para formar núcleos de helio-4 (24-25% de la masa bariónica), deuterio, helio-3 y pequeñas cantidades de litio-7; la proporción protón:neutrón al inicio era 1:1 pero la desintegración del neutrón libre —con vida media de 15 minutos— redujo la proporción a 7:1 protones:neutrones antes de que comenzara la fusión; las predicciones de estas proporciones con tres familias de neutrinos coinciden con las observaciones al nivel del 1%)**. Estos núcleos ligeros fueron los ingredientes de todas las estrellas que después fabricarían el resto de los elementos.

**Casos de Estudio y Aplicaciones Reales**

La era más fascinante desde una perspectiva experimental es la Época de los Quarks, porque el LHC del CERN la recrea activamente. En el experimento ALICE —A Large Ion Collider Experiment— se hacen colisionar núcleos de plomo a velocidades del 99.99% de la velocidad de la luz. El resultado es un plasma de quarks y gluones que dura apenas 10⁻²³ segundos pero alcanza temperaturas de 5.5 × 10¹² K, más de 250,000 veces más caliente que el núcleo del Sol. Lo que los físicos han descubierto es sorprendente: este plasma se comporta casi como un líquido perfecto, sin viscosidad, no como el gas que se esperaba. Cada medición refina nuestro modelo de cómo evolucionó el universo en su primer microsegundo.

Los **neutrinos** son el legado más esquivo de la Época de los Leptones. Se produjeron en cantidades colosales durante el primer segundo y desde entonces atraviesan la materia prácticamente sin interactuar. Ahora mismo, 65,000 millones de neutrinos solares atraviesan cada centímetro cuadrado de tu cuerpo cada segundo sin dejar rastro. Los detectores de neutrinos enterrados en hielo antártico (IceCube) o en agua subterránea (Super-Kamiokande en Japón) son los instrumentos que nos permiten estudiar esta partícula fantasmal y, a través de ella, reconstruir las condiciones del universo primitivo.

**Conclusión Estratégica**

Las Eras de la Materia no son solo historia antigua del cosmos. Son la demostración de que el universo opera según leyes matemáticas precisas y consistentes a través del tiempo. Las mismas partículas y fuerzas que estructuraron el universo en sus primeros instantes son las que gobiernan los transistores de tu teléfono, los enlaces químicos de tus células y la luz de las pantallas que usas para aprender. Estudiar física de partículas, cosmología o química fundamental no es ejercicio teórico: es descifrar el manual de instrucciones de la realidad. Y ese manual, resultó, está escrito en el lenguaje de las matemáticas.

🔖 Bluebook v1 · Capítulo I, Sección 1.1.2 📐 NGSS: HS-PS1-8 — Develop models to illustrate changes in matter 📋 RENAC: EC009 · Física de Partículas y Cosmología""",

"1.1.3": """En el instante del Big Bang, el universo creó materia y antimateria en cantidades prácticamente iguales. Si la física fuera perfectamente simétrica entre ambas, toda la materia del universo se habría aniquilado con toda la antimateria produciendo únicamente fotones, y el universo que existe hoy —galaxias, planetas, vida— no existiría en absoluto. Y sin embargo, aquí estamos. La existencia del universo observable es prueba irrefutable de que algo rompió esa simetría. Encontrar qué es exactamente lo que la rompió es uno de los problemas más grandes de la física moderna, y tiene nombre: el **Problema de la Bariogénesis (Baryogenesis — el proceso hipotético por el cual se generó el exceso de materia sobre antimateria en el universo primitivo; Andrei Sakharov estableció en 1967 las tres condiciones necesarias para que ocurra: violación del número bariónico, violación de las simetrías C y CP, y alejamiento del equilibrio termodinámico; ningún modelo actual explica completamente el grado de asimetría observado —un barión por cada 10⁹ fotones — con los parámetros medidos en los experimentos actuales)**.

La **Antimateria (Antimatter — la contraparte de la materia ordinaria; cada partícula tiene su antipartícula correspondiente con la misma masa pero carga opuesta y otros números cuánticos invertidos; el positrón es el antielectrón, el antiprotón es el antiprotón; cuando materia y antimateria se encuentran, se aniquilan completamente convirtiendo su masa en energía pura según E=mc²; la aniquilación protón-antiprotón libera 1.877 GeV de energía en forma de rayos gamma; fue predicha por Paul Dirac en 1928 y el positrón fue descubierto por Carl Anderson en 1932 en rayos cósmicos)** no es ciencia ficción: es una realidad física producida diariamente en laboratorios de todo el mundo y, de hecho, dentro de tu propio cuerpo —el potasio-40 de tus huesos emite positrones continuamente durante su decaimiento radiactivo.

El mecanismo que permitiría explicar la asimetría es la **Violación CP (CP Violation — la asimetría en el comportamiento de la física bajo la combinación de la transformación de carga C —que intercambia partículas por antipartículas— y la inversión de paridad P —que refleja el sistema espacialmente; fue descubierta en 1964 por Cronin y Fitch en el decaimiento de los kaones, lo que les valió el Nobel de Física en 1980; el Modelo Estándar predice violación CP en los mesones B y K, y el experimento LHCb del CERN ha medido asimetrías en el decaimiento de bariones encantados; sin embargo, la magnitud de la violación CP conocida es insuficiente para explicar la totalidad de la asimetría materia-antimateria observada)**. Esta violación existe dentro del Modelo Estándar, pero en una cantidad demasiado pequeña para explicar por qué sobrevivió un barión por cada 10⁹ fotones. Debe existir física más allá del Modelo Estándar que amplifica este efecto.

La antimateria tiene una propiedad que la hace extremadamente difícil de estudiar: cuando toca la materia ordinaria, ambas se destruyen. Producir y contener antimateria requiere campos magnéticos y vacío extremo. En el experimento **ALPHA (ALPHA Experiment — Antihydrogen Laser Physics Apparatus, experimento del CERN que desde 2010 produce y atrapa átomos de antihidrógeno —un antiprotón orbitado por un positrón— en trampas magnéticas; en 2022 midió por primera vez cómo el antihidrógeno interactúa con la gravedad, confirmando que la antimateria cae hacia abajo como la materia ordinaria; el objetivo es medir el espectro de luz del antihidrógeno con alta precisión para detectar diferencias con el hidrógeno ordinario que revelarían violaciones de la simetría CPT)** del CERN, los físicos han logrado atrapar átomos de antihidrógeno durante períodos de varios minutos y medir sus propiedades con precisión sin precedentes. Hasta ahora, el antihidrógeno se comporta exactamente como el hidrógeno ordinario —lo que refuerza la simetría CPT pero no explica por qué existe el universo.

Un concepto clave relacionado es la **Simetría CPT (CPT Symmetry — el teorema fundamental de la teoría cuántica de campos que establece que las leyes de la física son invariantes bajo la combinación de las tres transformaciones: inversión de carga C, inversión de paridad P e inversión temporal T; fue demostrado por Lüders y Pauli en los años 1950; si la simetría CPT se viola, implicaría una profunda asimetría en las leyes fundamentales de la naturaleza; todos los experimentos hasta la fecha son consistentes con la conservación exacta de CPT con una precisión de una parte en 10¹⁸)**: si alguna vez se detectara una violación, sería el descubrimiento más revolucionario en la historia de la física.

**Casos de Estudio y Aplicaciones Reales**

La antimateria no es solo un objeto de estudio filosófico: tiene aplicaciones médicas reales y cotidianas. Los **escáneres PET (Positron Emission Tomography — tecnología de imagen médica que usa la emisión de positrones por isótopos radiactivos como el flúor-18; el positrón emitido se aniquila con un electrón tisular produciendo dos fotones gamma de 511 keV en direcciones opuestas; el escáner detecta estas parejas de fotones y reconstruye la distribución tridimensional del isótopo en el cuerpo; es la técnica de imagen funcional más sensible disponible, capaz de detectar tumores de milímetros con alta sensibilidad metabólica)** en hospitales de todo el mundo producen y detectan antimateria —positrones— de forma controlada para diagnosticar cáncer, estudiar el metabolismo cerebral y planificar tratamientos. Cada día, millones de pacientes se benefician de la física de antimateria sin saberlo.

El experimento LHCb en el CERN se especializa en medir violaciones CP en bariones y mesones con quark "b" (belleza). En 2020, LHCb anunció la observación directa de violación CP en bariones encantados por primera vez, añadiendo piezas al puzzle de la bariogénesis. La búsqueda continúa: entender por qué existe el universo material es literalmente la pregunta más fundamental de la física.

**Conclusión Estratégica**

El dilema de la antimateria nos recuerda que la existencia no es trivial. El universo que habitamos es el resultado de una asimetría de una parte por billón —una diferencia cuántica minúscula que escaló a 10⁸⁰ átomos de materia observable. Esta fragilidad de la existencia no es filosofía abstracta; es un problema de física cuantificable y resoluble. Las carreras en física de partículas, cosmología y física matemática tienen en la asimetría materia-antimateria uno de sus grandes objetivos. Y las tecnologías derivadas —escáneres PET, detectores de partículas, imanes superconductores del CERN— ya transforman la medicina y la ingeniería hoy.

🔖 Bluebook v1 · Capítulo I, Sección 1.1.3 📐 NGSS: HS-PS1-8 — Matter interactions and conservation 📋 RENAC: EC009 · Física de Partículas · Antimateria""",

"1.1.4": """Imagina que pudieras fotografiar el universo cuando tenía solo 380,000 años de edad —una fracción infinitesimal de sus 13,800 millones de años actuales— y que esa fotografía revelara con precisión el mapa de todas las semillas de las galaxias que existirían mil millones de años después. Eso es exactamente lo que es el **Fondo Cósmico de Microondas (Cosmic Microwave Background / CMB — la radiación electromagnética más antigua del universo, emitida hace 380,000 años cuando la temperatura cayó lo suficiente para que los electrones se combinaran con protones formando átomos neutros; en ese momento el universo se volvió transparente y los fotones pudieron viajar libremente; esos fotones, redshifteados por la expansión del universo durante 13,800 millones de años, se detectan hoy como microondas con una temperatura de exactamente 2.7255 K)**: la imagen del universo bebé congelada en el cielo en todas las direcciones.

El descubrimiento del CMB en 1965 fue completamente accidental. Los ingenieros Arno Penzias y Robert Wilson, trabajando en Bell Labs en Nueva Jersey con una antena de microondas de última generación, detectaron un ruido de fondo persistente e inexplicable que provenía por igual de todas las direcciones del cielo, a cualquier hora del día y en cualquier época del año. Inicialmente pensaron que era contaminación —incluso limpiaron los excrementos de palomas del interior de la antena— pero el ruido persistía. Ese "ruido" era la señal más importante de la cosmología del siglo XX: la huella térmica del Big Bang, predicha años antes por George Gamow y sus colaboradores. Penzias y Wilson ganaron el Nobel de Física en 1978 por el descubrimiento que ni siquiera buscaban.

El CMB puede describirse perfectamente por la **Radiación de Cuerpo Negro (Blackbody Radiation — la distribución espectral de la radiación emitida por un objeto en equilibrio térmico a una temperatura determinada; sigue la ley de Planck; el CMB es el cuerpo negro más perfecto medido en la naturaleza, con una temperatura de 2.7255 K y una desviación de la curva de cuerpo negro inferior a una parte en 10⁴; esta perfección confirma que el universo primitivo estaba en equilibrio termodinámico completo, condición necesaria para el modelo estándar cosmológico)**, y es el cuerpo negro más perfecto que se ha medido en la naturaleza. La desviación entre la radiación observada del CMB y la predicción teórica de cuerpo negro es inferior a una parte en diez mil, un nivel de precisión extraordinario que valida directamente el modelo del Big Bang.

Lo más rico científicamente no es la temperatura media del CMB, sino sus pequeñas variaciones. Las **Anisotropías del CMB (CMB Anisotropies — las variaciones minúsculas en la temperatura del CMB de una dirección a otra, del orden de ΔT/T ~ 10⁻⁵; estas fluctuaciones reflejan las inhomogeneidades cuánticas del universo primitivo amplificadas por la inflación cósmica; contienen información sobre la geometría del universo, la densidad de materia ordinaria y oscura, la energía oscura, el índice espectral de la inflación y la época de reionización; su análisis mediante la descomposición en armónicos esféricos —el espectro de potencias— ha establecido los parámetros cosmológicos con precisión del 1%)** son variaciones de temperatura de apenas una parte en cien mil, pero contienen prácticamente toda la información cosmológica fundamental del universo.

El análisis de estas anisotropías requiere satélites diseñados específicamente para mapearlas. El satélite **WMAP (Wilkinson Microwave Anisotropy Probe — misión de la NASA lanzada en 2001 que durante nueve años produjo mapas de alta resolución de las anisotropías del CMB; determinó que el universo tiene 13,772 ± 59 millones de años, que la geometría del universo es esencialmente plana con una precisión del 0.4%, y que está compuesto aproximadamente de 5% materia ordinaria, 27% materia oscura y 68% energía oscura)** y su sucesor **Planck (Planck Satellite — misión de la ESA que operó de 2009 a 2013; produjo el mapa más preciso de las anisotropías del CMB hasta la fecha con una resolución angular de 5 arcominutos; refinó los parámetros cosmológicos con una precisión del 1%; detectó señales de inflación cósmica y constrinó la masa de los neutrinos; sus resultados confirmaron el modelo ΛCDM como el modelo estándar cosmológico con una solidez sin precedentes)** han transformado la cosmología en una ciencia de precisión.

**Casos de Estudio y Aplicaciones Reales**

Una de las aplicaciones más poderosas del análisis del CMB es la determinación de la geometría del universo. Si el universo es curvo positivamente —como la superficie de una esfera— las anisotropías del CMB aparecerían en ángulos mayores de lo predicho por geometría plana; si es curvo negativamente, aparecerían en ángulos menores. El primer pico del espectro de potencias del CMB, medido por WMAP y Planck, aparece exactamente en el ángulo predicho para un universo plano, confirmando que la geometría del espacio-tiempo a gran escala es euclidiana con una precisión del 0.4%.

El CMB también es sensible a las **Oscilaciones Acústicas de Bariones (Baryon Acoustic Oscillations / BAO — ondas de sonido en el plasma primordial que quedaron congeladas cuando el universo se volvió transparente; dejaron una huella estadística en la distribución de galaxias como una escala preferida de separación de ~150 Megapársecs; actúan como una "regla estándar" para medir la expansión del universo a diferentes épocas; su detección en la distribución de galaxias en 2005 por los equipos de SDSS y 2dF fue confirmación independiente de la energía oscura)**, un reloj y una regla estándar grabados en la distribución de galaxias que permite medir la expansión del universo a lo largo de toda su historia. Esta herramienta es clave para estudiar la naturaleza de la energía oscura.

**Conclusión Estratégica**

El CMB es la prueba de que el universo tiene una historia accesible a la razón, y que esa historia puede reconstruirse con precisión extraordinaria. Para los estudiantes STEM, el CMB representa algo más: demuestra que los descubrimientos más transformadores frecuentemente llegan por accidente cuando mentes preparadas observan algo inesperado y tienen la disciplina intelectual para tomarlo en serio. Penzias y Wilson no buscaban el Big Bang; encontraron "ruido" y se preguntaron por qué. Esa actitud —la de no descartar lo inesperado— es la que define a los grandes científicos e ingenieros de cualquier generación.

🔖 Bluebook v1 · Capítulo I, Sección 1.1.4 📐 NGSS: HS-ESS1-2 — Evidence for the Big Bang Theory 📋 RENAC: EC009 · Cosmología · CMB y Expansión del Universo"""
}

with open('/Users/yepz/JSweb/data/modules.json', 'r') as f:
    data = json.load(f)

count = 0
for chapter in data['chapters']:
    for module in chapter['modules']:
        if module['id'] in updates:
            module['fullText'] = updates[module['id']]
            count += 1

with open('/Users/yepz/JSweb/data/modules.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Updated {count} modules")
for mid, text in updates.items():
    w = len(text.split())
    print(f"  {mid}: {w} words / {len(text)} chars")
