import json

updates = {
"1.1.11": """En los últimos 540 millones de años, la vida compleja ha sido casi completamente extinguida cinco veces. No una, no dos: cinco. Cada una de estas catástrofes, conocidas colectivamente como las **Cinco Grandes Extinciones (The Big Five Mass Extinctions — los cinco eventos de extinción masiva del registro fósil del Fanerozoico en los que desapareció más del 40% de los géneros marinos y terrestres; en orden cronológico: Ordovícico-Silúrico (hace 443 Ma), Devónico tardío (374 Ma), Pérmico-Triásico (252 Ma, la mayor de todas), Triásico-Jurásico (201 Ma) y Cretácico-Paleógeno (66 Ma); su documentación fue sistematizada por Jack Sepkoski y David Raup en 1982 mediante análisis estadístico de las familias de organismos marinos en el registro fósil)**, remodeló el árbol de la vida de manera tan radical que el mundo después de cada evento era irreconocible comparado con el mundo antes. Y la más devastadora de todas ocurrió hace 252 millones de años, eliminando el 96% de todas las especies marinas y el 70% de las terrestres en lo que los paleontólogos llaman simplemente "el Gran Morir".

La historia de las extinciones masivas no es solo un catálogo de tragedias biológicas. Es, fundamentalmente, la historia de cómo los sistemas complejos colapsan y se reorganizan. Cada extinción fue seguida por una explosión evolutiva: los supervivientes, liberados de la competencia que habían enfrentado durante millones de años, radiaron rápidamente en nuevas formas y nichos ecológicos. Los mamíferos dominamos la Tierra no porque seamos superiores a los dinosaurios, sino porque una roca del espacio tuvo la mala —o buena— fortuna de impactar el planeta exactamente cuando y donde lo hizo. La contingencia histórica, no la superioridad biológica, determina qué linajes sobreviven.

La extinción más estudiada después del K-Pg es la **Extinción del Pérmico-Triásico (Permian-Triassic Extinction / "The Great Dying" — la mayor extinción masiva del registro fósil, hace 252 millones de años; eliminó el 96% de las especies marinas y el 70% de las terrestres en un período de entre 60,000 y 200,000 años; las causas principales fueron las erupciones volcánicas masivas de las Trampas Siberianas —uno de los mayores episodios de volcanismo continental— que liberaron enormes cantidades de CO₂, SO₂ y metano; provocaron un calentamiento global catastrófico, acidificación oceánica, anoxia marina y colapso de las cadenas alimentarias; la recuperación ecológica tardó entre 5 y 10 millones de años)**: el "Gran Morir". Las erupciones volcánicas de las **Trampas Siberianas (Siberian Traps — la mayor provincia ígnea conocida, cubriendo más de 7 millones de km² del actual territorio de Siberia; las erupciones ocurrieron en intervalos de 300,000 años hace 252 Ma; liberaron más de 3 millones de km³ de basalto y gases volcánicos incluyendo CO₂, SO₂ y metano de carbón metamorfoseado; el calentamiento y la acidificación oceánica resultantes colapsal los ecosistemas marinos primero y después los terrestres)** liberaron tanto CO₂ y SO₂ que transformaron el clima del planeta de forma irreversible durante millones de años.

La **Extinción del Devónico Tardío (Late Devonian Extinction — serie de eventos de extinción entre 375 y 359 Ma que eliminaron entre el 70 y el 82% de las especies; fue especialmente devastadora para los arrecifes de coral y los peces sin mandíbula; posibles causas incluyen enfriamiento global por expansión terrestre de plantas que extrajeron CO₂, anoxia oceánica por eutrofización de los mares con nutrientes de suelos forestales recientemente desarrollados, e impactos de asteroides menores; su carácter múltiple y en pulsos la hace más compleja de interpretar que las extinciones de causa única)** coincidió con la proliferación de las primeras plantas terrestres vasculares que, al crear suelos profundos, inyectaron nutrientes masivos a los océanos, causando proliferación de algas, agotamiento del oxígeno marino y asfixia de los ecosistemas marinos.

La **Extinción del Triásico-Jurásico (Triassic-Jurassic Extinction — hace 201 Ma, eliminó el 76% de las especies y marcó el fin del Triásico; causada probablemente por el volcanismo masivo de la Provincia Magmática del Atlántico Central (CAMP), que acompañó la separación de Pangea; la extinción eliminó a los grandes crurotarsos —parientes de los cocodrilos que dominaban los ecosistemas terrestres del Triásico— liberando los nichos ecológicos que los dinosaurios ocuparon para dominar el Jurásico y Cretácico)** fue la que abrió la puerta al dominio de los dinosaurios, al eliminar a sus principales competidores terrestres —los crurotarsos, parientes de los cocodrilos— en otra ronda de volcanismo masivo.

**Casos de Estudio y Aplicaciones Reales**

La ciencia de las extinciones masivas tiene una relevancia urgente y práctica: vivimos actualmente en lo que muchos biólogos llaman la **Sexta Extinción (Sixth Mass Extinction / Holocene Extinction — la extinción en curso causada por las actividades humanas; las tasas actuales de extinción de especies se estiman entre 100 y 1,000 veces superiores a las tasas de fondo natural; las causas incluyen destrucción de hábitat, cambio climático, contaminación, sobreexplotación y especies invasoras; a diferencia de las cinco extinciones anteriores, ocurre en siglos no en millones de años; fue documentada extensamente por Elizabeth Kolbert en su libro "La sexta extinción" —Premio Pulitzer 2015)**: una extinción biológica causada por actividades humanas que elimina especies a tasas 100-1,000 veces superiores a las de fondo natural. Los corales, los anfibios, los grandes mamíferos y las aves experimentan declives poblacionales que en el registro fósil se llamarían extinción masiva. La diferencia con las extinciones anteriores es que esta la estamos causando nosotros —y potencialmente podemos frenarla.

El análisis geoquímico de los límites de extinción en las rocas permite identificar las "huellas dactilares" de sus causas: el iridio del K-Pg evidencia el impacto de asteroides, las isotopías de carbono del P-T evidencian inyección masiva de carbono volcánico, los ciclos de anoxia del Devónico se leen en los sedimentos negros anóxicos. Esta "geoquímica de extinciones" es una de las herramientas más poderosas de la geología moderna.

**Conclusión Estratégica**

Las extinciones masivas demuestran que los sistemas ecológicos, por complejos y robustos que parezcan, tienen umbrales de colapso. Cruzarlos —por volcanismo, impacto de asteroides o cambio climático acelerado— produce consecuencias que se miden en millones de años de recuperación. Esta lección tiene una urgencia inmediata para nuestra civilización. Los biólogos de conservación, los geocientíficos, los climatólogos y los ingenieros ambientales que estudien estas extinciones pasadas son quienes mejor equipados están para comprender —y potencialmente prevenir— la magnitud de la crisis ecológica presente.

🔖 Bluebook v1 · Capítulo I, Sección 1.1.11 📐 NGSS: HS-LS4-1 — Fossil evidence for evolution and extinction 📋 RENAC: EC009 · Paleontología · Extinciones y Evolución""",

"1.1.12": """El 66 de los 100 metros de la historia del universo representan la era de los dinosaurios. Y el metro final —los últimos 66 millones de años desde su extinción— fue posible gracias a una roca que viajó desde el cinturón de asteroides a velocidad de 20 kilómetros por segundo y chocó con la Tierra en lo que hoy es la Península de Yucatán, México. El **Impacto de Chicxulub (Chicxulub Impactor — el asteroide o cometa de entre 10 y 15 kilómetros de diámetro que impactó la Tierra hace 66.038 millones de años en el límite K-Pg; dejó un cráter de 180 kilómetros de diámetro y 20 km de profundidad centrado en la costa norte de Yucatán, México; fue descubierto en 1978 por Walter Álvarez y sus colaboradores mediante el análisis de anomalías gravimétricas; el nombre proviene del pueblo maya cercano al epicentro; es el tercer cráter de impacto más grande conocido en la Tierra)** es el evento individual más estudiado en la historia de la geología, y la forma en que fue descubierto es uno de los triunfos más bellos del razonamiento científico interdisciplinar del siglo XX.

Todo comenzó con una pregunta geológica aparentemente menor. A principios de los años 1970, el geólogo Walter Álvarez estudiaba rocas en Gubbio, Italia, y encontró algo perturbador: entre las rocas del Cretácico —llenas de fósiles— y las del Paleógeno —con una biodiversidad radicalmente diferente— había una delgada capa de arcilla de apenas un centímetro de espesor donde los fósiles simplemente desaparecían. Esta capa, conocida como el **Límite K-Pg (K-Pg Boundary / Cretaceous-Paleogene Boundary — la línea geológica que marca la extinción masiva de hace 66 Ma; K viene del alemán "Kreide" —Cretácico— y Pg de Paleógeno; se reconoce en el registro sedimentario de todo el mundo por una capa de arcilla enriquecida en iridio, esférulas de impacto fundidas —vidrio de impacto—, cuarzo con características de choque y hollín que evidencia incendios globales; fue el límite geológico más estudiado del siglo XX)**, existe en prácticamente cada rincón del planeta donde se depositaron sedimentos de esa época.

El padre de Walter, el físico Nobel Luis Álvarez, sugirió medir la concentración de **Iridio (Iridium — elemento del grupo del platino con número atómico 77; es extremadamente raro en la corteza terrestre —unas 0.001 partes por billón— porque se hundió al núcleo terrestre durante la diferenciación planetaria; los asteroides y meteoritos tienen concentraciones de iridio entre 10,000 y 100,000 veces mayores que la corteza; por esto, un enriquecimiento en iridio en una capa sedimentaria es evidencia directa de un impacto extraterrestre; la anomalía de iridio del límite K-Pg —primero detectada en Gubbio en 1980— alcanza hasta 160 partes por billón en algunos sitios, frente a las 0.001 normales)** en la arcilla del límite. Encontraron niveles 160 veces por encima del fondo normal de la corteza terrestre, pero consistentes con la concentración que tendría el polvo de un asteroide pulverizado y distribuido globalmente. Esta fue la primera evidencia de la hipótesis del impacto, publicada en 1980 en Science por el equipo Álvarez. En el mismo número de la revista, científicos de Berkeley publicaron mediciones similares en capas K-Pg de Dinamarca. El consenso científico tardó una década en consolidarse, pero hoy la evidencia es abrumadora e irrefutable.

La energía liberada en el impacto fue de aproximadamente **10²⁴ julios**, equivalente a 100 millones de bombas de hidrógeno detonadas simultáneamente. El impacto vaporizó inmediatamente rocas a miles de kilómetros cuadrados, lanzó material al espacio —que regresó calentando la atmósfera globalmente— e inició un **Invierno de Impacto (Impact Winter — el enfriamiento climático global causado por la inyección masiva de polvo, hollín y aerosoles de azufre en la estratosfera tras un impacto masivo; estas partículas bloquearon la luz solar durante meses a años, reduciendo la fotosíntesis global; se estima que las temperaturas globales cayeron entre 10 y 15°C durante varios años; este colapso de la cadena alimentaria basada en la fotosíntesis fue la causa directa de la extinción de los dinosaurios no avianos y de las tres cuartas partes de las especies)** que duró años y colapso las cadenas alimentarias fotosintéticas. Los dinosaurios no avianos —dominantes durante 165 millones de años— se extinguieron en geológicamente un instante. Los mamíferos pequeños, adaptados a vida subterránea y a dietas oportunistas, sobrevivieron. Y de esos sobrevivientes, hace 66 millones de años, surgimos nosotros.

**Casos de Estudio y Aplicaciones Reales**

En 2016, la **Misión de Perforación de Chicxulub (Chicxulub Drilling Project — expedición científica del IODP/ICDP que perforó el pico de anillo del cráter de Chicxulub en el Golfo de México hasta 1,334 metros de profundidad; recuperó núcleos de roca que muestran las rocas de granito brechadas y fundidas del impacto, los primeros fósiles que reaparecieron después de la extinción —bacterias azufrosas que florecieron en los años inmediatamente posteriores al impacto— y evidencia de que el océano recolonizó el cráter en miles de años, no millones)** perforó directamente en el cráter y extrajo núcleos de roca que muestran los primeros organismos que recolonizaron el área: bacterias extremófilas que florecieron en las aguas calientes del cráter recién formado en los años y décadas posteriores al impacto. Es, literalmente, el registro de cómo la vida volvió a comenzar.

La **Defensa Planetaria (Planetary Defense — el campo interdisciplinar dedicado a detectar, caracterizar y potencialmente desviar objetos near-Earth que podrían representar una amenaza de impacto; la NASA opera el programa NEO —Near Earth Objects— que ha catalogado más del 95% de los objetos mayores de 1 km; la misión DART —Double Asteroid Redirection Test— de 2022 impactó exitosamente el asteroide Dimorphos y alteró su período orbital en 33 minutos, la primera demostración práctica de la deflexión de asteroides)** es la consecuencia directa del estudio del impacto de Chicxulub. La misión DART de la NASA, que en 2022 impactó el asteroide Dimorphos y alteró exitosamente su órbita, es la primera demostración práctica de que podemos proteger la Tierra de futuros impactos.

**Conclusión Estratégica**

El impacto de Chicxulub nos enseña que la historia de la vida en la Tierra es contingente: dependiente de eventos improbables y catastróficos que nadie predijo. Nos enseña también que la ciencia interdisciplinar —un geólogo, un físico nuclear, un geoquímico trabajando juntos— puede resolver misterios que ninguna disciplina podría resolver sola. Y nos recuerda que somos la primera especie en la historia de la Tierra con la capacidad tecnológica de comprender la amenaza de los impactos y, potencialmente, hacer algo al respecto. Esa es la promesa de las carreras STEM aplicadas a la defensa planetaria, la geología, la paleontología y la astrofísica.

🔖 Bluebook v1 · Capítulo I, Sección 1.1.12 📐 NGSS: HS-ESS1-6 · HS-LS4-1 — Catastrophic events and mass extinction 📋 RENAC: EC009 · Geociencias · Impactos Cósmicos y Extinción K-Pg""",

"1.2.2": """Uno de los aspectos más contraintuitivos de la física moderna es la idea de que el tiempo no transcurre a la misma velocidad para todos los observadores. No es una ilusión perceptual ni una metáfora filosófica: es un hecho físico medido con relojes atómicos en experimentos reales. Un reloj que viaja rápido marcha más despacio que uno en reposo. Un reloj cerca de un objeto masivo —como la Tierra— marcha más despacio que uno lejos de él. Este fenómeno se llama **Dilatación Temporal (Time Dilation — el retraso del tiempo medido en un sistema de referencia en movimiento relativo o en un campo gravitacional más intenso, comparado con un sistema en reposo o en campo gravitacional más débil; predicho por la Teoría Especial de la Relatividad de Einstein en 1905 y confirmado experimentalmente en múltiples ocasiones; no es un efecto sobre la percepción del tiempo sino una propiedad fundamental del espacio-tiempo que tiene consecuencias técnicas reales en sistemas como el GPS)**, y sus consecuencias van desde la paradoja del gemelo hasta los sistemas de navegación por satélite que usas en tu teléfono cada día.

La dilatación temporal es una consecuencia directa de uno de los postulados más radicales que cualquier científico ha propuesto: la velocidad de la luz es la misma para todos los observadores, independientemente de su movimiento relativo. Si esto es verdad —y experimentos como el de Michelson-Morley en 1887 demostraron que sí lo es— entonces el tiempo y el espacio no pueden ser absolutos. Al contrario: el tiempo y el espacio son aspectos de una misma entidad —el espacio-tiempo— que se curvea y estira según el movimiento y la masa.

La forma matemática de la dilatación temporal por velocidad viene dada por el **Factor de Lorentz (Lorentz Factor — el factor γ = 1/√(1-v²/c²) que aparece en todas las transformaciones de la Relatividad Especial; determina cuánto se dilata el tiempo, se contrae el espacio y aumenta la masa relativista en función de la velocidad v como fracción de la velocidad de la luz c; para velocidades cotidianas (v << c) γ ≈ 1 y los efectos relativistas son imperceptibles; para v = 0.99c, γ ≈ 7.09, lo que significa que el tiempo transcurre 7 veces más lento; para v = 0.9999c, γ ≈ 70.7)**. A velocidades cotidianas —un avión vuela a 0.0000003c— el factor de Lorentz es prácticamente uno y el efecto es imperceptible. Pero a velocidades cercanas a la de la luz, el tiempo se dilata dramáticamente.

La **Paradoja del Gemelo (Twin Paradox — experimento mental en el que un gemelo viaja en cohete a velocidades relativistas y regresa a la Tierra más joven que su hermano; no es una verdadera paradoja porque la situación no es simétrica —el gemelo viajero experimenta aceleración al invertir su rumbo, rompiendo la simetría; el gemelo viajero habrá envejecido menos en la misma medida que su reloj fue más lento; fue confirmado experimentalmente por el experimento Hafele-Keating en 1971 con relojes atómicos en aviones)** ilustra este efecto de forma dramática: si viajas durante un año a 99.5% de la velocidad de la luz y regresas, habrán pasado 10 años en la Tierra. Has viajado al futuro en un sentido real y físico. Este no es un efecto sobre la percepción; es un efecto sobre el tiempo físico real.

La dilatación temporal gravitacional —predicha por la Relatividad General— funciona de manera complementaria. Un reloj en el suelo —más cerca del centro gravitacional de la Tierra— marcha más despacio que uno en órbita. La diferencia cuantitativa la describe el **Potencial Gravitacional (Gravitational Time Dilation — el retraso del tiempo en un campo gravitacional más intenso, descrito por la ecuación Δt' = Δt √(1-2GM/rc²); cuanto más cerca del centro de un objeto masivo, más lento transcurre el tiempo; en la superficie de la Tierra, los relojes van aproximadamente 6.97 microsegundos más lentos por día que los relojes en el infinito gravitacional; este efecto, aunque pequeño, es suficiente para desplazar la posición calculada por GPS en 10 km al día si no se corrige)**: cuanto más profundo en el pozo gravitacional, más lento el tiempo.

**Casos de Estudio y Aplicaciones Reales**

El experimento de **Hafele y Keating (Hafele-Keating Experiment — experimento realizado en 1971 por Joseph Hafele y Richard Keating; pusieron relojes atómicos de cesio en aviones comerciales volando en direcciones opuestas alrededor del mundo y compararon con relojes en tierra; los resultados confirmaron la dilatación temporal relativista especial y gravitacional con una precisión del 10%; los relojes que viajaron hacia el este (en la dirección de la rotación terrestre, por lo tanto más rápidos respecto al Earth's center) retrasaron, y los que volaron hacia el oeste se adelantaron, exactamente como predecía la teoría)** fue la primera confirmación directa de la dilatación temporal en laboratorios ordinarios: relojes atómicos en aviones, comparados con relojes en tierra, mostraron exactamente la diferencia predicha por la Relatividad Especial y General.

El sistema GPS —que usas cuando navigas en tu coche o buscas una ubicación en tu teléfono— es el ejemplo más cotidiano de ingeniería que depende críticamente de la corrección de la dilatación temporal. Los satélites GPS orbitan a 20,200 km de altitud y viajan a 3.87 km/s. Debido a la dilatación temporal especial (por su velocidad), sus relojes se atrasan 7.2 microsegundos por día. Debido a la dilatación temporal gravitacional (por estar más lejos del centro terrestre), se adelantan 45.9 microsegundos por día. El efecto neto es un adelanto de 38.7 microsegundos diarios que, sin corrección, acumularía un error de 11 kilómetros por día en las posiciones calculadas. Cada GPS del mundo incorpora correcciones relativistas de tiempo en tiempo real; sin la Relatividad General y Especial de Einstein, el GPS sería inutilizable.

**Conclusión Estratégica**

La dilatación temporal no es solo un concepto fascinante para debatir en clase de física. Es una tecnología activa sobre la que se basan sistemas de posicionamiento, comunicaciones satelitales y experimentos de física de alta energía. Los futuros ingenieros aeroespaciales que diseñen naves interplanetarias deberán calcular efectos relativistas en las comunicaciones; los diseñadores de sistemas de navegación necesitarán entender las correcciones relativistas al nivel de nanosegundos. Y en física de partículas, la dilatación temporal es la razón por la que los muones cósmicos —creados en la atmósfera superior— llegan al suelo antes de desintegrarse, cuando su vida media sin dilatación les impediría hacerlo. El tiempo es relativo. Esa relatividad tiene consecuencias de ingeniería reales.

🔖 Bluebook v1 · Capítulo I, Sección 1.2.2 📐 NGSS: HS-PS2-4 — Forces and fields · Relativistic effects 📋 RENAC: EC009 · Física Moderna · Relatividad Especial y Dilatación Temporal"""
}

with open('/Users/yepz/JSweb/data/modules.json', 'r') as f:
    data = json.load(f)

count = 0
for chapter in data['chapters']:
    for module in chapter['modules']:
        if module['id'] in updates:
            module['fullText'] = updates[module['id']]
            count += 1

with open('/Users/yepz/JSweb/data/modules.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Updated {count} modules")
for mid, text in updates.items():
    w = len(text.split())
    print(f"  {mid}: {w} words / {len(text)} chars")
