import json

updates = {
"1.3.2": """Si pudieras alejarte de la Tierra lo suficiente como para que nuestro planeta se viera solo como un pequeño punto de luz contra la inmensidad del espacio, entenderías por qué el astrónomo Carl Sagan llamó a nuestro mundo el **Pálido Punto Azul (Pale Blue Dot — nombre dado a una fotografía de la Tierra tomada por la sonda Voyager 1 en 1990 desde una distancia récord de 6,000 millones de kilómetros; en la imagen, la Tierra aparece como un minúsculo punto de apenas 0.12 píxeles de tamaño, suspendida en un haz de luz solar dispersada por la cámara; la foto fue solicitada por Carl Sagan, quien la utilizó como metáfora de la pequeñez humana en la inmensidad cósmica y la necesidad de preservar nuestro único hogar)**. Esta perspectiva no es solo una curiosidad fotográfica; es una de las lecciones más profundas de humildad y responsabilidad que la ciencia nos ha entregado.

La importancia del Pálido Punto Azul radica en que rompe nuestra ilusión de centralidad. Durante milenios, los seres humanos creímos que éramos el centro del universo. La astronomía moderna, culminando en imágenes como esta, nos ha demostrado que habitamos un rincón minúsculo de una galaxia ordinaria entre billones de otras. Esta "degradación" de nuestra posición física es lo que permite una verdadera apreciación de la fragilidad de nuestro ecosistema. En el espacio infinito, no hay nadie que venga a salvarnos de nosotros mismos; somos los únicos guardianes de esta pequeña mota de polvo.

La fotografía fue capturada por la sonda **Voyager 1 (Voyager 1 — sonda espacial de la NASA lanzada en 1977 con el objetivo inicial de explorar Júpiter y Saturno; tras completar su misión primaria, continuó hacia el espacio interestelar; el 14 de febrero de 1990, a petición de Carl Sagan, giró su cámara una última vez para retratar los planetas del sistema solar desde el borde; es el objeto fabricado por el hombre que más lejos ha llegado del Sol, cruzando la heliopausa en 2012; actualmente viaja a 17 km/s en el espacio interestelar)**. A esa distancia, la luz tarda más de 5 horas y media en llegar a la Tierra. La cámara de la Voyager, diseñada en los años 70, capturó una realidad que cambió nuestra filosofía para siempre.

Un concepto clave en esta perspectiva es la **Perspectiva Cósmica (Cosmic Perspective — marco mental que reconoce la inmensidad del espacio y el tiempo y la posición relativa de la humanidad; busca trascender los conflictos locales y temporales al reconocer que compartimos un único y frágil hogar; ha sido promovida por científicos como Carl Sagan y Neil deGrasse Tyson como una herramienta para fomentar la colaboración global y la protección ambiental)**. Esta perspectiva nos enseña que las fronteras nacionales, los conflictos ideológicos y las diferencias culturales parecen insignificantes cuando se ven desde la distancia de los planetas exteriores.

La imagen también es un testimonio del **Efecto de Perspectiva (Overview Effect — cambio cognitivo en la conciencia reportado por astronautas durante los vuelos espaciales al ver la Tierra desde la órbita o la Luna; se describe como un sentimiento de interconexión global, una comprensión de la fragilidad de la vida y una ausencia de fronteras nacionales; este cambio psicológico ha motivado a muchos astronautas a convertirse en activistas ambientales y defensores de la paz mundial tras su regreso a la Tierra)**. Aunque solo unos pocos cientos de personas han experimentado esto directamente, fotografías como el Pálido Punto Azul nos permiten a todos participar de esta revelación.

**Casos de Estudio y Aplicaciones Reales**

La filosofía del Pálido Punto Azul ha inspirado movimientos ambientales globales. La primera imagen de la Tierra completa —la "Canica Azul" tomada por el Apolo 17 en 1972— es citada frecuentemente como el catalizador del moderno movimiento ecologista y la creación del primer Día de la Tierra. El Pálido Punto Azul llevó esto un paso más allá al mostrar no solo la belleza de la Tierra, sino su absoluta soledad en el vacío.

En la actualidad, esta perspectiva se aplica en la **Astrobiología (Astrobiology — campo científico interdisciplinar que estudia el origen, evolución y distribución de la vida en el universo; utiliza la Tierra como único ejemplo conocido para buscar biosignaturas en otros planetas y lunas; la búsqueda de "exotierras" —planetas de tamaño y temperatura similares a la Tierra alrededor de otras estrellas— es uno de sus objetivos principales; misiones como el telescopio Kepler y el TESS han descubierto miles de exoplanetas, pero ninguno tan hospitalario como nuestro pálido punto azul)**. Cada vez que encontramos un nuevo exoplaneta, comparamos sus condiciones con las de la Tierra, recordándonos que, hasta donde sabemos, este es el único lugar donde la vida ha flourishado.

**Conclusión Estratégica**

El Pálido Punto Azul es el recordatorio definitivo de nuestra responsabilidad hacia el futuro. En un universo de billones de galaxias, la Tierra es nuestro único bote salvavidas. Para los estudiantes STEM, esta perspectiva añade una dimensión ética a su trabajo: la ciencia y la tecnología no son solo herramientas para el progreso económico, sino los medios para preservar la habitabilidad de nuestro planeta. Entender nuestra posición en el cosmos no nos hace pequeños; nos hace responsables de lo que ocurra en este pequeño escenario que llamamos hogar.

🔖 Bluebook v1 · Capítulo I, Sección 1.3.2 📐 NGSS: HS-ESS1-3 — Stellar evolution and planetary systems 📋 RENAC: EC009 · Astronomía · Perspectiva Cósmica""",

"1.3.3": """Si alguna vez miramos hacia el cielo nocturno y nos preguntamos cuál es la estrella más cercana a nosotros, la respuesta es un sistema complejo y fascinante llamado **Alfa Centauri (Alpha Centauri — el sistema estelar más cercano al Sistema Solar, situado a una distancia de 4.37 años-luz; es un sistema triple compuesto por un par binario central —Alfa Centauri A y B— y una enana roja más distante llamada Próxima Centauri; Alfa Centauri A es una estrella de tipo espectral G2V muy similar al Sol, mientras que Alfa Centauri B es algo más pequeña y fría; es un objetivo prioritario para la futura exploración interestelar y la búsqueda de vida exoplanetaria)**. A "solo" 4.37 años-luz de distancia, este sistema es nuestro vecino galáctico más próximo y el primer objetivo lógico para cualquier futura misión interestelar de la humanidad.

Entender Alfa Centauri es entender la diversidad de las estrellas. Mientras que nuestro Sol es una estrella solitaria, la mayoría de las estrellas en nuestra galaxia viven en sistemas múltiples. Alfa Centauri nos muestra cómo estrellas similares al Sol pueden coexistir en órbitas complejas, y cómo incluso en estos entornos dinámicos pueden existir planetas que, en teoría, podrían albergar vida. El sistema es un laboratorio natural para probar nuestras teorías sobre la formación de sistemas solares y la habitabilidad planetaria.

El sistema está dominado por dos estrellas principales, **Alfa Centauri A y B**, que orbitan un centro de masas común cada 80 años. La tercera estrella, **Próxima Centauri (Proxima Centauri — estrella enana roja de tipo M5.5V que orbita el par central Alfa Centauri AB a una distancia de 13,000 unidades astronómicas; es actualmente la estrella más cercana al Sol, a 4.246 años-luz; a pesar de su cercanía, es demasiado tenue para ser vista a simple vista; en 2016 se descubrió un planeta de masa terrestre, Próxima b, orbitando en su zona habitable, lo que la convirtió en el foco principal de la astrobiología interestelar)**, es mucho más pequeña y tenue, y se encuentra algo más cerca de nosotros.

En 2016, el descubrimiento de **Próxima b (Proxima Centauri b — exoplaneta que orbita a Próxima Centauri dentro de su zona de habitabilidad; tiene una masa mínima de 1.17 masas terrestres y un período orbital de solo 11.2 días; debido a su cercanía a la enana roja, es probable que esté en rotación sincrónica —mostrando siempre la misma cara a su estrella— y expuesto a intensas llamaradas estelares de rayos X y UV; su habitabilidad real sigue siendo objeto de intenso debate científico)** cambió nuestra perspectiva sobre el sistema. Es un planeta de tamaño similar a la Tierra orbitando en la zona habitable de su estrella. Aunque las condiciones allí son extremas debido a las llamaradas solares de la enana roja, es el planeta habitable más cercano que jamás encontraremos.

Llegar a Alfa Centauri representa el mayor desafío de ingeniería de la historia. Con la tecnología actual (como las sondas Voyager), el viaje tardaría 75,000 años. Por eso, proyectos como **Breakthrough Starshot (Breakthrough Starshot — iniciativa de investigación y de ingeniería de 100 millones de dólares para demostrar la viabilidad del uso de velas solares impulsadas por láser para enviar nanosondas a Alfa Centauri; el objetivo es alcanzar el 20% de la velocidad de la luz, lo que permitiría realizar el viaje en solo 20 años; el proyecto fue anunciado en 2016 por Yuri Milner, Stephen Hawking y Mark Zuckerberg)** buscan usar velas solares impulsadas por potentes láseres terrestres para acelerar pequeñas sondas al 20% de la velocidad de la luz.

**Casos de Estudio y Aplicaciones Reales**

El estudio de Alfa Centauri ha impulsado el desarrollo de técnicas de **Velocidad Radial (Radial Velocity Method — técnica de detección de exoplanetas que mide los pequeños cambios en el espectro de luz de una estrella causados por el tirón gravitacional de un planeta en órbita; permite determinar la masa mínima del planeta y su período orbital; fue la técnica utilizada para descubrir Próxima b y sigue siendo una de las herramientas más precisas de la astronomía moderna)** de alta precisión. Los instrumentos instalados en telescopios como el VLT (Very Large Telescope) en Chile han alcanzado precisiones que permiten detectar movimientos estelares de apenas unos centímetros por segundo, permitiendo encontrar planetas cada vez más pequeños.

La exploración de Alfa Centauri también motiva la investigación en **Propulsión Interestelar (Interstellar Propulsion — campo de la ingeniería aeroespacial dedicado al desarrollo de sistemas de propulsión capaces de realizar viajes entre estrellas en tiempos humanos; incluye conceptos como la propulsión por pulsos nucleares, motores de antimateria y velas láser; el desafío principal es la enorme cantidad de energía necesaria para acelerar naves a fracciones significativas de la velocidad de la luz)**. Aunque hoy parece ciencia ficción, los principios físicos que se están probando para Breakthrough Starshot podrían ser la base de la tecnología espacial del siglo XXII.

**Conclusión Estratégica**

Alfa Centauri es la frontera final de nuestra generación. No es solo una estrella en el cielo; es el destino que define la ambición de la humanidad como especie interestelar. Para los estudiantes STEM, este sistema representa la integración de la astrofísica, la ingeniería aeroespacial y la ciencia de materiales. Entender a nuestro vecino más cercano es el primer paso para salir de nuestra cuna solar y comenzar la verdadera exploración de la galaxia.

🔖 Bluebook v1 · Capítulo I, Sección 1.3.3 📐 NGSS: HS-ESS1-3 — Stellar life cycles and systems 📋 RENAC: EC009 · Astronomía · Sistemas Estelares Próximos""",

"1.3.4": """A 2.5 millones de años-luz de nosotros, una galaxia gigante se acerca a la Vía Láctea a 110 kilómetros por segundo. Dentro de unos 4,000 millones de años, estas dos ciudades estelares colisionarán en un evento de escala galáctica que dará origen a una nueva estructura colosal: **Lactómeda (Milkomeda — nombre dado a la galaxia elíptica gigante resultante de la futura colisión y fusión entre la Vía Láctea y la galaxia de Andrómeda (M31); el término fue popularizado por los astrofísicos para describir el destino final de nuestro vecindario galáctico; aunque las galaxias colisionarán, la probabilidad de que estrellas individuales choquen es casi nula debido a las enormes distancias entre ellas; el proceso de fusión durará miles de millones de años y remodelará completamente el cielo nocturno)**. Este evento marcará el fin de nuestra galaxia tal como la conocemos y el inicio de una nueva era cósmica.

La colisión entre la Vía Láctea y Andrómeda es un ejemplo perfecto de cómo la gravedad organiza el universo a gran escala. Aunque el universo se está expandiendo, las galaxias que están cerca unas de otras sienten una atracción gravitacional que supera la expansión. Andrómeda y la Vía Láctea son los dos miembros más grandes del **Grupo Local (Local Group — el pequeño cúmulo de galaxias que incluye a la Vía Láctea, Andrómeda, la galaxia del Triángulo y unas 50 galaxias enanas; se extiende por unos 10 millones de años-luz; las galaxias del Grupo Local están ligadas gravitacionalmente y eventualmente se fusionarán en una sola estructura; es nuestro vecindario inmediato en la Red Cósmica)**, y su destino común es unirse.

El proceso de fusión no será una explosión violenta, sino una danza gravitacional lenta y majestuosa. Las galaxias se atravesarán mutuamente varias veces, estirando sus brazos espirales en largas colas de marea. Este proceso se llama **Canibalismo Galáctico (Galactic Cannibalism — proceso por el cual una galaxia grande, a través de interacciones gravitacionales de marea, se fusiona con otra galaxia, resultando en un objeto galáctico más grande; las galaxias masivas en los centros de los cúmulos suelen crecer mediante este proceso; Andrómeda ya muestra signos de haber absorbido galaxias menores en su pasado, y nuestra Vía Láctea está actualmente absorbiendo galaxias enanas como la de Sagitario)**, aunque en el caso de Andrómeda y la Vía Láctea, es más una fusión entre iguales.

Un efecto secundario importante de esta colisión será el aumento drástico de la **Formación Estelar (Star Formation — el proceso por el cual densas nubes de gas interestelar colapsan para formar nuevas estrellas; durante las colisiones galácticas, el gas de ambas galaxias se comprime violentamente, desencadenando una oleada de nacimientos estelares conocida como "starburst"; aunque las estrellas no choquen, las nubes de gas sí lo hacen, convirtiendo gran parte del gas galáctico en nuevas estrellas en un período relativamente corto)**. Las nubes de gas se comprimirán, encendiendo miles de millones de nuevas estrellas y dando al cielo nocturno de Lactómeda un brillo sin precedentes.

El destino final será una **Galaxia Elíptica (Elliptical Galaxy — tipo de galaxia con forma elipsoidal y una distribución de estrellas casi uniforme, con poco gas y polvo interestelar; a diferencia de las espirales, no tienen brazos ni formación estelar activa; se cree que las galaxias elípticas gigantes son el resultado final de múltiples fusiones de galaxias espirales; Lactómeda será una galaxia de este tipo, roja y muerta en términos de formación estelar nueva, pero con una masa colosal)**. Los brazos espirales desaparecerán, el gas se agotará, y lo que quedará será un enjambre esférico de estrellas viejas.

**Casos de Estudio y Aplicaciones Reales**

El estudio de colisiones galácticas se realiza mediante potentes **Simulaciones de N-Cuerpos (N-Body Simulations — simulaciones computacionales que calculan la evolución dinámica de un sistema de partículas bajo fuerzas físicas, comúnmente la gravedad; en astrofísica se usan para modelar la formación de galaxias y sus colisiones; requieren supercomputadoras para procesar las interacciones de millones de partículas que representan estrellas y materia oscura; las simulaciones de la colisión Vía Láctea-Andrómeda predicen con precisión las fases del proceso y la morfología final de Lactómeda)**. Estas simulaciones nos permiten "ver" el futuro de nuestro vecindario galáctico y entender los procesos que han formado las galaxias elípticas que observamos hoy en el universo distante.

Observamos ejemplos actuales de este proceso en galaxias como las **Antenas (Antennae Galaxies / NGC 4038 & 4039 — par de galaxias espirales en interacción situadas a 45 millones de años-luz; sus largas colas de marea, causadas por la gravedad diferencial durante la colisión, les dan su nombre; son el "laboratorio" más cercano para estudiar lo que le ocurrirá a la Vía Láctea y Andrómeda; muestran regiones masivas de formación estelar reciente provocada por el choque del gas)**. Al estudiar estas colisiones en tiempo real en otros lugares del universo, podemos validar nuestros modelos sobre lo que ocurrirá aquí en el futuro lejano.

**Conclusión Estratégica**

Lactómeda es el destino final de nuestro hogar galáctico. Nos enseña que nada en el universo es estático, ni siquiera las estructuras más grandes que podemos imaginar. Para los estudiantes STEM, el estudio de la dinámica galáctica es una invitación a pensar en escalas de tiempo y espacio que desafían la imaginación. La ingeniería de supercomputación necesaria para estas simulaciones y la astrofísica teórica que las sustenta son los pilares de nuestra comprensión de la evolución cósmica.

🔖 Bluebook v1 · Capítulo I, Sección 1.3.4 📐 NGSS: HS-ESS1-2 — Gravity and galaxy evolution 📋 RENAC: EC009 · Astronomía · Evolución Galáctica"""
}

with open('/Users/yepz/JSweb/data/modules.json', 'r') as f:
    data = json.load(f)

count = 0
for chapter in data['chapters']:
    for module in chapter['modules']:
        if module['id'] in updates:
            module['fullText'] = updates[module['id']]
            count += 1

with open('/Users/yepz/JSweb/data/modules.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Updated {count} modules")
for mid, text in updates.items():
    w = len(text.split())
    print(f"  {mid}: {w} words / {len(text)} chars")
