import json

updates = {
"1.1.5": """Las galaxias son las ciudades del cosmos. Así como las ciudades no brotan del suelo de forma aleatoria sino que emergen donde convergen rutas comerciales, ríos y recursos, las galaxias se forman donde la materia oscura y la gravedad organizan el espacio intergaláctico en filamentos, muros y nodos. El universo a gran escala tiene una estructura que los astrónomos llaman la **Red Cósmica (Cosmic Web — la estructura a gran escala del universo que muestra la materia organizada en filamentos de materia oscura con longitudes de decenas a cientos de megapársecs, con nodos donde se concentran los cúmulos de galaxias y vastos vacíos entre ellos; fue predicha teóricamente por Zel'dovich en los años 1970 y confirmada por los primeros grandes relevamientos de galaxias en los años 1980 y 1990; los filamentos contienen la mayor parte de la masa del universo y actúan como autopistas por las que fluye el gas que alimenta la formación de nuevas galaxias)**: una arquitectura colosal de filamentos, muros y vacíos que se formó durante los primeros miles de millones de años del universo.

Comprender cómo se forman las galaxias es comprender cómo se organiza la materia bajo la influencia de la gravedad a escalas millones de veces mayores que la escala humana. Las mismas leyes que hacen caer una manzana —la gravedad newtoniana y la relatividad general de Einstein— gobiernan el colapso de nubes de gas que se extienden a lo largo de millones de años-luz para dar origen a estructuras que brillarán durante miles de millones de años. La formación de galaxias es, en ese sentido, la gravedad trabajando a escala cósmica.

El proceso comienza con la **Materia Oscura (Dark Matter — componente de la materia que no interactúa con la radiación electromagnética y por lo tanto no emite, absorbe ni refleja luz; representa el 27% de la densidad total de energía del universo; su existencia se infiere de sus efectos gravitacionales: la curva de rotación plana de las galaxias espirales, el lente gravitacional fuerte en cúmulos de galaxias y las anisotropías del CMB; los candidatos principales son las WIMPs —Weakly Interacting Massive Particles—, los axiones y las estrellas de neutrones primordiales; ninguno ha sido detectado directamente pese a décadas de búsqueda intensa)**. La materia oscura no forma estrellas ni planetas, pero su gravedad construye los **Halos de Materia Oscura (Dark Matter Halos — estructuras gravitacionales esféricas de materia oscura que rodean y embeben a las galaxias; su masa típica es 10-100 veces mayor que la masa de la materia bariónica visible de la galaxia; son las "cunas" dentro de las cuales se forma la materia ordinaria; el modelo ΛCDM predice que los halos se forman de forma jerárquica —primero los pequeños, que se fusionan para formar los grandes— en un proceso llamado merging o fusión de halos)**: los andamios invisibles sobre los que se construye todo lo visible del cosmos.

El proceso de colapso sigue la **Inestabilidad de Jeans (Jeans Instability — el criterio físico que determina cuándo una nube de gas puede colapsar gravitacionalmente; formulado por James Jeans en 1902; establece que una nube colapsa cuando su masa supera la Masa de Jeans MJ, que depende de la temperatura y densidad del gas; a temperaturas más bajas y densidades más altas, la masa de Jeans es menor y el colapso ocurre más fácilmente; el enfriamiento radiativo del gas —por emisión de radiación infrarroja de moléculas como el hidrógeno molecular y el monóxido de carbono— es el mecanismo que permite que las nubes superen su masa de Jeans y formen estrellas)**. Una nube de gas que supera este umbral comienza a colapsar en un proceso de retroalimentación: al contraerse se calienta, al calentarse radia energía, al enfriar se contrae más, y en el núcleo más denso nacen las primeras estrellas.

Las galaxias tienen morfologías distintas que reflejan historias de formación diferentes. Las **Galaxias Espirales (Spiral Galaxies — galaxias con un bulbo central esférico, un disco plano con brazos espirales y un halo de materia oscura; los brazos espirales son regiones de alta densidad de estrellas jóvenes, gas y polvo donde la formación estelar es activa; se forman en halos de materia oscura con alto momento angular y relativamente pocas fusiones violentas; la Vía Láctea y Andrómeda son espirales barradas; representan el 77% de las galaxias masivas en el universo local)** como la Vía Láctea tienen brazos de formación estelar activa. Las **Galaxias Elípticas (Elliptical Galaxies — galaxias con forma esférica o elipsoidal, población estelar vieja y roja, poco gas y polvo interestelar y formación estelar mínima; se forman principalmente mediante fusiones de galaxias —major mergers— que destruyen los discos espirales y mezclan las poblaciones estelares; son las galaxias más masivas del universo; la galaxia M87, cuyo agujero negro supermasivo fue fotografiado en 2019 por el Event Horizon Telescope, es una elíptica gigante)** son los restos de fusiones violentas.

**Casos de Estudio y Aplicaciones Reales**

El Telescopio Espacial Hubble revolucionó nuestra comprensión de la formación de galaxias con el **Hubble Deep Field (Hubble Deep Field — imagen obtenida en diciembre de 1995 apuntando el Hubble durante 10 días consecutivos a un pequeño parche del cielo en la constelación de la Osa Mayor; reveló aproximadamente 3,000 galaxias en un campo de apenas 5.3 arcominutos cuadrados; demostró que el universo está lleno de galaxias hasta donde podemos ver y que las galaxias del universo temprano tienen morfologías más irregulares y son más activas en formación estelar que las actuales)**: una ventana de 10 días mirando el cielo oscuro que reveló miles de galaxias en un parche de cielo del tamaño de un grano de arena sostenido a brazo extendido.

El telescopio James Webb, operativo desde 2022, ha observado galaxias a redshifts de z>10, correspondientes a cuando el universo tenía apenas 400 millones de años. Algunas de estas galaxias ya son sorprendentemente masivas y estructuradas, desafiando los modelos de formación galáctica y forzando a los cosmólogos a revisar los tiempos de formación de las primeras estructuras. Cada imagen del Webb es una revisión del libro de texto de la cosmología.

**Conclusión Estratégica**

El nacimiento de galaxias es la historia de cómo la gravedad y la física cuántica colaboraron para crear el orden del cosmos. Las mismas fluctuaciones cuánticas del universo primordial —amplificadas por la inflación— se convirtieron en los nodos de la red cósmica donde hoy existen miles de millones de galaxias. Para los futuros astrofísicos, cosmólogos e ingenieros de instrumentación, la formación de galaxias representa uno de los campos más activos de la astronomía moderna, con nueva evidencia llegando cada semana del James Webb, del Gran Telescopio de Magallanes y de futuros observatorios como el Vera Rubin Observatory y el Extremely Large Telescope en construcción en Chile.

🔖 Bluebook v1 · Capítulo I, Sección 1.1.5 📐 NGSS: HS-ESS1-1 — Stellar properties and galaxy formation 📋 RENAC: EC009 · Cosmología · Formación de Estructuras""",

"1.1.6": """Cuando la materia cae hacia un objeto muy masivo —un agujero negro, una estrella de neutrones, o una estrella ordinaria en formación— no cae directamente en línea recta. La conservación del momento angular hace que la materia entrante forme inevitablemente un disco que gira alrededor del objeto central: un **Disco de Acreción (Accretion Disk — estructura en forma de disco de gas y polvo que orbita un objeto compacto o masivo central; el material en el disco pierde momento angular por viscosidad turbulenta y fricción, espiralizando lentamente hacia el interior; la energía gravitacional liberada en este proceso se convierte en radiación; los discos de acreción son algunos de los objetos más luminosos del universo y los responsables de fenómenos que van desde el calentamiento de sistemas binarios de rayos X hasta la alimentación de cuásares)**. Este simple fenómeno —la geometría de cómo cae la materia— está detrás de algunos de los objetos más energéticos del universo conocido.

Los discos de acreción no son exclusivos del cosmos lejano. Se forman alrededor de estrellas en formación (discos protoplanetarios, de los cuales surgirán planetas), alrededor de estrellas en sistemas binarios que se roban masa mutuamente, y alrededor de los agujeros negros supermasivos en los centros de las galaxias. La física de los discos de acreción une mecánica orbital, termodinámica, magnetohidrodinámica y relatividad general en uno de los problemas más ricos de la astrofísica moderna.

El mecanismo de transferencia de momento angular dentro del disco fue un misterio durante décadas. La **Viscosidad del Disco (Disk Viscosity — la resistencia al flujo diferencial entre capas adyacentes del disco que giran a diferentes velocidades; la viscosidad molecular es demasiado pequeña para explicar la velocidad de acreción observada; el mecanismo dominante es la turbulencia magnetohidrodinámica causada por la inestabilidad magnetorotacional —MRI— descubierta por Balbus y Hawley en 1991; la MRI ocurre cuando un campo magnético débil conecta capas del disco en rotación diferencial y transfiere momento angular hacia afuera, permitiendo que la materia espiral hacia adentro)** turbulenta es lo que permite al material moverse efectivamente hacia adentro, perdiendo energía gravitacional que se convierte en radiación.

Cuando la acreción es suficientemente intensa, los discos de acreción alrededor de agujeros negros supermasivos producen **Cuásares (Quasars / Quasi-Stellar Objects — los núcleos galácticos activos más luminosos del universo; pueden superar en brillo a toda la galaxia que los alberga en un factor de mil; su energía proviene de la acreción de materia al agujero negro supermasivo central a tasas de entre 0.01 y 10 masas solares por año; fueron descubiertos en los años 1960 cuando se detectaron fuentes de radio muy compactas con desplazamientos al rojo enormes que implicaban distancias y luminosidades sin precedente; el cuásar más lejano conocido, J0313-1806, existe cuando el universo tenía apenas 670 millones de años)**. Un cuásar puede irradiar en un segundo tanta energía como el Sol en varios millones de años. Son los faros del cosmos: tan brillantes que los vemos desde los confines del universo observable.

La temperatura del disco de acreción no es uniforme: varía radicalmente desde las regiones exteriores frías hasta las internas calientes. Esto genera el **Espectro Multicolor del Disco (Multi-Color Disk Spectrum — el perfil espectral de un disco de acreción, resultante de la superposición de la radiación de cuerpo negro emitida a diferentes temperaturas por diferentes zonas radiales del disco; la zona interna, más caliente, emite en rayos X; la zona media emite en ultravioleta; la zona exterior, más fría, emite en luz visible e infrarrojo; esta distribución espectral característica es una firma observacional que permite medir la masa del objeto compacto central y la tasa de acreción)**: una paleta de radiaciones desde los rayos X hasta el infrarrojo que los astrónomos usan para medir la masa del agujero negro y la tasa de acreción.

Uno de los fenómenos más espectaculares asociados a los discos de acreción son los **Jets Relativistas (Relativistic Jets — chorros de plasma altamente colimados que emergen perpendiculares al plano del disco de acreción en sistemas con acreción intensa; pueden extenderse durante millones de años-luz; viajan a velocidades de entre el 90 y el 99.9% de la velocidad de la luz; su mecanismo de formación no está completamente comprendido pero involucra campos magnéticos enrollados alrededor del eje de rotación; los jets de la galaxia M87 —fotografiados con el Event Horizon Telescope junto con el agujero negro central— tienen una longitud de 5,000 años-luz)**. Estos chorros de plasma relativista, lanzados perpendicularmente al disco, transportan enormes cantidades de energía hacia el espacio intergaláctico y calientan el medio intergaláctico, influyendo en la formación de galaxias a escalas cosmológicas.

**Casos de Estudio y Aplicaciones Reales**

El caso más estudiado de acreción cósmica es la galaxia M87, a 55 millones de años-luz de distancia. El Event Horizon Telescope (EHT) —una red de radiotelescopios distribuidos por todo el planeta que actúa como un único telescopio del tamaño de la Tierra— produjo en 2019 la primera imagen directa de un agujero negro y su disco de acreción. La imagen muestra el anillo brillante de gas supercalentado girando en el disco y la sombra circular del horizonte de eventos del agujero negro de 6,500 millones de masas solares. Esta imagen no fue solo un logro fotográfico; fue una verificación directa de predicciones de la Relatividad General en el régimen de gravedad extrema que nunca antes había podido comprobarse.

En nuestro propio sistema solar, los discos de acreción explican el origen de los planetas. El sistema solar se formó hace 4,568 millones de años cuando una nube de gas y polvo colapso formando el Sol en el centro y un disco protoplanetario a su alrededor. Los planetas se formaron por acreción de polvo y planetesimales dentro de ese disco, un proceso llamado acreción planetaria que tardó decenas de millones de años.

**Conclusión Estratégica**

Los discos de acreción son el testimonio de que la gravedad y el momento angular son fuerzas arquitectónicas de primer orden en el cosmos. Desde los planetas de nuestro sistema solar hasta los cuásares más lejanos del universo observable, la misma física —momento angular conservado, energía gravitacional convertida en radiación, campos magnéticos que transportan momento— opera en escalas que van de metros a millones de años-luz. Para los futuros astrofísicos, ingenieros de instrumentación y físicos teóricos, comprender los discos de acreción es entrar en la intersección más rica de la física clásica, la relatividad general y la física de plasmas.

🔖 Bluebook v1 · Capítulo I, Sección 1.1.6 📐 NGSS: HS-PS2-4 — Gravitational force and orbital motion 📋 RENAC: EC009 · Astrofísica · Discos de Acreción y AGN""",

"1.1.8": """Hace 4,500 millones de años, la Tierra recién formada era un planeta sin vida, sin luna y sin la inclinación axial estable que hoy regula nuestras estaciones. Entonces ocurrió el evento más violento en la historia de la Tierra desde su formación: un cuerpo del tamaño de Marte —que los científicos llaman **Theia (Theia — cuerpo planetario hipotético del tamaño de Marte, con aproximadamente el 10% de la masa terrestre, que colisionó con la proto-Tierra hace unos 4,500 millones de años; su existencia fue propuesta independientemente por William Hartmann y Donald Davis en 1975; el nombre proviene de la titánide griega, madre de Selene, la diosa de la Luna; evidencia de su existencia incluye la composición isotópica similar entre la Luna y la Tierra en elementos como oxígeno, titanio y cromo, con ligeras diferencias que sugieren que Theia tenía un origen diferente del cinturón exterior del sistema solar)** — colisionó con la proto-Tierra en un impacto oblicuo de escala catastrófica. Este evento, conocido como la **Hipótesis del Gran Impacto (Giant Impact Hypothesis — el modelo científico actualmente aceptado del origen de la Luna; propone que Theia impactó la proto-Tierra en un ángulo oblicuo a velocidades de 4-8 km/s; la colisión vaporizó gran parte de los mantos de ambos cuerpos; los materiales vaporizados fueron expulsados al espacio formando un toro caliente de roca vaporizada —un "synestia"— que se condensó en unos pocos decenios para formar la Luna; fue propuesto independientemente por Hartmann-Davis y Cameron-Ward en 1975)**, es hoy el modelo científico estándar para el origen de nuestra Luna. Y sus consecuencias van mucho más allá de explicar el origen de un satélite.

La Luna no es solo el objeto más brillante del cielo nocturno ni la causa de las mareas oceánicas. Es, en un sentido muy real, un componente esencial de las condiciones que permitieron el desarrollo de la vida compleja en la Tierra. Sin la Luna, la inclinación axial de la Tierra —hoy de 23.5 grados— sería caótica, variando entre 0 y 85 grados en escalas de millones de años, produciendo variaciones climáticas tan extremas que el desarrollo de biosistemas complejos habría sido enormemente más difícil o imposible. La colisión de Theia no fue solo un accidente cósmico; fue, en retrospectiva, una de las condiciones necesarias para que tú existas.

Durante la colisión, las simulaciones computacionales modernas muestran que los mantos de ambos cuerpos —Theia y la proto-Tierra— se fusionaron parcialmente en un estado de plasma y roca vaporizada. El **Sinestia (Synestia — objeto astronómico hipotético consistente en una masa de roca vaporizada en rotación rápida, donde la rotación es tan rápida que el objeto supera el límite de corrotación colapso; fue propuesto por Lock y Stewart en 2017 como el estado intermedio del sistema Tierra-Luna tras el Gran Impacto; la sinestia se enfría y contrae en decenas a cientos de años, con el material exterior condensándose para formar la Luna mientras el interior forma la Tierra; este modelo explica mejor la composición isotópica similar de Tierra y Luna que los modelos anteriores)**, una estructura de roca fundida en rotación ultrarrápida, habría existido durante décadas antes de condensarse en la Tierra actual y la Luna.

Las simulaciones del impacto también explican varias propiedades observadas de la Luna. El **Déficit de Hierro Lunar (Lunar Iron Deficit — la Luna tiene una densidad media de 3.34 g/cm³ comparada con 5.51 g/cm³ de la Tierra; esto refleja que la Luna tiene un núcleo de hierro mucho menor en proporción —solo un 1-3% de su masa frente al 32% de la Tierra—; en el modelo del Gran Impacto, la Luna se formó principalmente del manto de la proto-Tierra y Theia —rocas silicatadas— mientras que los núcleos de hierro de ambos cuerpos se hundieron y se fusionaron en el interior de la proto-Tierra antes del impacto)** de la Luna —su baja densidad comparada con la Tierra— es evidencia directa de que se formó principalmente del manto, no del núcleo, de los cuerpos progenitores.

Las **Mareas Terrestres (Tidal Forces — las fuerzas gravitacionales diferenciales ejercidas por la Luna sobre la Tierra; la cara de la Tierra más cercana a la Luna experimenta una fuerza gravitacional mayor que el centro, y el centro mayor que el lado opuesto; esto deforma la Tierra ligeramente creando dos protuberancias oceánicas opuestas —las mareas—; la fricción de estas protuberancias con el fondo marino frena la rotación terrestre gradualmente, alargando el día en aproximadamente 2 milisegundos por siglo; como consecuencia, la Luna se aleja de la Tierra a razón de 3.8 cm por año —medido con precisión por el reflector láser que dejaron los astronautas del Apolo)** son el testimonio gravitacional presente de ese impacto hace 4,500 millones de años. La Luna frena la rotación de la Tierra y se aleja progresivamente. Hace 600 millones de años, un día terrestre duraba solo 22 horas.

**Casos de Estudio y Aplicaciones Reales**

La confirmación más directa de la Hipótesis del Gran Impacto provino de las muestras lunares traídas por las misiones Apolo entre 1969 y 1972. El análisis isotópico de estas rocas reveló composiciones de oxígeno, titanio y cromo casi idénticas a las de la Tierra, con diferencias menores del 0.01%, algo imposible si la Luna se hubiera formado en otra parte del sistema solar o capturada gravitacionalmente. En 2020, un análisis de isótopos de potasio-41 en muestras lunares mostró diferencias con la Tierra que encajan perfectamente con los modelos de sinestia pero no con los modelos anteriores, dando nueva vida a la hipótesis.

El reflectómetro láser —un retroreflector colocado en la superficie lunar por los astronautas del Apolo 11 en 1969— sigue siendo usado hoy por observatorios en todo el mundo para medir con precisión milimétrica la distancia a la Luna mediante pulsos láser. Estas mediciones han confirmado que la Luna se aleja a 3.82 cm por año, exactamente lo predicho por los modelos de disipación mareal.

**Conclusión Estratégica**

El impacto de Theia es el recordatorio de que la historia de la Tierra —y de la vida que alberga— es inseparable de los procesos violentos del sistema solar primitivo. Un planeta sin esa colisión podría haber tenido una axe de rotación caótica, sin estaciones regulares, sin la estabilización climática que permitió el desarrollo de la biosfera compleja. Las misiones lunares futuras —Artemis de NASA, las misiones chinas Chang'e, la iniciativa lunar europea— no son solo exploraciones geológicas; son el camino para entender mejor la historia del impacto que hizo posible la vida en la Tierra y para evaluar la habitabilidad de otros planetas con o sin lunas masivas.

🔖 Bluebook v1 · Capítulo I, Sección 1.1.8 📐 NGSS: HS-ESS1-6 — Orbital interactions and planetary formation 📋 RENAC: EC009 · Geociencias · Origen de la Luna"""
}

with open('/Users/yepz/JSweb/data/modules.json', 'r') as f:
    data = json.load(f)

count = 0
for chapter in data['chapters']:
    for module in chapter['modules']:
        if module['id'] in updates:
            module['fullText'] = updates[module['id']]
            count += 1

with open('/Users/yepz/JSweb/data/modules.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Updated {count} modules")
for mid, text in updates.items():
    w = len(text.split())
    print(f"  {mid}: {w} words / {len(text)} chars")
