import json

updates = {
"1.0.3": """Antes de explorar el Big Bang, los átomos, los procesadores o el código, necesitamos hablar de algo más fundamental: la manera en que piensas. No qué piensas, sino cómo lo haces. Porque el mayor obstáculo para comprender el mundo tecnológico y científico en que vivimos no es la falta de información —hoy tenemos acceso a más datos que en cualquier otro momento de la historia humana— sino la ausencia de un filtro confiable para saber qué hacer con esa información. Ese filtro tiene un nombre: **Neosys Aeon (Neosys Aeon Framework — marco conceptual abierto diseñado para mejorar la manera en que los individuos comprenden la realidad y toman decisiones basadas en evidencia; articula diez principios operativos que avanzan desde el individuo hacia lo colectivo; no es una ideología sino un conjunto de prácticas epistémicas aplicables en ciencia, tecnología, política y vida cotidiana)**.

La razón de su existencia parte de un diagnóstico incómodo pero necesario: la abundancia masiva de información que caracteriza al siglo XXI no ha producido una mejora proporcional en la calidad del pensamiento colectivo. Investigaciones en **Epistemología Aplicada (Applied Epistemology — rama de la filosofía que estudia cómo adquirimos conocimiento y cómo podemos mejorar ese proceso en contextos prácticos y cotidianos; distingue entre creencias justificadas y meras opiniones; evalúa la calidad de las fuentes, la validez de los argumentos y la coherencia de las conclusiones; su aplicación en educación busca desarrollar pensadores críticos capaces de navegar entornos de información compleja)** documentan una paradoja perturbadora: el acceso a más datos puede, en ciertos contextos, reforzar sesgos preexistentes en lugar de corregirlos, un fenómeno conocido como **Razonamiento Motivado (Motivated Reasoning — tendencia cognitiva a buscar, interpretar y recordar información de manera que confirme creencias previas en lugar de evaluar evidencia de forma objetiva; fue documentado sistemáticamente por Ziva Kunda en 1990; se activa especialmente cuando la evidencia amenaza creencias identitarias o emocionales; es responsable de por qué personas inteligentes pueden mantener creencias falsas frente a evidencia clara en sentido contrario)**. Entre el 30 y el 60 por ciento de los adultos en países industrializados tiene dificultades para distinguir afirmaciones científicas de afirmaciones pseudocientíficas, y ese número no mejora solo con más acceso a internet.

El marco Neosys Aeon propone restablecer una cadena operativa esencial: **Comprender → Validar → Aplicar**. Comprender es construir una representación precisa de la realidad a partir de evidencia. Validar significa someter esa comprensión al escrutinio del método científico: ¿Es falsable? ¿Ha sido replicado? ¿Resiste el cuestionamiento? Aplicar es el paso que convierte el conocimiento en acción real con impacto real.

Los diez principios de Neosys Aeon no son mandamientos ni reglas absolutas. Son puntos de partida revisables para quien decida adoptarlos. El **primero** invita a priorizar la verdad sobre la comodidad: no apoyarse en certezas falsas, buscar lo que es real aunque sea inconveniente. El **segundo** cultiva la curiosidad como práctica: preguntar antes de afirmar, explorar antes de juzgar. El **tercero** recuerda que somos polvo de estrellas, no por pequeñez sino por pertenencia. El **cuarto** propone la humildad epistémica: reconocer abiertamente los límites del propio conocimiento. El **quinto** enfatiza la coherencia entre lo que se piensa, lo que se dice y lo que se hace.

El **sexto** principio valora la **Colaboración Epistémica (Epistemic Collaboration — el principio de que el conocimiento colectivo supera al individual; ninguna mente, por brillante que sea, puede abarcar sola la totalidad del conocimiento disponible; la ciencia como institución es el ejemplo más exitoso de colaboración epistémica sostenida; la revisión por pares, la replicación de experimentos y el debate abierto son sus mecanismos de calidad)**. El **séptimo** exige responsabilidad en el impacto de las propias acciones sobre la comunidad. El **octavo** subraya la importancia del pensamiento a largo plazo en un mundo que recompensa la gratificación inmediata. El **noveno** propone integrar lo que sabemos con cómo vivimos: no fragmentar el conocimiento técnico de la ética personal. El **décimo** principio —quizás el más difícil— invita a revisar activamente las propias creencias cuando la evidencia lo exige: el cambio de opinión ante nueva evidencia no es debilidad sino la definición misma de rigor intelectual.

En el contexto de JóvenesSTEM, el marco Neosys Aeon no es opcional. Es el suelo sobre el que se planta todo lo demás. Un estudiante que domina la física cuántica pero no puede evaluar críticamente una fuente de información está parcialmente equipado. Un estudiante que entiende la biología molecular pero decide basándose en prejuicios tiene un déficit que ningún diploma corrige. La **Alfabetización Científica (Scientific Literacy — la capacidad de comprender conceptos, procesos y valores de la ciencia; incluye entender cómo funciona la investigación científica, interpretar datos y gráficos, evaluar afirmaciones con evidencia y reconocer la diferencia entre ciencia y pseudociencia; la OCDE la mide como parte de PISA y la considera una competencia del siglo XXI tan fundamental como leer y escribir)** no comienza con la memorización de fórmulas; comienza con la disposición a cambiar de opinión cuando los datos lo justifican.

**Casos de Estudio y Aplicaciones Reales**

El poder del pensamiento basado en evidencia no es abstracto. En 1998, el estudio fraudulento de Andrew Wakefield afirmando una relación entre vacunas y autismo fue publicado en The Lancet. A pesar de ser retractado completamente en 2010 y refutado por decenas de estudios con millones de participantes, el daño al imaginario colectivo persiste. El marco Neosys Aeon, aplicado rigurosamente, habría permitido identificar las señales de alerta: muestra demasiado pequeña (12 pacientes), conflicto de interés económico no declarado, incapacidad de replicación. Esta no es historia antigua: versiones modernas del mismo error ocurren cada semana en redes sociales, en política pública y en decisiones empresariales.

En contraste positivo, la colaboración epistémica a escala global que representó el desarrollo de las vacunas contra COVID-19 en 2020-2021 —completado en nueve meses cuando el récord anterior era cuatro años— fue posible porque miles de investigadores compartieron datos abiertamente, sometieron sus hallazgos a revisión acelerada y actualizaron sus modelos cuando los datos lo exigían. Ese es el modelo Neosys Aeon en acción colectiva.

**Conclusión Estratégica**

El siglo XXI pertenece a quienes pueden pensar con claridad en entornos de incertidumbre, tomar decisiones basadas en evidencia y comunicar sus razonamientos de forma transparente. Ninguna inteligencia artificial, ningún algoritmo de recomendación y ninguna plataforma de información puede reemplazar el juicio crítico de una mente bien entrenada. Neosys Aeon no te dice qué pensar; te entrena en cómo hacerlo. Y esa diferencia es la que separa al usuario de la tecnología del arquitecto del futuro.

🔖 Bluebook v1 · Capítulo Intro, Sección 1.0.3 📐 NGSS: Science & Engineering Practices · Constructing Explanations 📋 RENAC: EC009 · Competencias Transversales STEM""",

"1.1.1": """Hace 13,800 millones de años no existía el espacio, no existía el tiempo, no existía la materia ni la energía tal como las conocemos hoy. No había "antes" del Big Bang porque el tiempo mismo comenzó en ese instante. Esta afirmación no es filosofía ni metáfora: es la conclusión directa de las ecuaciones de la Relatividad General de Einstein aplicadas hacia atrás en el tiempo. El **Big Bang (Big Bang — el modelo cosmológico estándar que describe el origen y evolución del universo; no fue una explosión en el espacio sino una expansión del espacio mismo desde un estado de densidad y temperatura infinitas hace 13.8 mil millones de años; el término fue acuñado irónicamente por el astrónomo Fred Hoyle en 1949, quien defendía el modelo de Estado Estacionario y usó el apodo para ridiculizar la teoría, sin imaginar que la frase se volvería el nombre oficial del mayor descubrimiento cosmológico del siglo XX)** es la historia de origen de todo: galaxias, estrellas, planetas, átomos, vida. Y comprenderla es comprender de dónde vienen cada uno de los átomos que forman tu cuerpo.

Esta no es una teoría especulativa. Es el modelo mejor respaldado en la historia de la cosmología, sostenido por múltiples líneas de evidencia independientes: la expansión del universo medida por Hubble en 1929, la abundancia primordial de elementos ligeros que coincide exactamente con las predicciones de la nucleosíntesis del Big Bang, y el descubrimiento en 1965 del Fondo Cósmico de Microondas por Penzias y Wilson. Estos tres pilares forman una red de confirmación mutua que ningún modelo alternativo ha podido replicar.

En el primer instante —antes de 10⁻⁴³ segundos, la llamada **Época de Planck (Planck Epoch — el período comprendido entre el inicio del universo y el tiempo de Planck, 5.39×10⁻⁴⁴ segundos; durante este tiempo, las cuatro fuerzas fundamentales —gravedad, electromagnetismo, fuerza nuclear fuerte y débil— eran una sola fuerza unificada; la densidad superaba la densidad de Planck de 5.1×10⁹⁶ kg/m³ y la temperatura era mayor que la temperatura de Planck de 1.4×10³² K; ninguna teoría física actual puede describir estas condiciones porque requiere una teoría cuántica de la gravedad que aún no existe)** — el universo era una singularidad de densidad y temperatura infinitas donde todas las leyes físicas conocidas colapsan.

Inmediatamente después, entre 10⁻³⁶ y 10⁻³² segundos, ocurrió algo que resuelve varios de los misterios más profundos de la cosmología: la **Inflación Cósmica (Cosmic Inflation — período de expansión exponencial del universo propuesto por Alan Guth en 1980; durante un intervalo de tiempo menor que un parpadeo cuántico, el universo se expandió en un factor de al menos 10²⁶; explica por qué el universo observable es tan homogéneo —la uniformidad del CMB— y tan plano —la geometría euclidiana del espacio a gran escala—; también explica por qué no observamos monopolos magnéticos, que la Gran Teoría Unificada predice pero nunca se han detectado)**. La inflación estiró las pequeñas fluctuaciones cuánticas del vacío a escalas macroscópicas: esas pequeñísimas irregularidades se convirtieron en las semillas de las galaxias que vemos hoy.

Al finalizar la inflación, la energía del campo inflacionario se convirtió en el **Plasma de Quarks y Gluones (Quark-Gluon Plasma / QGP — el estado de la materia existente en los primeros microsegundos tras el Big Bang, cuando la temperatura era superior a 2×10¹² K; en estas condiciones, quarks y gluones existían libremente sin estar confinados en hadrones como protones o neutrones; es el estado más caliente y denso de la materia conocida; el LHC del CERN recrea brevemente este estado mediante colisiones de iones de plomo a velocidades relativistas; se comporta casi como un fluido perfecto con viscosidad cercana al mínimo cuántico)**, un caldo primordial de partículas fundamentales que llenó el universo recién nacido. A medida que el universo se expandió y enfrió, quarks y gluones se confinaron en protones y neutrones —la materia ordinaria que hoy conocemos.

Entre los 3 minutos y los 20 minutos de vida del universo, ocurrió la **Nucleosíntesis Primordial (Big Bang Nucleosynthesis / BBN — el proceso por el cual los primeros núcleos atómicos se formaron a partir de protones y neutrones cuando la temperatura cayó por debajo de 10⁹ K; produjo hidrógeno-1 (≈75% de la masa barionica), helio-4 (≈25%), deuterio (≈0.001%), y cantidades traza de litio-7 y berilio-7; las proporciones predichas por la teoría coinciden con las observaciones en las nubes de gas más antiguas e intocadas del universo con una precisión del 1%, constituyendo una de las validaciones más poderosas del modelo estándar cosmológico)**. Las proporciones de hidrógeno y helio que vemos hoy en el universo —75% y 25% respectivamente— fueron fijadas en esos primeros minutos y no han cambiado significativamente desde entonces.

**Casos de Estudio y Aplicaciones**

La teoría del Big Bang no se comprobó en un laboratorio sino en el cielo. Edwin Hubble midió en 1929 que las galaxias se alejan de nosotros a velocidades proporcionales a su distancia —la Ley de Hubble— lo que implica que en el pasado estaban más juntas. En 1965, Arno Penzias y Robert Wilson, ingenieros de Bell Labs que ajustaban una antena de microondas, detectaron accidentalmente un ruido de fondo uniforme proveniente de todas las direcciones del cielo: el Fondo Cósmico de Microondas, la "foto" del universo cuando tenía 380,000 años. Ningún modelo alternativo pudo explicar este hallazgo. En 2001, el satélite WMAP mapeó este fondo con una precisión sin precedentes, revelando las semillas de la estructura cósmica. En 2009, el satélite Planck mejoró esa resolución al punto de constreñir la edad del universo a 13,813 ± 38 millones de años.

En el CERN, las colisiones de iones pesados en el detector ALICE recrean el Plasma de Quarks y Gluones por fracciones de segundo, permitiendo estudiar directamente las condiciones del universo a 10⁻⁶ segundos del Big Bang. Este conocimiento conecta directamente con la física de partículas, la cosmología y —a través de los materiales de ultra-alta densidad— con aplicaciones en fusión nuclear y tecnología cuántica.

**Conclusión Estratégica**

Comprender el Big Bang es comprender que el universo tiene una historia, y que esa historia es accesible a través de la razón y el experimento. Las leyes de la física que rigen un electrón en tu laptop son las mismas que gobernaron el universo en sus primeros instantes. Esta conexión —entre lo más pequeño y lo más grande, entre el laboratorio y el cosmos— es la esencia del pensamiento STEM. Las carreras en cosmología, astrofísica, física de partículas y ciencias de materiales tienen en el Big Bang su primer capítulo. Pero también lo tienen la ingeniería de materiales de alta densidad, la computación cuántica y cualquier disciplina que busque comprender la naturaleza fundamental de la realidad.

🔖 Bluebook v1 · Capítulo I, Sección 1.1.1 📐 NGSS: HS-ESS1-2 — Construct an explanation based on evidence of the Big Bang theory 📋 RENAC: EC009 · Cosmología y Origen del Universo"""
}

with open('/Users/yepz/JSweb/data/modules.json', 'r') as f:
    data = json.load(f)

count = 0
for chapter in data['chapters']:
    for module in chapter['modules']:
        if module['id'] in updates:
            module['fullText'] = updates[module['id']]
            count += 1

with open('/Users/yepz/JSweb/data/modules.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Updated {count} modules")
for mid, text in updates.items():
    w = len(text.split())
    print(f"  {mid}: {w} words / {len(text)} chars")
