import json

updates = {
"1.6.7": """En la inmensidad del océano cósmico, existen objetos que actúan como faros de una precisión asombrosa, emitiendo haces de energía que parpadean con la regularidad de un reloj atómico. Estos objetos son los **Pulsares: Faros (Pulsars — estrellas de neutrones en rotación extremadamente rápida que emiten haces colimados de radiación electromagnética desde sus polos magnéticos; debido a que el eje magnético no coincide con el eje de rotación, estos haces barren el espacio como el foco de un faro; desde la Tierra, observamos pulsos periódicos de radio, luz o rayos X cada vez que el haz apunta hacia nosotros; fueron descubiertos en 1967 por Jocelyn Bell Burnell, revolucionando nuestra comprensión de la materia extrema)**. Los púlsares no son solo una curiosidad astronómica; son los cronómetros definitivos del universo y una herramienta vital para la navegación espacial futura.

Un púlsar es el remanente hiperdenso de una estrella masiva que ha colapsado después de una supernova. Imagina una masa mayor que la del Sol comprimida en una esfera del tamaño de una ciudad. Debido a la conservación del momento angular, al encogerse tanto, la estrella comienza a girar a velocidades vertiginosas, algunas veces completando cientos de vueltas por segundo. Este giro rápido, combinado con un campo magnético trillones de veces más fuerte que el de la Tierra, crea un generador eléctrico natural de una potencia inimaginable que acelera partículas a velocidades cercanas a la de la luz.

La característica definitoria de un púlsar es su **Precisión Cronométrica (Chronometric Precision — la estabilidad extrema del período de rotación de un púlsar, que se mantiene constante con una precisión de hasta una parte en mil billones; esta estabilidad permite a los astrónomos utilizar los púlsares como relojes naturales para medir el tiempo profundo y detectar cambios minúsculos en el espacio-tiempo causados por ondas gravitatorias o el movimiento de planetas invisibles; de hecho, los primeros planetas descubiertos fuera del sistema solar fueron encontrados orbitando un púlsar en 1992)**. Un púlsar es, en esencia, el estándar de tiempo natural del cosmos.

Existen púlsares que giran tan rápido que su período se mide en milisegundos, conocidos como **Púlsares de Milisegundo (Millisecond Pulsars — púlsares con períodos de rotación entre 1 y 10 milisegundos; se cree que estas estrellas han sido "aceleradas" por la transferencia de materia desde una estrella compañera en un sistema binario; a medida que la materia cae sobre el púlsar, le transfiere momento angular, haciéndolo girar cada vez más rápido; estos púlsares son los más estables de todos y son fundamentales para la formación de redes de cronometría de púlsares a escala galáctica)**. Son las máquinas giratorias más rápidas y precisas conocidas por el hombre.

La radiación de un púlsar puede abarcar todo el espectro, pero es más común en las ondas de radio. Sin embargo, algunos emiten intensamente en **Rayos Gamma (Gamma-Ray Pulsars — púlsares que emiten la forma más energética de luz; el telescopio espacial Fermi ha descubierto cientos de estos objetos, revelando que los púlsares son aceleradores de partículas naturales mucho más potentes que cualquier colisionador construido en la Tierra; estudiar esta radiación extrema nos ayuda a entender los límites de la electrodinámica cuántica y la física del plasma en condiciones de gravedad y magnetismo extremos)**. Cada pulso es una firma energética única de una de las regiones más violentas del espacio.

**Casos de Estudio y Aplicaciones Reales**

El caso de estudio más icónico es el **Púlsar del Cangrejo (Crab Pulsar — situado en el centro de la Nebulosa del Cangrejo, el remanente de una supernova observada por astrónomos chinos en el año 1054; este púlsar gira unas 30 veces por segundo y emite radiación en todas las longitudes de onda, desde radio hasta rayos gamma; es el púlsar más estudiado del cielo y nos ha proporcionado datos invaluables sobre cómo las estrellas de neutrones inyectan energía en sus nebulosas circundantes)**. Es el "modelo estándar" para entender la física de los púlsares jóvenes y energéticos.

En el ámbito tecnológico, el proyecto **SEXTANT (Station Explorer for X-ray Timing and Navigation Technology)** de la NASA ha demostrado el uso de púlsares para la navegación espacial autónoma. Utilizando un sensor de rayos X en la Estación Espacial Internacional (NICER), el sistema logró determinar la posición de la estación con una precisión de pocos kilómetros basándose únicamente en los tiempos de llegada de los pulsos de varios púlsares conocidos. Este "GPS Galáctico" será la clave para que las futuras naves espaciales naveguen de forma autónoma hacia Marte, Júpiter y más allá de nuestro sistema solar sin depender de señales terrestres que tardan horas en viajar.

Otro ejemplo fascinante es el uso de púlsares para detectar **Ondas Gravitatorias de Fondo (Gravitational Wave Background)**. Al monitorear una red de púlsares de milisegundos distribuidos por toda la galaxia (Pulsar Timing Arrays), los científicos pueden detectar cómo el espacio-tiempo se estira y encoge muy levemente cuando pasan ondas gravitatorias de baja frecuencia generadas por la colisión de agujeros negros supermasivos en galaxias lejanas. En 2023, varias colaboraciones internacionales anunciaron las primeras evidencias de este fondo de ondas gravitatorias, abriendo una nueva era en nuestra capacidad de "escuchar" el murmullo del universo.

**Conclusión Estratégica**

Los púlsares son los guardianes del tiempo y la navegación en el universo profundo. Para los futuros ingenieros de telecomunicaciones, astrofísicos y diseñadores de misiones interestelares, estos objetos representan la infraestructura natural que permitirá a la humanidad expandirse por la galaxia. Aprender a leer el lenguaje de los púlsares es aprender a orientarse en la inmensidad del espacio, utilizando los relojes más precisos que la naturaleza ha forjado.

Estudiar un púlsar es estudiar la materia en sus límites más extremos de densidad, rotación y magnetismo. Cada destello que recibimos es un mensaje de una estrella muerta que sigue sirviendo al universo como un faro eterno. Para un estudiante STEM, el púlsar es el símbolo de cómo la ciencia puede convertir un fenómeno exótico y lejano en una herramienta tecnológica práctica que algún día guiará los pasos de los primeros exploradores interestelares de la humanidad.

🔖 Bluebook v1 · Capítulo I, Sección 1.6.7 — Pulsares: Faros (Págs. 228–231)
📐 NGSS: HS-PS4-2 (Digital transmission and waves) — Evaluate questions about the advantages of using a digital transmission and storage of information (applied to pulsar pulse timing).
📋 RENAC: EC009 · Astrofísica de Altas Energías y Navegación Espacial
💡 Standards World: Pulsar (Púlsar) · Angular Momentum (Momento Angular) · X-ray Navigation (Navegación por Rayos X)""",

"1.6.8": """En los confines más extremos de la física, donde la gravedad vence por completo a todas las demás fuerzas de la naturaleza, surge el objeto más enigmático y aterrador del universo: un lugar donde el espacio y el tiempo se curvan tanto que ni siquiera la luz puede escapar. Este objeto es un **Agujero Negro (Black Hole — una región del espacio-tiempo con un campo gravitatorio tan intenso que ninguna partícula ni radiación electromagnética puede escapar de ella; se forma tras el colapso gravitatorio total de una estrella masiva al final de su vida; su estructura principal incluye el horizonte de eventos —la frontera de no retorno— y la singularidad central —un punto de densidad infinita donde las leyes actuales de la física se rompen—)**. Los agujeros negros son las prisiones de luz del cosmos y los laboratorios donde la relatividad de Einstein se encuentra con la mecánica cuántica.

La existencia de los agujeros negros no es solo una teoría matemática; son objetos reales que dominan la dinámica de las galaxias y marcan los límites de nuestro conocimiento científico. Un agujero negro no es una "aspiradora" que succiona todo a su paso, sino una concentración de masa tan extrema que distorsiona la realidad a su alrededor. Si pudieras observar a alguien cayendo en un agujero negro desde afuera, verías cómo su tiempo se ralentiza hasta detenerse por completo en el borde, mientras que para la persona que cae, el final llegaría en un instante violento y definitivo.

El límite invisible que define a un agujero negro es el **Horizonte de Eventos (Event Horizon — la superficie esférica imaginaria que rodea a un agujero negro a partir de la cual la velocidad de escape requerida supera la velocidad de la luz; cualquier cosa que cruce este límite, ya sea materia o información, queda desconectada para siempre del universo observable; el radio de este horizonte se conoce como radio de Schwarzschild y depende directamente de la masa del agujero negro: por ejemplo, para la Tierra, el radio de Schwarzschild sería de apenas 9 milímetros)**. Es la frontera definitiva entre el ser y el no ser.

En el centro de este abismo se encuentra la **Singularidad (Singularity — un punto o anillo de volumen cero y densidad infinita donde toda la masa del agujero negro está concentrada; en la singularidad, la curvatura del espacio-tiempo se vuelve infinita y las ecuaciones de la Relatividad General dejan de tener sentido físico; es el mayor misterio de la ciencia moderna, ya que requiere una teoría de Gravedad Cuántica —que aún no tenemos— para ser explicada correctamente)**. La singularidad es el lugar donde el universo "se rompe".

Alrededor de muchos agujeros negros activos encontramos un **Disco de Acreción (Accretion Disk — una estructura en forma de disco compuesta por gas, polvo y plasma que orbita a velocidades cercanas a la de la luz antes de caer al agujero negro; la fricción y la gravedad calientan este material a millones de grados, haciendo que emita intensos rayos X y luz visible; irónicamente, esto convierte a los agujeros negros —los objetos más oscuros— en algunos de los objetos más brillantes y detectables del universo)**. Estos discos son los motores más eficientes de la galaxia, convirtiendo la masa en energía con una eficacia mucho mayor que la fusión nuclear.

**Casos de Estudio y Aplicaciones Reales**

El caso de estudio más histórico y visual es la primera fotografía de un agujero negro obtenida por el **Event Horizon Telescope (EHT)** en 2019. Utilizando una red de radiotelescopios en todo el mundo para crear un telescopio virtual del tamaño de la Tierra, los científicos capturaron la imagen de la sombra del agujero negro supermasivo en el centro de la galaxia M87. Esta imagen confirmó por primera vez la existencia del horizonte de eventos y validó las predicciones de Einstein en el entorno más extremo posible, marcando un hito en la historia de la ciencia y la tecnología de datos masivos.

Otro ejemplo fundamental es el estudio de **Sagitario A*** (Sagittarius A-star), el agujero negro de 4 millones de masas solares en el centro de nuestra propia Vía Láctea. Durante décadas, los astrónomos observaron estrellas orbitando a velocidades increíbles alrededor de un punto invisible en el centro galáctico. Al aplicar las leyes de Kepler y Newton, calcularon que solo un agujero negro podía tener tanta masa concentrada en un espacio tan pequeño. Este trabajo, que valió el Premio Nobel en 2020, demostró que los agujeros negros no son excepciones raras, sino componentes fundamentales que mantienen unidas a las galaxias.

En la física teórica, un concepto revolucionario es la **Radiación de Hawking (Hawking Radiation — radiación térmica que se predice es emitida por los agujeros negros debido a efectos cuánticos cerca del horizonte de eventos; propuesta por Stephen Hawking en 1974, sugiere que los agujeros negros no son totalmente negros, sino que se "evaporan" muy lentamente a lo largo de eones; este concepto une por primera vez la termodinámica, la mecánica cuántica y la gravedad, y es la clave para resolver la paradoja de la pérdida de información en los agujeros negros)**. Aunque es demasiado tenue para ser detectada hoy, es la base de toda la física teórica moderna.

**Conclusión Estratégica**

Los agujeros negros son las fronteras finales de nuestra comprensión del universo. Para los futuros físicos teóricos, matemáticos y especialistas en computación cuántica, estos objetos representan el reto definitivo: reconciliar lo muy grande con lo muy pequeño. Entender un agujero negro es entender cómo se fabricó el universo y cómo podría terminar. A medida que nuestra tecnología de observación mejora, los agujeros negros dejan de ser monstruos teóricos para convertirse en herramientas para probar la naturaleza misma de la realidad.

Aunque están a distancias inimaginables, los agujeros negros nos enseñan sobre la resiliencia de las leyes físicas y la inmensidad de la naturaleza. Son el recordatorio de que siempre hay más por descubrir y que incluso la oscuridad más absoluta contiene secretos que pueden iluminar nuestro conocimiento. Para un estudiante STEM, el agujero negro es la invitación máxima a la curiosidad y al rigor científico, el lugar donde la imaginación humana y la realidad física chocan para crear las preguntas más profundas de la ciencia.

🔖 Bluebook v1 · Capítulo I, Sección 1.6.8 — Agujeros Negros (Págs. 232–235)
📐 NGSS: HS-ESS1-2 (Evidence of the Big Bang and stars) — Construct an explanation of the Big Bang theory based on astronomical evidence of light spectra, motion of distant galaxies, and composition of matter in the universe.
📋 RENAC: EC009 · Relatividad General y Astrofísica Relativista
💡 Standards World: Black Hole (Agujero Negro) · Event Horizon (Horizonte de Eventos) · Singularity (Singularidad)""",

"1.7.1": """Desde los filósofos de la antigua Grecia hasta los colisionadores de partículas más avanzados de la actualidad, la humanidad ha estado obsesionada con una sola pregunta: ¿de qué está hecho realmente el mundo? Esta búsqueda milenaria para encontrar la unidad mínima e indivisible de la materia es lo que llamamos la **Historia Atómica (Atomic History — la evolución del pensamiento científico sobre la estructura de la materia, desde la idea filosófica de los átomos de Demócrito —del griego 'atomos', que significa indivisible— hasta el complejo modelo cuántico actual; esta historia es una crónica de cómo pasamos de imaginar esferas sólidas a entender que los átomos son mayormente espacio vacío dominado por fuerzas cuánticas y partículas subatómicas invisibles)**. La historia del átomo es la historia del nacimiento de la química y la física moderna.

Durante siglos, la idea del átomo fue puramente especulativa. Fue recién a principios del siglo XIX cuando John Dalton transformó la filosofía en ciencia al proponer la primera teoría atómica basada en experimentos químicos. Desde entonces, cada generación de científicos ha "abierto" una nueva capa del átomo, revelando una complejidad que nadie había imaginado. Entender esta evolución no es solo aprender historia; es entender el proceso mismo del método científico: cómo las teorías antiguas se descartan o mejoran a medida que nuestra tecnología de observación se vuelve más precisa.

El primer gran avance moderno fue el **Modelo de Dalton (Dalton's Atomic Theory — propuesta en 1803, establecía que la materia está formada por átomos indivisibles y que todos los átomos de un elemento dado son idénticos en masa y propiedades; aunque hoy sabemos que los átomos se pueden dividir y que existen isótopos, la teoría de Dalton fue revolucionaria porque permitió a los químicos predecir cómo se combinan los elementos para formar compuestos de manera proporcional y exacta)**. Dalton fue quien dio a los átomos un peso y una medida, permitiendo que la química dejara de ser alquimia para convertirse en una ciencia cuantitativa.

A finales del siglo XIX, J.J. Thomson descubrió que el átomo no era indivisible al encontrar el electrón, sugiriendo el famoso modelo de "budín de pasas". Sin embargo, fue Ernest Rutherford quien dio el salto definitivo con su experimento de la lámina de oro, proponiendo el **Modelo Planetario (Rutherford Model — modelo atómico propuesto en 1911 que establece que el átomo tiene un núcleo central denso y cargado positivamente que contiene casi toda la masa, mientras que los electrones orbitan a su alrededor como planetas alrededor del Sol; Rutherford descubrió que el átomo es mayormente espacio vacío: si el núcleo fuera del tamaño de una mosca en el centro de un estadio de fútbol, los electrones serían como motas de polvo en las gradas más altas)**. Este descubrimiento cambió para siempre nuestra percepción de la "solidez" de la materia.

Finalmente, la revolución cuántica de principios del siglo XX, liderada por Niels Bohr y Erwin Schrödinger, nos llevó al **Modelo de Nube de Electrones (Quantum Mechanical Model — el modelo actual que describe a los electrones no en órbitas circulares fijas, sino en regiones de probabilidad llamadas orbitales; en este modelo, es imposible conocer simultáneamente la posición y la velocidad exacta de un electrón —principio de incertidumbre de Heisenberg—; el átomo es visto como un núcleo rodeado por una "nube" matemática de probabilidad donde la materia se comporta tanto como partícula como onda)**. Este es el modelo que permite el funcionamiento de toda nuestra tecnología moderna, desde los microchips hasta los láseres.

**Casos de Estudio y Aplicaciones Reales**

Un caso de estudio fundamental es el **Experimento de la Lámina de Oro de Rutherford**. Al disparar partículas alfa contra una fina lámina de oro, Rutherford esperaba que todas pasaran de largo. Al ver que algunas rebotaban hacia atrás, comprendió que debían haber chocado contra algo extremadamente denso y cargado en el centro. Este experimento es el ejemplo perfecto de cómo un resultado inesperado en el laboratorio puede derribar una teoría científica establecida (el modelo de Thomson) y dar paso a una comprensión totalmente nueva de la realidad física. Es la esencia de la innovación STEM.

En la tecnología actual, el conocimiento de la estructura atómica es la base de la **Microscopía de Efecto Túnel (STM / Scanning Tunneling Microscopy — técnica que permite observar y manipular átomos individuales en una superficie utilizando una punta metálica extremadamente afilada y el fenómeno cuántico del efecto túnel; esta tecnología es la que nos permite hoy "ver" los átomos que Dalton y Rutherford solo podían imaginar, y es la herramienta fundamental de la nanotecnología para construir circuitos y materiales átomo por átomo)**. Hemos pasado de teorizar sobre los átomos a moverlos con la punta de una aguja electrónica.

Otro ejemplo crítico es el desarrollo de la **Energía Nuclear**. Al entender que el núcleo del átomo concentra casi toda la energía y la masa, los científicos pudieron desarrollar métodos para liberar esa energía mediante la fisión. La historia de cómo pasamos del descubrimiento del núcleo por Rutherford al Proyecto Manhattan y luego a las centrales nucleares civiles es una crónica de cómo el conocimiento básico de la estructura de la materia tiene consecuencias geopolíticas, económicas y éticas masivas que definen el mundo moderno.

**Conclusión Estratégica**

La historia atómica nos enseña que el conocimiento científico es un edificio en constante construcción. Para los futuros químicos, físicos de materiales e ingenieros electrónicos, entender el átomo no es aprender un dibujo estático en un libro, sino comprender una estructura dinámica que sigue revelando secretos. Cada avance en nuestra comprensión del átomo ha traído consigo una revolución industrial y tecnológica, desde la máquina de vapor de la era de Dalton hasta la computación cuántica de nuestra era.

El átomo es la unidad que une toda la ciencia. Al estudiar su historia, aprendemos que incluso las mentes más brillantes pueden estar equivocadas y que la verdad científica siempre es provisional, esperando el próximo experimento que la refine. Para un estudiante STEM, el átomo es el recordatorio de que la realidad es mucho más profunda y fascinante de lo que parece a simple vista, y que la curiosidad humana es la única herramienta capaz de desentrañar los misterios de la materia que nos compone.

🔖 Bluebook v1 · Capítulo I, Sección 1.7.1 — Historia Atómica (Págs. 236–239)
📐 NGSS: HS-PS1-1 (Atomic structure and periodic table) — Use the periodic table as a model to predict the relative properties of elements based on the patterns of electrons in the outermost energy level.
📋 RENAC: EC009 · Química General y Física Atómica
💡 Standards World: Atomic Theory (Teoría Atómica) · Quantum Mechanics (Mecánica Cuántica) · Subatomic Particles (Partículas Subatómicas)""",

"1.7.2": """Si pudiéramos hacer un zoom infinito al interior de un átomo, después de atravesar el inmenso vacío de la nube de electrones, llegaríamos a un corazón denso y ardiente de energía que contiene el 99.9% de la masa de toda la materia visible: el núcleo atómico. Dentro de este núcleo, el protagonista principal que define la identidad de cada elemento en el universo es el protón. La **Estructura: Protones (Protons — partículas subatómicas con carga eléctrica positiva que se encuentran en el núcleo de todos los átomos; el número de protones —número atómico Z— es lo que determina qué elemento químico es el átomo; por ejemplo, cualquier átomo con exactamente 6 protones es carbono, mientras que uno con 79 es oro; los protones son, por tanto, el "DNI" o la huella digital de la materia)**. Sin los protones y su carga positiva, el universo no tendría estructura, ni química, ni luz.

El protón es mucho más que una simple "bolita" con carga positiva. Es una estructura compleja y dinámica que se mantiene unida por las fuerzas más poderosas del cosmos. A diferencia del electrón, que parece ser una partícula fundamental (sin estructura interna), el protón está formado por componentes aún más pequeños llamados quarks. Entender la estructura interna del protón es asomarse a las condiciones que existían en el primer microsegundo después del Big Bang, donde la materia y la energía eran una sola cosa.

La estabilidad y la existencia misma del protón dependen de la **Fuerza Nuclear Fuerte (Strong Nuclear Force — la más poderosa de las cuatro fuerzas fundamentales de la naturaleza; actúa a distancias extremadamente cortas dentro del núcleo para mantener unidos a los protones y neutrones; debido a que los protones tienen carga positiva, su tendencia natural es repelerse violentamente entre sí —fuerza electromagnética—, pero la fuerza nuclear fuerte actúa como un "pegamento" cósmico inmensamente más potente que vence esa repulsión y mantiene el núcleo unido)**. Sin esta fuerza, los núcleos atómicos explotarían instantáneamente y el universo se desintegraría en una sopa informe de partículas aisladas.

En un nivel más profundo, el protón está compuesto por tres partículas fundamentales llamadas **Quarks (Quarks — partículas elementales que son los constituyentes básicos de la materia; un protón está formado por dos quarks 'up' —arriba— y un quark 'down' —abajo—; los quarks están unidos por partículas mensajeras llamadas gluones, que transmiten la fuerza nuclear fuerte; la masa del protón no proviene solo de la masa de los quarks mismos, sino de la inmensa energía de movimiento y de enlace de los gluones que los mantienen confinados, de acuerdo con la famosa ecuación E=mc² de Einstein)**. Somos, literalmente, energía condensada en forma de quarks y gluones.

Una propiedad fundamental del protón es su **Estabilidad Atómica (Proton Stability — la característica de que el protón es una partícula extremadamente estable, con una vida media que se estima superior a los 10³⁴ años —mucho más que la edad actual del universo—; esto garantiza que los átomos que forman nuestro cuerpo y el mundo que nos rodea no se desintegren espontáneamente; la búsqueda de la "decadencia del protón" es uno de los objetivos más importantes de la física experimental, ya que su descubrimiento confirmaría las Teorías de Gran Unificación que buscan unir todas las fuerzas de la naturaleza en una sola ecuación)**. La longevidad de la materia depende de la increíble resistencia del protón.

**Casos de Estudio y Aplicaciones Reales**

Una de las aplicaciones médicas más revolucionarias de la física de protones es la **Protonterapia (Proton Therapy — una forma avanzada de radioterapia que utiliza haces de protones de alta energía para destruir células cancerosas; a diferencia de los rayos X convencionales, que atraviesan todo el cuerpo dañando tejidos sanos en su camino, los protones pueden ser calibrados para liberar la mayor parte de su energía exactamente a una profundidad específica —el pico de Bragg— dentro del tumor; esto permite tratar cánceres complejos cerca de órganos vitales, como el cerebro o el corazón, con una precisión milimétrica y efectos secundarios mínimos)**. Es la física de partículas salvando vidas diariamente en hospitales de vanguardia.

En la tecnología de diagnóstico, utilizamos el protón cada vez que realizamos una **Resonancia Magnética Nuclear (MRI / Magnetic Resonance Imaging — técnica de imagen médica que utiliza potentes campos magnéticos para alinear el espín o giro de los protones de los átomos de hidrógeno en el cuerpo humano; al aplicar pulsos de radiofrecuencia, los protones absorben y luego liberan energía, emitiendo señales que una computadora procesa para crear imágenes detalladas de los órganos y tejidos blandos; debido a que el 70% del cuerpo humano es agua, tenemos trillones de protones que actúan como pequeños imanes naturales que nos permiten "ver" el interior del cuerpo sin cirugía ni radiación ionizante)**.

Otro caso de estudio fundamental es el **LHC (Large Hadron Collider — el acelerador de partículas más grande y potente del mundo, situado en el CERN; su función principal es hacer colisionar haces de protones a velocidades cercanas a la de la luz para romper su estructura interna y observar las partículas fundamentales que surgen de la colisión; fue en estas colisiones de protones donde se descubrió el Bosón de Higgs en 2012, confirmando cómo las partículas adquieren masa)**. El protón es el "proyectil" preferido por los físicos para explorar los secretos más profundos de la realidad.

**Conclusión Estratégica**

El protón es el pilar sobre el que se construye toda la complejidad del universo. Para los futuros bioingenieros, físicos nucleares y oncólogos, comprender la carga, la masa y la estructura del protón es la llave para desarrollar tecnologías que van desde la energía limpia hasta la curación de enfermedades incurables. El protón nos enseña que la identidad y la función de la materia dependen de su estructura interna más profunda.

Somos el resultado de la estabilidad de los protones y de la fuerza que los mantiene unidos. Cada vez que tocas algo, estás sintiendo la repulsión electrónica, pero cada vez que existes, estás dependiendo de la cohesión nuclear de tus protones. Para un estudiante STEM, el protón es el recordatorio de que en el corazón de la materia hay una fuente de energía y orden casi infinita, y que nuestra misión como científicos es aprender a utilizar ese orden para construir un futuro mejor para la humanidad.

🔖 Bluebook v1 · Capítulo I, Sección 1.7.2 — Estructura: Protones (Págs. 240–243)
📐 NGSS: HS-PS1-8 (Nuclear processes) — Develop models to illustrate the changes in the composition of the nucleus of the atom and the energy released during nuclear processes.
📋 RENAC: EC009 · Física Nuclear y Medicina Radiológica
💡 Standards World: Proton (Protón) · Quark (Quark) · Nuclear Force (Fuerza Nuclear)"""
}

with open('/Users/yepz/JSweb/data/modules.json', 'r') as f:
    data = json.load(f)

count = 0
for chapter in data['chapters']:
    for module in chapter['modules']:
        if module['id'] in updates:
            module['fullText'] = updates[module['id']]
            count += 1

with open('/Users/yepz/JSweb/data/modules.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Updated {count} modules")
for mid, text in updates.items():
    words = len(text.split())
    print(f"  {mid}: {words} words / {len(text)} chars")
