# -*- coding: utf-8 -*-
import json

path = '/Users/yepz/JSweb/data/modules.json'

with open(path, 'r', encoding='utf-8') as f:
    data = json.load(f)

fullTexts = {
    "1.14": """Antes de Einstein, el espacio y el tiempo eran dos cosas completamente separadas. El espacio era el escenario vacío e inmutable donde ocurrían los eventos del cosmos. El tiempo era un río que fluía igual para todos en todas partes. Newton los describía así y funcionaba perfectamente para predecir el movimiento de los planetas, las mareas y las trayectorias de los proyectiles. Pero a velocidades extremas y en presencia de masas enormes, el modelo newtoniano fallaba. Le hacía falta algo más profundo.

En 1905, un empleado de la Oficina de Patentes de Berna publicó un artículo que cambiaría para siempre nuestra comprensión del Universo. Albert Einstein, entonces con 26 años y sin acceso a laboratorios, basándose puramente en **experimentos mentales (Thought Experiments — razonamientos hipotéticos que exploran las consecuencias lógicas de premisas físicas sin necesidad de equipo de laboratorio; Einstein los usó para derivar tanto la relatividad especial como la general; son una herramienta central del pensamiento científico teórico)**, propuso la **Teoría de la Relatividad Especial (Special Theory of Relativity — la teoría publicada por Einstein en 1905 que reformuló la mecánica para velocidades cercanas a la de la luz; sus dos postulados son: (1) las leyes de la física son idénticas para todos los observadores en movimiento uniforme y (2) la velocidad de la luz en el vacío es la misma para todos los observadores sin importar su movimiento)**.

Diez años después, en 1916, Einstein publicó la **Teoría de la Relatividad General (General Theory of Relativity — la teoría que Einstein publicó en 1916 ampliando la relatividad especial para incluir la gravedad y la aceleración; su idea central es que la gravedad no es una fuerza a distancia sino la curvatura del espacio-tiempo causada por la masa y la energía; es la teoría más precisa de la gravedad que existe)** —su obra maestra—. Su insight radical: la gravedad no es una fuerza que actúa a distancia como propuso Newton. La gravedad es la **curvatura del espacio-tiempo (Curvature of Spacetime — la deformación geométrica del tejido cuadridimensional del espacio-tiempo causada por la presencia de masa y energía; los objetos con masa curvan el espacio-tiempo a su alrededor, y otros objetos se mueven siguiendo las curvas naturales de esa deformación, lo que percibimos como atracción gravitacional)**. El **espacio-tiempo (Spacetime — el tejido cuadridimensional que combina los tres ejes espaciales —largo, ancho, alto— con el tiempo como una cuarta dimensión; fue introducido matemáticamente por Herman Minkowski en 1908 a partir del trabajo de Einstein; en él, los eventos se describen con cuatro coordenadas en lugar de tres)** combina los tres ejes espaciales con el tiempo en una sola entidad unificada.

Para visualizarlo, imagina una sábana extendida y tensa horizontalmente. Coloca una bola de boliche en el centro: la tela se curva. Ahora lanza una pequeña canica cerca del borde: la canica rodará en espiral hacia la bola de boliche siguiendo la curvatura de la tela. Eso es exactamente lo que hacen los planetas respecto al Sol: no son "jalados" por ninguna fuerza invisible; siguen la geometría del espacio-tiempo que la masa del Sol curva a su alrededor. La gravedad no es un tirón: es una geometría.

La confirmación espectacular de la Relatividad General llegó durante el **eclipse solar total de 1919 (Solar Eclipse Expedition of 1919 — el astrónomo Arthur Eddington viajó a la isla Príncipe, frente a la costa africana, para fotografiar las estrellas visibles cerca del Sol durante el eclipse; encontró que sus posiciones aparentes estaban ligeramente desplazadas respecto a su posición habitual, exactamente en la cantidad predicha por Einstein; este resultado confirmó que la gravedad curva la trayectoria de los rayos de luz)**. El astrónomo Arthur Eddington midió la posición de estrellas visibles cerca del Sol durante el eclipse y encontró que estaban ligeramente desplazadas respecto a su posición normal: exactamente en la cantidad predicha por Einstein. La gravedad del Sol curvaba literalmente los rayos de luz de esas estrellas. El espacio-tiempo era real, medible y exactamente como Einstein lo describía.

En 2015, la colaboración científica **LIGO (Laser Interferometer Gravitational-Wave Observatory — observatorio que usa dos interferómetros de láser de 4 km de longitud en Hanford, Washington y Livingston, Louisiana; detecta perturbaciones en el espacio-tiempo de menos de un milmillonésimo del diámetro de un protón; ganó el Premio Nobel de Física 2017 para Kip Thorne, Rainer Weiss y Barry Barish)** detectó directamente por primera vez las **ondas gravitacionales (Gravitational Waves — ondulaciones en el tejido del espacio-tiempo que se propagan a la velocidad de la luz; son generadas por objetos masivos que se aceleran, como dos agujeros negros o estrellas de neutrones en órbita mutua; predichas por Einstein en 1916 pero no detectadas hasta 2015; su detección fue el equivalente a "escuchar" el Universo por primera vez)**: ondulaciones en el tejido del espacio-tiempo generadas por la fusión de dos **agujeros negros (Black Holes — regiones del espacio-tiempo donde la curvatura es tan extrema que ni siquiera la luz puede escapar; se forman cuando estrellas masivas colapsan gravitacionalmente; su límite se llama horizonte de eventos)** a 1,300 millones de años luz de distancia.

La fusión de esos dos agujeros negros liberó en una fracción de segundo más energía que la luminosidad combinada de todas las estrellas del Universo observable durante ese instante, irradiada completamente como ondas gravitacionales. Esas ondas llegaron a la Tierra como una perturbación del espacio-tiempo más pequeña que una milmillonésima del diámetro de un protón: y LIGO las detectó. Es el equivalente científico de detectar el sonido de una hormiga pisando el suelo desde el otro lado del planeta. Cada vez que dos objetos masivos se aceleran mutuamente, crean ondas en el espacio-tiempo que se propagan a la velocidad de la luz. El cosmos retumba con estas ondas, y ahora tenemos los "oídos" para escucharlas.

---
**🔖 Bluebook v1 · Capítulo I, Sección 1.3 — La Red Espacio-Tiempo** (Págs. 20–22)
**📐 NGSS: HS-PS2-4 · HS-ESS1-1** — Usar las matemáticas para representar las relaciones entre objetos en sistemas gravitacionales.
**📋 RENAC / SEP-CONOCER: EC009 · Física Moderna y Relatividad**
**💡 Standards World:** Espacio-Tiempo · Relatividad General · Relatividad Especial · Curvatura · Ondas Gravitacionales · LIGO · Eclipse 1919 · Einstein""",
    "1.15": """Una de las predicciones más contraintuitivas de la física moderna es que el tiempo no es una constante universal. No fluye igual para todos en todo lugar. El tiempo es **elástico (Elastic Time — la propiedad del tiempo de transcurrir a distintas tasas dependiendo de la velocidad del observador y de la intensidad del campo gravitacional que experimenta; no es una metáfora: es una consecuencia matemática de las ecuaciones de Einstein confirmada experimentalmente con relojes atómicos de alta precisión)**: se estira y se comprime dependiendo de la velocidad a la que te mueves y de la gravedad que sientes. A este fenómeno se le llama **dilatación temporal (Time Dilation — el fenómeno predicho por la relatividad de Einstein por el que el tiempo transcurre más lentamente para un observador en movimiento rápido o sometido a mayor gravedad, en comparación con un observador de referencia; ha sido medido experimentalmente con precisión de nanosegundos usando relojes atómicos en aviones y satélites)**, y no es ciencia ficción. Es física experimental medida con **relojes atómicos (Atomic Clocks — relojes de precisión extrema que miden el tiempo basándose en las transiciones entre niveles de energía de átomos de cesio-133 o rubidio; son exactos hasta un segundo en 300 millones de años; son los estándares de tiempo más precisos de la humanidad y se usan en GPS, telecomunicaciones y experimentos de física fundamental)** de una precisión de **femtosegundos (Femtoseconds — unidad de tiempo equivalente a un millonésimo de nanosegundo, o 10⁻¹⁵ segundos; la duración de un femtosegundo es a un segundo lo que un segundo es a 31.7 millones de años; se usa para medir procesos químicos ultrarrápidos y la precisión de relojes atómicos avanzados)**.

La dilatación temporal tiene dos formas distintas, ambas predichas por Einstein:

**1. Dilatación temporal por velocidad (Relatividad Especial):** Cuanto más rápido te mueves a través del espacio, más lento fluye tu tiempo respecto a un observador estático. Si viajaras en una nave a el 99% de la velocidad de la luz durante lo que para ti serían 7 años, al regresar a la Tierra habrían pasado más de 49 años. Tus amigos habrían envejecido; tú apenas habrías cumplido 7 años más. Este efecto se llama la **paradoja de los gemelos (Twin Paradox — experimento mental en relatividad especial: si un gemelo viaja a velocidades relativistas y regresa, habrá envejecido menos que el gemelo que se quedó en la Tierra; no es realmente una paradoja porque los dos gemelos no son equivalentes: uno experimentó aceleración y el otro no; ha sido verificado con relojes atómicos en aviones)**, y ha sido verificado experimentalmente enviando relojes atómicos en aviones y comparándolos con relojes idénticos en tierra.

**2. Dilatación temporal gravitacional (Relatividad General):** La gravedad también dilata el tiempo. Cerca de un objeto muy masivo, donde la **curvatura del espacio-tiempo** es mayor, el tiempo fluye más lentamente. En la superficie terrestre, el tiempo fluye ligeramente más lento que en el espacio, donde la gravedad es menor. Esta diferencia es de 38 **microsegundos (Microseconds — millonésimas de segundo; 38 microsegundos equivalen a 0.000038 segundos por día; una cantidad aparentemente insignificante que sin embargo produce errores de posicionamiento de 11.4 km en un sistema GPS si no se corrige diariamente mediante compensación relativista)** por día para los satélites del GPS a 20,200 km de altitud.

El sistema de **GPS (Global Positioning System — sistema de navegación por satélite del Departamento de Defensa de Estados Unidos; consta de 31 satélites activos en seis planos orbitales a 20,200 km de altitud; determina posiciones en la superficie terrestre con precisión de metros triangulando señales de tiempo de al menos cuatro satélites simultáneos)** es la demostración tecnológica más cotidiana de que la relatividad no es teoría académica sino ingeniería aplicada. Dos efectos relativistas operan simultáneamente sobre sus relojes: la dilatación especial (por su velocidad orbital de 3.9 km/s) hace sus relojes más lentos en **7 microsegundos por día**, y la dilatación gravitacional (por estar lejos de la masa terrestre) hace sus relojes más rápidos en **45 microsegundos por día**. El efecto neto es +38 microsegundos por día. A 300,000 km/s, ese error acumulado corresponde a 11.4 km de error en posición. Los ingenieros del GPS compensan esto ajustando la frecuencia de los relojes satelitales antes del lanzamiento para que, ya en órbita, coincidan con los terrestres. Cada vez que usas el GPS de tu teléfono para navegar, la física relativista de Einstein está trabajando invisiblemente para darte coordenadas precisas. La relatividad no es solo cosmología abstracta: está en la aplicación de mapas que abriste esta mañana.

La dilatación temporal también es relevante para los planes de viajes a Marte y más allá. Las tripulaciones en misiones largas envejecerán ligeramente más lento que sus familias en la Tierra. En viajes interestelares hipotéticos a fracciones significativas de la velocidad de la luz, los efectos se magnifican dramáticamente: una tripulación que viajara al 90% de la velocidad de la luz durante lo que para ellos sería un año, regresaría a una Tierra donde habrían pasado más de dos años. El tiempo es flexible. El Universo lo decidió así desde el primer instante.

---
**🔖 Bluebook v1 · Capítulo I, Sección 1.3** (Págs. 20–21)
**📐 NGSS: HS-PS2-4 · HS-ESS1-1** — Aplicar razonamiento científico para comprender los efectos de la gravedad y la velocidad sobre el espacio-tiempo.
**📋 RENAC / SEP-CONOCER: EC009 · Física Moderna · Relatividad y sus Aplicaciones**
**💡 Standards World:** Dilatación Temporal · Relatividad General · Relatividad Especial · GPS · Relojes Atómicos · Paradoja de los Gemelos · Microsegundos""",
    "1.16": """Cada vez que abres Google Maps y obtienes tu ubicación exacta en alguna calle de tu ciudad, estás siendo beneficiario de una de las redes de ingeniería más sofisticadas que la humanidad ha construido, y de la correcta aplicación de la física relativista de Albert Einstein. El **GPS (Global Positioning System — sistema de navegación por satélite del Departamento de Defensa de Estados Unidos; declarado operativo en 1995; consiste en 31 satélites activos distribuidos en 6 planos orbitales inclinados 55° respecto al ecuador a una altitud de 20,200 km; garantiza que en cualquier punto de la Tierra al menos 4 satélites sean visibles sobre el horizonte en todo momento)** es un sistema de navegación que funciona triangulando tu posición usando señales de radio de múltiples satélites simultáneamente.

La arquitectura del sistema GPS está compuesta por tres segmentos. El **segmento espacial (Space Segment — el conjunto de satélites que transmiten la señal GPS; cada satélite lleva múltiples relojes atómicos de cesio y rubidio como redundancia; transmite continuamente su posición orbital precisa y una marca de tiempo de nanosegundos de exactitud)** consta de 31 satélites operativos con relojes atómicos a bordo. El **segmento de control (Control Segment — la red de estaciones terrestres repartidas globalmente que monitorizan y corrigen las órbitas y los relojes de los satélites GPS; la estación maestra está en Schriever Air Force Base en Colorado; actualiza los parámetros de cada satélite varias veces al día)** es una red de estaciones terrestres que monitorean y corrigen las órbitas y los relojes de cada satélite. El **segmento de usuario (User Segment — cualquier receptor GPS, desde el chip en tu teléfono hasta los receptores de aviación o agricultura de precisión; solo recibe señales pasivamente, sin transmitir nada; calcula su posición procesando las señales de al menos cuatro satélites)** es tu receptor GPS.

El principio de funcionamiento es la **trilateración (Trilateration — técnica de posicionamiento que usa distancias conocidas a puntos de referencia para calcular una posición desconocida; es distinta de la triangulación que usa ángulos; en GPS, cada satélite define una esfera de posibles posiciones; la intersección de tres esferas da un punto en 3D; el cuarto satélite corrige el error del reloj del receptor)** (no triangulación, que requiere ángulos): cada satélite transmite su posición exacta y una marca de tiempo precisa. Tu receptor calcula cuánto tiempo tardó en llegar la señal y multiplica por la velocidad de la luz para obtener la distancia al satélite. Con una sola distancia estás en algún punto de una **esfera** centrada en ese satélite. Con dos, en un **círculo**. Con tres, en dos **puntos**. Con cuatro satélites, el cuarto permite corregir el error del reloj del receptor —que es mucho menos preciso que los atómicos de los satélites— y obtener la posición en tres dimensiones con precisión de metros o incluso centímetros con GPS diferencial.

Los dos efectos relativistas que actúan sobre los relojes GPS son cuantitativamente distintos y en direcciones opuestas. La **dilatación temporal especial (Special Relativistic Time Dilation — consecuencia de la relatividad especial: cuanto mayor es la velocidad de un objeto, más lento corre su tiempo respecto a un observador estático; los satélites GPS a 3.9 km/s experimentan un retraso de 7 microsegundos diarios respecto a los relojes terrestres)**, causada por la velocidad orbital de 3.9 km/s, retrasa los relojes satelitales 7 microsegundos por día. La **dilatación temporal gravitacional (Gravitational Time Dilation — consecuencia de la relatividad general: a menor campo gravitacional, más rápido corre el tiempo; los satélites GPS a 20,200 km de altitud están lejos de la masa terrestre y en un campo gravitacional más débil, por lo que sus relojes avanzan 45 microsegundos por día más rápido que los terrestres)**, causada por estar en un campo gravitacional más débil, adelanta los relojes 45 microsegundos por día. El efecto neto es +38 microsegundos diarios de adelanto, que equivale a 11.4 km de error acumulado si no se corrige.

Hoy, el GPS tiene competidores globales. Rusia opera el **GLONASS (GLObal NAvigation Satellite System — el sistema de navegación por satélite de Rusia; operativo desde 1995; consta de 31 satélites en órbitas a 19,100 km de altitud; garantiza cobertura global completa)**, Europa el **Galileo (Galileo — el sistema de navegación satelital civil de la Unión Europea; opera con 30 satélites a 23,222 km de altitud; ofrece precisión civil de 1 metro, superior al GPS civil estándar; es el único sistema de navegación diseñado exclusivamente para uso civil)** con precisión civil de 1 metro, superior al GPS civil estándar; es el único sistema de navegación diseñado exclusivamente para uso civil) y China el **BeiDou (BeiDou Navigation Satellite System — el sistema de navegación por satélite de China; su tercera generación, completada en 2020, opera con 35 satélites en tres tipos de órbita; cubre no solo Asia sino el globo completo; es el mayor sistema de navegación por satélite en términos de número de satélites)** con 35 satélites. Los teléfonos modernos reciben señales de múltiples constelaciones simultáneamente combinando mediciones para lograr precisiones inferiores al metro en condiciones óptimas.

Las consecuencias del GPS van mucho más allá de la navegación: precisión en la **agricultura de precisión (Precision Agriculture — el uso de GPS y sistemas de información geográfica para optimizar la aplicación de fertilizantes, pesticidas y agua en campos agrícolas con resolución de metro a metro; reduce costos y el impacto ambiental de la agricultura industrial)**, sincronización de redes eléctricas y telecomunicaciones, guía de aviones y barcos, monitoreo del movimiento de placas tectónicas y medición del rebote isostático post-glacial de la corteza terrestre en Escandinavia. El GPS es la infraestructura invisible que conecta el mundo físico con el digital, y funciona gracias a Einstein.

---
**🔖 Bluebook v1 · Capítulo I, Sección 1.3** (Pág. 21)
**📐 NGSS: HS-PS4-5 · HS-ESS1-1** — Entender cómo los principios físicos de las ondas y la relatividad se aplican en sistemas tecnológicos reales.
**📋 RENAC / SEP-CONOCER: ET002 · Tecnología de Posicionamiento Global y Telecomunicaciones**
**💡 Standards World:** GPS · Satélite · Trilateración · Relojes Atómicos · Velocidad de la Luz · GLONASS · Galileo · BeiDou · Relatividad Aplicada""",
    "1.17": """Existe una velocidad que el Universo ha declarado como el límite absoluto de todo lo que puede existir. No es una restricción de ingeniería que algún día superaremos con tecnología más avanzada. Es una barrera fundamental inscrita en el tejido mismo de la realidad: la **velocidad de la luz (Speed of Light — la velocidad máxima a la que puede viajar cualquier señal, partícula con masa o información en el Universo; en el vacío es exactamente 299,792,458 metros por segundo; es una constante fundamental de la naturaleza representada con la letra c; desde 1983 el metro se define a partir de {r'c'})**, representada en física con la letra **c** = 299,792,458 metros por segundo, exactamente.

Para comprender su magnitud, pon cifras cotidianas en perspectiva. La luz recorre los 384,400 km que separan la Tierra de la Luna en exactamente 1.28 segundos. Cuando ves la Luna en el cielo nocturno, la estás viendo tal como era hace 1.28 segundos. El Sol está a 8 minutos y 20 segundos luz. La luz que te llega ahora mismo salió del Sol cuando estabas haciendo otra cosa hace 8 minutos. La estrella más cercana, **Próxima Centauri (Proxima Centauri — enana roja a 4.24 años luz del Sol; es el objeto estelar más cercano a nuestro sistema solar; orbita el sistema binario Alfa Centauri A y B; alberga al menos dos exoplanetas, uno de los cuales —Próxima b— está en la zona de habitabilidad)**, está a 4.24 **años luz (Light-Year — unidad de distancia astronómica equivalente a la distancia que recorre la luz en un año en el vacío; equivale a 9.461 × 10¹² km, o aproximadamente 9.5 billones de kilómetros; es una medida de distancia, no de tiempo, a pesar de su nombre)**: la luz tarda más de 4 años en llegar desde allí. La Galaxia de Andrómeda, a 2.537 millones de años luz, nos muestra el Universo tal como era hace 2.5 millones de años: cuando los primeros Homo habilis caminaban por África, esa luz salió de Andrómeda.

La razón por la que nada puede superar **c** no es que "ningún motor sea suficientemente potente". Es que la física misma lo prohíbe matemáticamente. La Relatividad Especial de Einstein demuestra que a medida que un objeto con **masa en reposo (Rest Mass — la masa que tiene un objeto cuando está en reposo respecto al observador; en relatividad especial, la masa relativista o masa efectiva aumenta con la velocidad del objeto; un objeto con masa en reposo no nula requeriría energía infinita para alcanzar exactamente {r'c'})** se acelera hacia la velocidad de la luz, su masa relativista aumenta indefinidamente. Para alcanzar exactamente **c**, se necesitaría una cantidad infinita de energía. Por tanto, solo los **fotones (Photons — partículas de luz con masa en reposo igual a cero; al no tener masa en reposo, pueden viajar exactamente a la velocidad de la luz; son los portadores de la fuerza electromagnética)** y otras partículas sin masa en reposo, como los gluones, pueden viajar exactamente a **c**.

Hay algo más sorprendente: la constancia de **c** para todos los observadores. No importa si el observador está quieto o moviéndose a velocidades enormes. No importa si la fuente de luz se aleja o se acerca. La velocidad de la luz medida siempre será la misma. Esto fue confirmado por el famoso experimento de **Michelson-Morley (Michelson-Morley Experiment — experimento realizado en 1887 por Albert Michelson y Edward Morley en la Case Western Reserve University; usó un interferómetro de luz para intentar detectar el \"éter\" —el supuesto medio que transportaba la luz—; el resultado fue negativo: no detectó ninguna diferencia en la velocidad de la luz en ninguna dirección, demostrando que {r'c'} es constante para todos los observadores e independiente del movimiento de la Tierra)** en 1887.

Las consecuencias tecnológicas de la velocidad de la luz son inmediatas en telecomunicaciones. La velocidad de la luz en la **fibra óptica (Fiber Optic Cable — cable de vidrio o plástico ultra puro por el que viaja luz láser mediante reflexión total interna; la luz viaja dentro del vidrio a aproximadamente 200,000 km/s, el 66% de {r'c'} en el vacío; es el medio de transmisión de datos de mayor ancho de banda disponible; la mayoría del tráfico de internet transcontinental viaja por cables de fibra óptica en el fondo de los océanos)** —aproximadamente 200,000 km/s dentro del vidrio— impone **latencias mínimas (Latency — el tiempo que tarda una señal en viajar de un punto a otro en una red; incluso con fibra óptica perfecta existe una latencia física mínima determinada por la velocidad de la luz; ningún hardware puede reducirla más allá de ese límite físico)** que ninguna mejora de hardware puede eliminar. Una señal de Nueva York a Londres —5,570 km— tarda al menos 28 milisegundos solo por propagación física. Los sistemas de **trading de alta frecuencia (High-Frequency Trading — sistemas de compraventa automática de activos financieros que ejecutan miles de transacciones por segundo; la latencia física de la red es un factor competitivo crítico; empresas de HFT gastan cientos de millones de dólares en tender cables más directos o en ubicar sus servidores en el mismo edificio que la bolsa para reducir milisegundos de latencia)** gastan millones en reducir cada milisegundo de latencia física; la velocidad de la luz es literalmente el límite de su competitividad.

La barrera de la luz no es un obstáculo frustrante: es la estructura del Universo. Nos dice que existe un horizonte de causalidad —nada puede afectar a nada más rápido de lo que la luz puede viajar entre ellos— y que vivimos en un cosmos causalmente estructurado. Sin ese límite, la física y la lógica del Universo se romperían. Es el precio de vivir en un Universo coherente, y vale absolutamente la pena.

---
**🔖 Bluebook v1 · Capítulo I, Sección 1.3** (Págs. 21–22)
**📐 NGSS: HS-PS4-1 · HS-ESS1-1** — Aplicar las propiedades de la luz para explicar fenómenos astronómicos y tecnológicos.
**📋 RENAC / SEP-CONOCER: EC009 · Física Moderna · Electromagnetismo**
**💡 Standards World:** Velocidad de la Luz · c Constante · Relatividad Especial · Fotones · Masa Relativista · Experimento Michelson-Morley · Fibra Óptica · Años Luz"""
}

updated = 0
for ch in data['chapters']:
    for m in ch['modules']:
        if m['id'] in fullTexts:
            m['fullText'] = fullTexts[m['id']]
            updated += 1

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"✅ {updated} módulos actualizados correctamente.")
